Trabalho da matéria de Big Data.

Link da base da dados: https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica---cnpj

In [2]:
import os
import glob
import pandas as pd
import gc
import random

Importando e verificando os dados

In [ ]:
import os

print(os.listdir('.'))
path = os.getcwd()

print(path)

['.git', 'Base_de_dados_parquet', 'Cnaes.zip', 'Consulta_CNPJ.ipynb', 'download.zip', 'Empresas0.zip', 'Empresas1.zip', 'Empresas2.zip', 'Empresas3.zip', 'Empresas4.zip', 'Empresas5.zip', 'Empresas6.zip', 'Empresas7.zip', 'Empresas8.zip', 'Empresas9.zip', 'Estabelecimentos0.zip', 'Estabelecimentos1.zip', 'Estabelecimentos2.zip', 'Estabelecimentos3.zip', 'Estabelecimentos4.zip', 'Estabelecimentos5.zip', 'Estabelecimentos6.zip', 'Estabelecimentos7.zip', 'Estabelecimentos8.zip', 'Estabelecimentos9.zip', 'Motivos.zip', 'Municipios.zip', 'Naturezas.zip', 'Paises.zip', 'Qualificacoes.zip', 'Simples.zip', 'Socios0.zip', 'Socios1.zip', 'Socios2.zip', 'Socios3.zip', 'Socios4.zip', 'Socios5.zip', 'Socios6.zip', 'Socios7.zip', 'Socios8.zip', 'Socios9.zip']
c:\Users\mayma\Documents\Projetos\Big_data-Consulta_CNPJ_Brasil

In [1]:
import zipfile

with zipfile.ZipFile('download.zip', 'r') as zip:
    print(f' Quantidade de arquivos dentro do zip: {len(zip.namelist())}')
    print(zip.namelist())
    #Extraindo todos os arquivos do download.zip

 Quantidade de arquivos dentro do zip: 37
['Cnaes.zip', 'Empresas0.zip', 'Empresas1.zip', 'Empresas2.zip', 'Empresas3.zip', 'Empresas4.zip', 'Empresas5.zip', 'Empresas6.zip', 'Empresas7.zip', 'Empresas8.zip', 'Empresas9.zip', 'Estabelecimentos0.zip', 'Estabelecimentos1.zip', 'Estabelecimentos2.zip', 'Estabelecimentos3.zip', 'Estabelecimentos4.zip', 'Estabelecimentos5.zip', 'Estabelecimentos6.zip', 'Estabelecimentos7.zip', 'Estabelecimentos8.zip', 'Estabelecimentos9.zip', 'Motivos.zip', 'Municipios.zip', 'Naturezas.zip', 'Paises.zip', 'Qualificacoes.zip', 'Simples.zip', 'Socios0.zip', 'Socios1.zip', 'Socios2.zip', 'Socios3.zip', 'Socios4.zip', 'Socios5.zip', 'Socios6.zip', 'Socios7.zip', 'Socios8.zip', 'Socios9.zip']

In [ ]:
import io

with zipfile.ZipFile('download.zip', 'r') as zip_principal:
    for arquivo in zip_principal.infolist():
        print(f'Zip interno: {arquivo.filename} ({arquivo.file_size / 1024**2:.2f} MB)')
        
        if arquivo.filename.endswith('.zip'):
            with zip_principal.open(arquivo.filename) as sub_handle:
                try:
                    with zipfile.ZipFile(io.BytesIO(sub_handle.read())) as z_interno:
                        for f in z_interno.namelist():
                            print(f"   └── {f}")
                except Exception:
                    print(f"   [Erro ao ler {arquivo.filename}]")

Sub-zip encontrado: Cnaes.zip (0.02 MB)
   └── F.K03200$Z.D60411.CNAECSV
Sub-zip encontrado: Empresas0.zip (494.16 MB)
   └── K3241.K03200Y0.D60411.EMPRECSV
Sub-zip encontrado: Empresas1.zip (74.27 MB)
   └── K3241.K03200Y1.D60411.EMPRECSV
Sub-zip encontrado: Empresas2.zip (75.44 MB)
   └── K3241.K03200Y2.D60411.EMPRECSV
Sub-zip encontrado: Empresas3.zip (81.17 MB)
   └── K3241.K03200Y3.D60411.EMPRECSV
Sub-zip encontrado: Empresas4.zip (86.08 MB)
   └── K3241.K03200Y4.D60411.EMPRECSV
Sub-zip encontrado: Empresas5.zip (92.87 MB)
   └── K3241.K03200Y5.D60411.EMPRECSV
Sub-zip encontrado: Empresas6.zip (89.93 MB)
   └── K3241.K03200Y6.D60411.EMPRECSV
Sub-zip encontrado: Empresas7.zip (94.24 MB)
   └── K3241.K03200Y7.D60411.EMPRECSV
Sub-zip encontrado: Empresas8.zip (94.34 MB)
   └── K3241.K03200Y8.D60411.EMPRECSV
Sub-zip encontrado: Empresas9.zip (90.11 MB)
   └── K3241.K03200Y9.D60411.EMPRECSV
Sub-zip encontrado: Estabelecimentos0.zip (1959.99 MB)
   └── K3241.K03200Y0.D60411.ESTABELE
Sub-zip encontrado: Estabelecimentos1.zip (325.26 MB)
   └── K3241.K03200Y1.D60411.ESTABELE
Sub-zip encontrado: Estabelecimentos2.zip (319.18 MB)
   └── K3241.K03200Y2.D60411.ESTABELE
Sub-zip encontrado: Estabelecimentos3.zip (348.59 MB)
   └── K3241.K03200Y3.D60411.ESTABELE
Sub-zip encontrado: Estabelecimentos4.zip (326.66 MB)
   └── K3241.K03200Y4.D60411.ESTABELE
Sub-zip encontrado: Estabelecimentos5.zip (319.27 MB)
   └── K3241.K03200Y5.D60411.ESTABELE
Sub-zip encontrado: Estabelecimentos6.zip (347.09 MB)
   └── K3241.K03200Y6.D60411.ESTABELE
Sub-zip encontrado: Estabelecimentos7.zip (328.01 MB)
   └── K3241.K03200Y7.D60411.ESTABELE
Sub-zip encontrado: Estabelecimentos8.zip (319.11 MB)
   └── K3241.K03200Y8.D60411.ESTABELE
Sub-zip encontrado: Estabelecimentos9.zip (346.14 MB)
   └── K3241.K03200Y9.D60411.ESTABELE
Sub-zip encontrado: Motivos.zip (0.00 MB)
   └── F.K03200$Z.D60411.MOTICSV
Sub-zip encontrado: Municipios.zip (0.04 MB)
   └── F.K03200$Z.D60411.MUNICCSV
Sub-zip encontrado: Naturezas.zip (0.00 MB)
   └── F.K03200$Z.D60411.NATJUCSV
Sub-zip encontrado: Paises.zip (0.00 MB)
   └── F.K03200$Z.D60411.PAISCSV
Sub-zip encontrado: Qualificacoes.zip (0.00 MB)
   └── F.K03200$Z.D60411.QUALSCSV
Sub-zip encontrado: Simples.zip (277.83 MB)
   └── F.K03200$W.SIMPLES.CSV.D60411
Sub-zip encontrado: Socios0.zip (216.94 MB)
   └── K3241.K03200Y0.D60411.SOCIOCSV
Sub-zip encontrado: Socios1.zip (47.36 MB)
   └── K3241.K03200Y1.D60411.SOCIOCSV
Sub-zip encontrado: Socios2.zip (46.91 MB)
   └── K3241.K03200Y2.D60411.SOCIOCSV
Sub-zip encontrado: Socios3.zip (46.95 MB)
   └── K3241.K03200Y3.D60411.SOCIOCSV
Sub-zip encontrado: Socios4.zip (47.11 MB)
   └── K3241.K03200Y4.D60411.SOCIOCSV
Sub-zip encontrado: Socios5.zip (47.22 MB)
   └── K3241.K03200Y5.D60411.SOCIOCSV
Sub-zip encontrado: Socios6.zip (46.92 MB)
   └── K3241.K03200Y6.D60411.SOCIOCSV
Sub-zip encontrado: Socios7.zip (46.89 MB)
   └── K3241.K03200Y7.D60411.SOCIOCSV
Sub-zip encontrado: Socios8.zip (47.29 MB)
   └── K3241.K03200Y8.D60411.SOCIOCSV
Sub-zip encontrado: Socios9.zip (47.09 MB)
   └── K3241.K03200Y9.D60411.SOCIOCSV

###Tratamento dos dados

In [ ]:
with zipfile.ZipFile('download.zip', 'r') as zip:
    #Extraindo todos os arquivos do download.zip
    zip.extractall()

In [3]:
import glob

path = r'C:\Users\mayma\Documents\Projetos\Big_data-Consulta_CNPJ_Brasil'
arqs = glob.glob(os.path.join(path, '*.zip'))

arqs = [f for f in arqs if 'download.zip' not in f]

arqs

['C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Cnaes.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas0.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas1.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas2.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas3.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas4.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas5.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas6.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas7.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas8.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Empresas9.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos0.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos1.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos2.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos3.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos4.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos5.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos6.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos7.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos8.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Estabelecimentos9.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Motivos.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Municipios.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Naturezas.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Paises.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Qualificacoes.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Simples.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios0.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios1.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios2.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios3.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios4.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios5.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios6.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios7.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios8.zip',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Socios9.zip']

In [ ]:
import pandas as pd
import pyarrow
import glob
import gc

diretorio_final = r'C:\Users\mayma\Documents\Projetos\Big_data-Consulta_CNPJ_Brasil\Base_de_dados_parquet'

dicionario_colunas = {
    'Empresas': ['cnpj_basico', 'razao_social', 'natureza_juridica', 'qualificacao_responsavel', 'capital_social', 'porte_empresa', 'ente_federativo_responsavel'],
    'Estabelecimentos': ['cnpj_basico', 'cnpj_ordem', 'cnpj_dv', 'identificador_matriz_filial', 'nome_fantasia', 'situacao_cadastral', 'data_situacao_cadastral', 'motivo_situacao_cadastral', 'nome_cidade_exterior', 'pais', 'data_inicio_atividade', 'cnae_fiscal_principal', 'cnae_fiscal_secundaria', 'tipo_logradouro', 'logradouro', 'numero', 'complemento', 'bairro', 'cep', 'uf', 'municipio', 'ddd_1', 'telefone_1', 'ddd_2', 'telefone_2', 'ddd_fax', 'fax', 'correio_eletronico', 'situacao_especial', 'data_situacao_especial'],
    'Simples': ['cnpj_basico', 'opcao_simples', 'data_opcao_simples', 'data_exclusao_simples', 'opcao_mei', 'data_opcao_mei', 'data_exclusao_mei'],
    'Socios': ['cnpj_basico', 'identificador_socio', 'nome_socio_razao_social', 'cnpj_cpf_socio', 'qualificacao_socio', 'data_entrada_sociedade', 'pais', 'representante_legal', 'nome_representante', 'qualificacao_representante_legal', 'faixa_etaria'],
    'Municipios': ['codigo_municipio', 'nome_municipio'],
    'Paises': ['codigo_pais', 'nome_pais'],
    'Qualificacoes': ['codigo_qualificacao', 'nome_qualificacao'],
    'Naturezas': ['codigo_natureza', 'nome_natureza'],
    'Cnaes': ['codigo_cnae', 'nome_cnae'],
    'Motivos': ['codigo_motivo', 'descricao_motivo']
}

for caminho in arqs:
    nome_arq = os.path.basename(caminho).replace('.zip', '')
    tamanho_arq = os.path.getsize(caminho) / (1024**2)
    colunas_arq = None

    for chave, colunas in dicionario_colunas.items():
        if nome_arq.startswith(chave):
            colunas_arq = colunas
            break
        
    if not colunas_arq:
        continue
    
    print(f"Processando: {nome_arq} ({tamanho_arq:.2f} MB)")

    if tamanho_arq > 300:
        porcao = pd.read_csv(caminho, sep=';', encoding='iso-8859-1', header=None, 
                             names=colunas_arq, dtype=str, chunksize=500000)
        
        lote_num = 1
        for lotes in porcao:
            nome_final = f'{nome_arq}_{lote_num}.parquet'
            caminho_final = os.path.join(diretorio_final, nome_final)
            
            if not os.path.exists(caminho_final):
                lotes.to_parquet(caminho_final, index=False)
            
            lote_num += 1
            del lotes
            gc.collect()
    else:
        nome_final = f'{nome_arq}.parquet'
        caminho_final = os.path.join(diretorio_final, nome_final)

        if not os.path.exists(caminho_final):
            df_inteiro = pd.read_csv(caminho, sep=';', encoding='iso-8859-1', 
                                     header=None, names=colunas_arq, dtype=str)
            df_inteiro.to_parquet(caminho_final, index=False)
            del df_inteiro
            gc.collect()

print("\n--- Conversão concluída ---")

Processando: Cnaes (0.02 MB)
Processando: Empresas0 (494.16 MB)
Processando: Empresas1 (74.27 MB)
Processando: Empresas2 (75.44 MB)
Processando: Empresas3 (81.17 MB)
Processando: Empresas4 (86.08 MB)
Processando: Empresas5 (92.87 MB)
Processando: Empresas6 (89.93 MB)
Processando: Empresas7 (94.24 MB)
Processando: Empresas8 (94.34 MB)
Processando: Empresas9 (90.11 MB)
Processando: Estabelecimentos0 (1959.99 MB)
Processando: Estabelecimentos1 (325.26 MB)
Processando: Estabelecimentos2 (319.18 MB)
Processando: Estabelecimentos3 (348.59 MB)
Processando: Estabelecimentos4 (326.66 MB)
Processando: Estabelecimentos5 (319.27 MB)
Processando: Estabelecimentos6 (347.09 MB)
Processando: Estabelecimentos7 (328.01 MB)
Processando: Estabelecimentos8 (319.11 MB)
Processando: Estabelecimentos9 (346.14 MB)
Processando: Motivos (0.00 MB)
Processando: Municipios (0.04 MB)
Processando: Naturezas (0.00 MB)
Processando: Paises (0.00 MB)
Processando: Qualificacoes (0.00 MB)
Processando: Simples (277.83 MB)

## **Atividade** Em duplas ou individual. Para começar agora e entregar no máximo até antes da próxima aula.

Para cada questão, pesquise as informações necessárias (como códigos CNAE), limpe os dados, aplique as regras de negócio solicitadas e gere um arquivo final com os resultados.

**1. O Boom da Construção Civil (Foco em Datas)**
Uma grande loja de material de construção sediada na Bahia quer oferecer parcerias para novas construtoras e incorporadoras. Sua missão é gerar uma lista de potenciais clientes (leads) abertos recentemente.
* **Tarefa:** Pesquise qual é o código CNAE (os dois primeiros dígitos) que representa a divisão de "Construção de Edifícios" e "Incorporação". Acesse a base de Estabelecimentos e filtre as empresas ativas na Bahia que tenham essa divisão como atividade principal. Transforme a coluna de data de início de atividade para o formato de data nativo do Python e filtre o dataframe para manter **apenas as empresas que foram abertas nos últimos 3 anos**. Exporte o resultado para `leads_construcao_recentes_ba.csv`.

**2. O Mercado Oculto Pet (Foco em Buscas Parciais)**
Uma distribuidora de ração percebeu que muitos supermercados e clínicas veterinárias vendem produtos pet, mesmo que esse não seja o foco principal do negócio.
* **Tarefa:** Descubra o código CNAE oficial para "Comércio varejista de animais vivos e de artigos e alimentos para animais de estimação". Na base de Estabelecimentos, encontre empresas ativas onde esse código **não** seja a atividade principal, mas esteja "escondido" no meio do texto da lista de atividades secundárias. Salve o resultado contendo apenas o CNPJ, Nome Fantasia, Bairro e Telefone em um arquivo `leads_pet_secundario.parquet`.

**3. Higienização para Discador Automático (Foco em Regex)**
O time de telemarketing da sua empresa está enfrentando problemas porque o sistema de discagem automática está travando. O motivo é que os números de telefone na base da Receita muitas vezes vêm com letras, espaços, traços ou símbolos bizarros.
* **Tarefa:** Pegue a base de Estabelecimentos e faça uma limpeza na coluna principal de telefones usando Expressões Regulares (Regex) para substituir **qualquer caractere que não seja um número** por um espaço vazio. Exiba no seu código as primeiras linhas da tabela antes e depois da limpeza para comprovar que restaram apenas dígitos numéricos, e exporte a base limpa como `telefones_higienizados.parquet`.

**4. Alvos Valiosos para Fusões e Aquisições (Foco em Conversão de Tipos)**
Uma consultoria financeira (M&A) está em busca de "alvos" promissores. Eles querem focar em negócios classificados oficialmente como "Empresa de Pequeno Porte" (EPP), mas que possuam um capital social declarado muito alto, superior a R$ 2.000.000,00.
* **Tarefa:** Acesse a base de Empresas e filtre por esse porte específico (descubra o código correspondente a EPP). Trate a coluna de capital social (removendo ou alterando caracteres de texto, se necessário) para que o Python a entenda como um número decimal puro (Float). Extraia apenas as empresas que superam estritamente a marca de 2 milhões e salve o resultado em `alvos_aquisicao_epp.csv`.

**5. Campanha de Softwares para Padarias (Foco em Concatenação e Nulos)**
Uma startup desenvolveu um ERP para padarias e confeitarias. Eles farão uma campanha mista (ligação e e-mail) e precisam de uma tabela preparada.
* **Tarefa:** Pesquise o CNAE principal relacionado à "Fabricação de produtos de padaria e confeitaria com predominância de produção própria". Filtre as empresas ativas. Crie uma **nova coluna** na tabela combinando o DDD e o Telefone em um único campo de texto. Como muitas padarias não preenchem o e-mail, em vez de excluir essas linhas, preencha todos os valores nulos/vazios da coluna de correio eletrônico com o texto "NÃO INFORMADO". Exporte a lista final para `contatos_padarias.csv`.

**6. O *Frame* de Amostragem Estatística (Foco em Dicionários)**
Sua consultoria ganhou uma licitação para realizar uma pesquisa por amostragem rigorosa com donos de restaurantes em todo o estado da Bahia. Você precisa montar a "população" base (o *sampling frame*) com o nome legível das cidades para a equipe de campo.
* **Tarefa:** Descubra o CNAE de "Restaurantes e similares" e filtre a base para obter esses estabelecimentos ativos na Bahia. Carregue a tabela acessória de Municípios, transforme-a em um dicionário Python e faça o mapeamento na base principal, substituindo o código numérico do município diretamente pelo seu nome real em texto. Salve a base pronta em `frame_amostragem_restaurantes_ba.parquet`.

**7. Venda de Modelagem Preditiva para o Varejo (Foco em Listas)**
Você desenvolveu um algoritmo de segmentação de clientes e quer vender para o varejo alimentar (supermercados, hipermercados e minimercados), pois eles têm grande volume de dados.
* **Tarefa:** Pesquise os códigos CNAE exatos para Supermercados, Hipermercados e Minimercados. Crie uma lista no Python contendo esses três códigos. Acesse a base de Estabelecimentos e faça um único filtro passando essa lista, de modo a extrair todas as empresas ativas do Brasil que se enquadrem em qualquer uma dessas três categorias simultaneamente. Exporte os potenciais clientes encontrados para `leads_modelagem_varejo.csv`.

**8. Terceirização de Coleta de Dados (Foco em Agrupamento)**
Sua consultoria fechou um contrato de abrangência nacional, mas você precisa mapear em quais estados há maior concentração de parceiros e concorrentes locais para terceirizar a aplicação de questionários.
* **Tarefa:** Pesquise o CNAE referente a "Pesquisas de mercado e de opinião pública" e filtre as empresas ativas no Brasil inteiro que atuam nessa atividade. Em vez de gerar um mailing de contatos, crie uma tabela estatística agrupando os dados para mostrar a **contagem total de empresas ativas por Estado (UF)**. Ordene a tabela do estado com mais parceiros para o estado com menos e salve em `ranking_estados_pesquisa.csv`.

#Tarefa 1:

In [5]:
import glob
import os

diretorio_dados = r'C:\Users\mayma\Documents\Projetos\Big_data-Consulta_CNPJ_Brasil\Base_de_dados_parquet'

#Lista de caminhos com os dados de interesse
dados_estab = glob.glob(os.path.join(diretorio_dados, 'Estabelecimentos*'))

dados_estab

['C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_11.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_12.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_13.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_14.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_15.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_16.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_17.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_18.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_19.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_20.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_21.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_22.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_23.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_24.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_25.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_26.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_27.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_28.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_29.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_30.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_31.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_32.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_33.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_34.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_35.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_36.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_37.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_38.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_39.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_40.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_41.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_42.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_43.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_44.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_45.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_46.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_47.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_48.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_49.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_50.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_51.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_52.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_53.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_54.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_55.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_56.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_57.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos1_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos4_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos8_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_9.parquet']

In [5]:
#Averiguando as variáveis que tem dentro da base de dados
import random

amostras_paths = random.sample(dados_estab, 5)

amostras_paths

['C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_37.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos5_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos7_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos6_5.parquet']

In [6]:
teste = pd.read_parquet(amostras_paths)

In [7]:
teste

,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,nome_fantasia,situacao_cadastral,data_situacao_cadastral,motivo_situacao_cadastral,nome_cidade_exterior,pais,...,municipio,ddd_1,telefone_1,ddd_2,telefone_2,ddd_fax,fax,correio_eletronico,situacao_especial,data_situacao_especial
0,17240667,0001,64,1,SACOS E SACOLAS RENASCER,08,20211021,01,None,None,...,4133,31,86660640,None,None,None,None,MIRIAMAGALHAES.M@GMAIL.COM,None,None
1,17240679,0001,99,1,None,08,20160328,01,None,None,...,7107,11,39738166,None,None,None,None,mariapc12@bol.com.br,None,None
2,17240690,0001,59,1,JYN TECHNOLOGY SERVICOS E T.I.,02,20121201,00,None,None,...,9227,62,83230001,None,None,None,None,JONATHA.CUNHA@JYN.COM.BR,None,None
3,17240702,0001,45,1,MERCADINHO MOUREIRA,08,20180201,67,None,None,...,1247,85,99898610,None,None,None,None,None,None,None
4,17240718,0001,58,1,IVA,08,20180625,01,None,None,...,5813,22,29880292,None,None,None,None,JULICOCEZARE@GMAIL.COM,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499995,36318979,0001,98,1,None,02,20200210,00,None,None,...,3875,71,88833591,None,None,None,None,REIVOLLEY@HOTMAIL.COM,None,None
2499996,36320432,0001,27,1,None,02,20230524,00,None,None,...,7535,41,21051500,None,None,None,None,ANDREA@BERTCON.NET.BR,None,None
2499997,36321923,0001,92,1,IMPETUS DESENVOLVIMENTO E CONSULTORIA EM INFOR...,02,20200211,00,None,None,...,7667,43,30672137,None,None,None,None,PAULOCELEGHIN@OUTLOOK.COM,None,None
2499998,36323138,0001,79,1,None,02,20200211,00,None,None,...,8383,49,99343674,None,None,None,None,ABELJUNG684@GMAIL.COM,None,None
2499999,36324990,0001,60,1,None,02,20240913,00,None,None,...,0856,42,99938912,None,None,None,None,PAULOSERGIOYAMAHA123@GMAIL.COM,None,None

In [8]:
resultados = []

for caminho in amostras_paths:
    df = pd.read_parquet(caminho)
    filtrado = df[df['nome_fantasia'].astype(str).str.startswith('Const' , na = False)]

    if not filtrado.empty:
        resultados.append(filtrado)

df_final = pd.concat(resultados, ignore_index=True) if resultados else pd.DataFrame()

In [9]:
df_final[['cnae_fiscal_principal', 'nome_fantasia']]

  cnae_fiscal_principal     nome_fantasia
0               7319002      ConstruTeles
1               4744099       ConstruNato
2               4399103      ConstruForma
3               4399103      Construcanis
4               1412601  Constellation 42
5               4399103   Construcoes CHA

In [10]:
#"Construção de Edifícios" e "Incorporação"

df_final.columns

Index(['cnpj_basico', 'cnpj_ordem', 'cnpj_dv', 'identificador_matriz_filial',
       'nome_fantasia', 'situacao_cadastral', 'data_situacao_cadastral',
       'motivo_situacao_cadastral', 'nome_cidade_exterior', 'pais',
       'data_inicio_atividade', 'cnae_fiscal_principal',
       'cnae_fiscal_secundaria', 'tipo_logradouro', 'logradouro', 'numero',
       'complemento', 'bairro', 'cep', 'uf', 'municipio', 'ddd_1',
       'telefone_1', 'ddd_2', 'telefone_2', 'ddd_fax', 'fax',
       'correio_eletronico', 'situacao_especial', 'data_situacao_especial'],
      dtype='object')

O código que representa a divisão de "Construção de Edifícios" e "Incorporação" nos dois primeiros dígitos é 41.

Situação Cadastral: O código para empresas Ativas é 02.

In [11]:
from datetime import datetime, timedelta

data_alcance = (datetime.now() - timedelta(days=3*365 + 1)).strftime('%Y%m%d')
print(data_alcance)
print(type(data_alcance))

20230511
<class 'str'>

In [ ]:
#Buscando em todos os arquivos paquet
construcao_civil = []

for path in dados_estab:
    df = pd.read_parquet(path)

    filtros = ((df['uf'] == 'BA') & (df['situacao_cadastral'] == '02') & (df['cnae_fiscal_principal'].str.startswith('41', na = False)))

    df_filtrado = df[filtros]

    if not df_filtrado.empty:
        df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
        if not df_filtrado.empty:
            df_filtrado['data_inicio_atividade'] = pd.to_datetime(df_filtrado['data_inicio_atividade'], format = '%Y%m%d', errors = 'coerce')
            construcao_civil.append(df_filtrado)

construcao_civil

C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]
C:\Users\mayma\AppData\Local\Temp\ipykernel_12796\4084090748.py:12: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtrado = df_filtrado[df['data_inicio_atividade'] >= data_alcance]

:

In [ ]:
print(len(construcao_civil))

39

In [ ]:
df_construcao_civil = pd.concat(construcao_civil, ignore_index = True)

df_construcao_civil

,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,nome_fantasia,situacao_cadastral,data_situacao_cadastral,motivo_situacao_cadastral,nome_cidade_exterior,pais,...,municipio,ddd_1,telefone_1,ddd_2,telefone_2,ddd_fax,fax,correio_eletronico,situacao_especial,data_situacao_especial
0,50573007,0001,70,1,None,02,20230506,00,None,105,...,3279,73,82012498,0000,00000000,None,None,ASERVICOSADM@GMAIL.COM,None,None
1,50598966,0001,40,1,ZN 6,02,20230509,00,None,None,...,3469,71,32635719,None,None,None,None,ADM@ZANAN.COM.BR,None,None
2,50606046,0001,27,1,AMAZONAS CONSTRUCOES E EMPREENDIMENTOS,02,20230509,00,None,105,...,3827,75,82797111,None,None,None,None,AMAZONIACONSTRUCAO881@GMAIL.COM,None,None
3,15742639,0002,09,2,EURO POCOS,02,20230510,00,None,None,...,1112,62,96208858,None,None,None,None,EUROPOCOSARTESIANOS@GMAIL.COM,None,None
4,50671918,0001,30,1,GONCALVES CONSTRUCAO E INCORPORACAO,02,20230515,00,None,None,...,3515,75,91458078,None,None,None,None,VALDINEYGONCALVES05@HOTMAIL.COM,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3936,65952076,0001,62,1,VERTICE EMPREENDIMENTOS,02,20260327,00,None,None,...,1112,77,98288633,77,99595581,77,98288633,IBSENOPA@HOTMAIL.COM,None,None
3937,66061143,0001,11,1,CONSTRUTORA PROJECT BAHIA,02,20260402,00,None,None,...,3943,73,82442494,73,88218141,73,36131440,RADAMIS27@BOL.COM.BR,None,None
3938,73661472,0015,64,2,None,02,20260406,00,None,None,...,3515,75,36258040,None,None,None,None,CONTABILIDADE@CEPRENG.COM.BR,None,None
3939,66169562,0001,71,1,ARQTERRA CONSTRUTORA E INCORPORADORA,02,20260409,00,None,None,...,3807,73,99554535,None,None,None,None,ARQTERRA.CONSTRUTORA@GMAIL.COM,None,None
3940,66185523,0001,68,1,CONDOMINIO PRAIA SERRA GRANDE,02,20260410,00,None,None,...,3953,77,34246218,77,32025563,77,34246218,ATENDIMENTO@OLIVEIRANOVAIS.COM.BR,None,None

In [ ]:
df_construcao_civil.to_csv('leads_construcao_recentes_ba.csv', index = False, sep = ';', encoding = 'utf-8-sig')

**2. O Mercado Oculto Pet (Foco em Buscas Parciais)**
Uma distribuidora de ração percebeu que muitos supermercados e clínicas veterinárias vendem produtos pet, mesmo que esse não seja o foco principal do negócio.
* **Tarefa:** Descubra o código CNAE oficial para "Comércio varejista de animais vivos e de artigos e alimentos para animais de estimação". Na base de Estabelecimentos, encontre empresas ativas onde esse código **não** seja a atividade principal, mas esteja "escondido" no meio do texto da lista de atividades secundárias. Salve o resultado contendo apenas o CNPJ, Nome Fantasia, Bairro e Telefone em um arquivo `leads_pet_secundario.parquet`.

In [ ]:
valores = teste.loc[
    teste['cnae_fiscal_principal'].str.startswith('4789', na = False),
    'nome_fantasia'
].unique()

print(list(valores))

[None, 'ECOVILLE NOVA PRATA', 'IMPORIUM DAS CORES', 'DUBEN FESTAS', 'AGRO OLIVEIRA', 'UNITA LTDA', 'EXCLUSIVA', 'ERVA DOCE PRODUTOS NATURAIS', 'ENCANTO DAS FLORES', 'COUROART', 'ATACADAO DO 3 E 5', 'COSMOLISTICO', 'PET FORTE CASA DE RACAO E ACESSORIOS', 'ETA WORD', 'SHOPDATA AGENCIAMENTO DE SERVICOS E NEGOCIOS', 'MAX SHINE', 'VERDE CRIATIVO', 'COELHO FOTOGRAFIAS', 'BIG STORE', 'JOIAS ARTS', 'RECEBIMENTO PAYMENTS DETRAN & SERVICOS LTDA', 'DY PRATA JOIAS', 'TAIS ACESSORIOS IMPORTADORA E DISTRIBUIDORA', 'ANIMAL FOOD', 'ESMERALDA PANTANAL', 'COMERCEALL BRASIL', 'USA MADEIRA', 'LUCAS RACOES', 'GOINSTA', 'BOPDY BOOM', 'AGROPET BARAO', 'AGM DISTRIBUICAO', 'BIO TERRA SUPLEMENTOS', 'NOSSO PET', 'AGROPECUARIA E PETSHOP CASTRO', 'WORLD CLEAN', 'BKR LUMINOSOS', 'RAYRA BIJU', 'PIONEIRA PETS', 'MINI FLOR KIDS', 'LONFIRE TECNOLOGIA', 'JFAGROPRIME', 'AGROMARQUES', 'IMPERIO BIJUTERIAS', 'PETSHOP SANTIAGO', 'VO MARIA UTILIDADES', 'EDNAGIFTS', 'CARAJAS MAIS VARIEDADES', 'MWAGRO', 'CHAMPSECOMMERCE', 'AGROMEC SUPRIMENTOS', 'BLUE CLEAN', 'FLORICULTURA JOINVILLE', 'AGRO TERRA', 'AGROJOPET', 'ONE SHOPP STORE', 'LOJA DA ALEGRIA LTDA', 'KARIN PET SHOP', 'FOGOS CARAMURU', 'CAMPELLO DISTRIBUICAO', 'HOUSE PATAS', 'TEC SOLAR', 'AGRO RACOES 2', 'CARTAZ SC', 'KALANI PRATAS', 'LUSAMED', 'DZ COMERCIAL VAREJISTA LTDA', 'PLANTAS & PAISAGISMO', 'EVOLUIND', 'NOHKER', 'AGROPET CARIRI', 'MARILIA RACOES & CIA', 'TREVO 61', 'QUINTAS RIO DESIGN', 'AQUI BARATO', 'LUCIANE CLINICA VETERINARIA', 'CASA DE RACAO PAPAGAIO', 'L V CONSERVAS', 'FORA DA CAIXOLA PRESENTES CRIATIVOS LTDA', 'AGROPECUARIA PERINI', 'MUNDO DOS BICHOS', 'VALERIO DOLCE', 'TENENTE EMBALAGENS', 'E&M BIJUTERIA', 'ALVES NUTRICAO ANIMAL', 'CARVAO NELORE', 'SOS PISCINAS', 'LAGO EXTINTORES', 'SANTA FLOR', 'GABI RACOES', 'RLS MKT & IMPOTS', 'FLANE IMPORTACOES E COMERCIO', 'BETA DENTAL', 'TE2C', 'AGROPET PATAS E GARRAS', 'BRUG PET LOVE', 'ESPACO DA DANCA MANU VILLELA', 'SHOPPING DA LIMPEZA', 'ATELIER ZUY COSTA', 'VIBEUM', 'AGROPECUARIA PAULINO E OLIVEIRA', 'MISSYE JOIAS', 'ROLME SOLUCOES EM MEDICAO', 'BOXY FITSIGNATURE', 'AGROLOZ', 'TSMF COMERCIO VAREJISTA', 'PORTO VEDACOES', 'J E L PRIME MOBILIARIO CORPORATIVO', 'ESPACO CATOLICO DIVINO AMOR', 'CASA DE RACOES BILLY BONNIE', 'FLORA MISTICA', 'PADARIA PET DOG HOUR', '1001 COISAS', 'ILE ASE ODARA', 'AQUA SUMMER', '****', 'LOJAS MADAM', 'IPS LOG', 'ZELLAR', 'S&A EMBALAGENS', 'MASTER HIGIENE E LIMPEZA', 'CASA DAS FRALDAS', 'PUNGA CAFES ESPECIAIS', 'EXPRESS LIST COMERCIO DE PRODUTOS PARA ANIMAIS', 'CASA DA RACAO', 'ALENCAR PLACAS PARA VEICULOS', 'DAZMIX', 'ALPLASTIPEL', 'ARTHUR TOLDOS', 'BENDITUUS ESPACO CATOLICO', 'VHV MARKET', 'FLIP COMERCIO', "D'RACOES & CIA", 'HOME PET', 'EZYCART ONLINE', 'INOVA PET', 'MILTON SHOP', 'CAMILA ANDRADE ACESSORIOS', 'PATRICAGRO', 'ANIEL FLORES E PRESENTES CAMPINAS', 'PS GOMES PRODUTOS DE LIMPEZA', 'RAMS COMERCIAL', 'FOUR KING PET SHOP', 'BEST MULTI SHOP', '* VIVEIRO - FLORES E FRUTOS *', 'FLOWERPRINTY', 'ZARI SEMI JOIAS', 'MERCADINHO WM', 'DURAO COMERCIAL AGRICOLA', 'PETVITTA', 'ELI DA RAINHA', 'SG BICHOS', 'RDLA AGROPECUARIA', 'AQUANOOK', 'REALEZA FLORES E EVENTOS', 'ROSA FESTA', 'PLACAS BRASIL', 'NAVIEXPRESS IMPORTACAO', 'CD INSTINTO SEXY', 'PLANETA RACOES DEPOSITO FECHADO', 'VAREJAO DAS RACOES', 'JACSON FLORA', 'EMPORIO FERREIRA MILANO', 'CASA DO MILHO', 'FOLIA E FESTA', 'PURPURINA BIJU', 'VRL IMPORT EXPORT AND CONSULTANCY', 'DUDYCELL', 'BELA FOTO PERSONALIZACAO', 'CLUBE DOS OXENTEIROS', 'INOVAR DISTRIBUIDORA', 'BAZAR DOS ORIXAS', 'E-FORRAGENS ALIMENTACAO ANIMAL', 'SIRIUS SEMIJOIAS', 'PET SHOP LAMBRE', 'SUPER MEGA CABELOS', 'CASA DE RACOES GEOVANIA', 'CASA DA VACA', 'PUTSZGRILA PRODUCOES', 'PRESIDENTE PLACAS', 'VIVEIRO SANTA INES', 'MANDACARU', 'NOVA PET FOOD', 'NEW WAY BRINDES', 'BIJU DORAH', 'DOGSTORE', 'ZAGUT', 'G V A ARTIGOS PARA PISCINA', 'BECKER JOIAS', 'BRINDISSIMO PRESENTES PERSONALIZADOS', 'ISA FESTAS', 'KARDENE COMERCIO', 'LUZ SOPHIA CASTILLA', 'J B PRODUTOS DE LIMPEZA LOJA 02 UTILIDADES DOMESTICAS', 'CAMAPUA', 'AGRO 10', 'PASSOS COMERCIAL', 'SANTISSIMA ACESSORIOS', 'CASA DO CRIADOR', 'VILLA SURICATTO', 'ESCRITORIO DE PAGAMENTOS E QUITACAO ON-LINE', '----', 'ALFA PRIME', 'OLIVEIRA AGROPET JAPUIBA', 'LANDO RACOES', 'M.A.P VARIEDADES', 'IMAGENART COMERCIO BIJUTERIAS E ARTESANATOS LTDA', 'PLACAS ONLINE', 'PET VITALITY', 'ATTACK PREVENCAO', 'AGROVICULTURA BATISTENSE', 'MAGAZINE IMPORTACOES', 'JC LIMPEZAS', 'RANCHO DO COLONO', 'LOJAS MIX', "GIULLIA'S PRESENTES", 'DUTRA LONAS', 'AGRO AF', 'PRUDEMPLAK', 'FLORICULTURA FLOR E CIA FLORES E PRESENTES', 'DISTRIBUIDORA TRIEX LIMP', 'GIPEL EMPORIO PET LTDA', 'JOSIANA BORDADOS', 'PLANETA ANIMAL PET SHOP', 'JR PRODUTOS DE LIMPEZA', 'CISSA MOOD ACESSORIOS E PRESENTES', 'ARPEN SOLUCOES', 'CAVABLANCO', 'BOVI PREMIUM AGROPECUARIA', 'DIBOTEC DISTRIBUIDORA', 'DSLINS MAGAZINE', 'HERBIMAQ PECAS AGRICOLAS E FERRAMENTAS', 'QUALITY & SAFETY', 'LIVIRRE E-COMMERCE', 'PESCADO THOR FERNANDES', 'FENO SANTA TERESINHA', 'NOVA GIBIM REPRESENTACOES', 'BIXO NO CAPRIXO', 'SOL NASCENTE COMERCIO E REPRESENTACAO', 'EMANUELA GALDINO ASSESSORIA', 'AGROPECUARIA CASA DO FENO', 'VOLK REPRESENTACOES', 'RDR PAISAGISMO', 'EMS PISCINAS', 'KAMAFAYA', 'MORANA', 'QUANTUM OXYGEN TECHNOLOGIES', 'GLAMOUR BIJU E ACESSORIOS', 'PET SHOP PRATICAO', 'PREMATURE SHOP', 'MULTI-PLACAS', 'CHAPAS E TUBOS MARINA', 'OURO PRETO BABACU', 'LOJAS GONCALVES', 'X-UTILIDADE', 'EMPORIO DONA ADELIA', 'VN RACAO', 'SUPER MERCADO JOSE ROBERTO', 'SINGULLAR FLORES E GIFTY BOX', 'ETHERIAN SERVICES LTDA', 'MORANA PARQUE SHOPPING MACEIO', 'ASTROMIX', 'CK', 'DALAS COLCHOES', 'CASAS CANINDE', 'LIS RACOES', 'MEGA SOM', 'FAZENDA AGUA COMPRIDA', 'ESTE FLORES', 'COMERCIO DE ARTIGOS RELIGIOSOS OGUM MENINO', 'CASA DA RACOES NOVA OPCAO', 'PET SHOP LITORAL', 'ROMA JOIAS', 'AGRO COMERCIAL GRANDE VALE', 'COMMERCE UPP', 'LOJAO GIRA RAPIDO', 'JC DISTRIBUIDORA E COMERCIO', 'COSTUME ACESSORIOS', 'METAIS SH GESTORA', 'WL EXTINTORES', 'EMPLACAKI PLACAS MERCOSUL', 'GUIPACK', 'LARUBY ACESSORIOS', 'ILE DOS ORIXAS', 'FLOR AMOR COMERCIO DE PLANTAS', 'SANTO SANTO SANTO', 'POLOPET', 'JM RACOES & VETERINARIA', 'EXECUTIVA EXTINTORES', 'CPA PETSHOP', 'PARDAL BARBANTES E CIA', 'MOV SOLDAS', 'NUSH COMERCIO', 'ABC PLACAS', 'ARISTEU FOGOS', 'CASA DE RACAO JABA', 'FLORICULTURA HORTENCIA', 'RL UTILIDADES', 'MAPA', 'AVENIDA AGROPET', 'CASA DAS FLORES CORUPA', 'SHOPPING AMAZONAS', 'NATER COOP', 'RAP COMERCIO DE ANIMAIS', 'NUPA ESTUDIO', 'PET DOG', 'CLEAN NACIONAL', 'ECOVILLE ARACAJU', 'J.A. JOIAS COBRANCAS', 'RCF COMERCIO DIGITAL', 'OMEGA ARMAS E MUNICOES', 'RECANTO DAS FLORES', 'MAGNO PRINT', 'EMPORIO BRASIL', 'STAR RACOES E MATERIAIS DE CONSTRUCAO LTDA', 'CLUBE DO VET', 'FOTO E ALBUM', 'ESPACO DE ARTE CABOCO', 'GCI TRANSPORTES', 'TF QUADROS E DECORACOES', 'LIDER PISCINAS', 'JOAO DE BARRO DISTRIBUIDORA', 'IMPERIAL PLANTAS', 'PEROLA STORE', 'OLIVEIRAS SITIO IPE', 'ATACADAO PET', 'B B RACOES', 'E DO NENEM PRODUTOS INFANTIS', 'EKCH IMPORTS', 'AGROPET MIRANDA', 'AGROPET RECANTO DOS BICHOS', 'LOJAO DA AMAZONIA', 'IMPERIO DOS IGBAS', 'ROSA DE SARON', 'SACOS SUPERSACO', 'MONY BIJOUX 5.1', 'LOPDIER GLOBAL', 'CRIS CAPPELLARI ARTE EM CERAMICA', 'AGROPET FAZENDINHA', 'PIU BOX', 'FABI JOIAS', 'LEIDE CUNHA EMBALAGENS', 'ESTACAO DA MODA E VAIEDADES', 'RURAL FORT', 'GRAUNAS FLORES', 'CENTRO VETERINARIO VILA FORMOSA', 'LUIZIANA SHOP', 'BRISA SUAVE AROMAS', 'BM EMBALAGENS', 'BELLE BIJUTERIAS', 'FERNANDES MAIA', 'SJA COMERCIO DE ACESSORIOS', 'PET ZAP', 'IMPERIO CLEAN', 'PRAIANO', 'COPERAMAS', 'VM SHOPPING', 'JUNQUEIRA ACESSORIOS', 'DANILLO COSTA COMERCIAL', 'YELLOW PINE HOUSE BRZ', 'CF FERRAMENTAS', 'PAM PETS', 'DF SCORE E CONSULTORIA', 'SAMANTA FRANCO DECOR', 'EUDA MARIA DA SILVA', 'RACAO E CIA', 'M. PET', 'POTENZZA', 'DA LIRA FESTAS', 'CENTER PANOS GOIANIA', 'RAIZ FORTE', 'LB BRINDES', 'COMERCIAL ALVES', 'MEGA PRODUTOS DE LIMPEZA E ACESSORIOS', 'TOUCHER ARTIGOS DE PRAZER', 'MARLEM COMERCIO E IMPORTACAO', 'BARBARA JORGE ATELIE FLORAL LTDA', 'WDX CORPORATION', 'MIX ACESSORIOS', 'KARINA VENDAS E MODAS', 'FLORICULTURA FRUTO DO MILAGRE', 'SAO FRANCISCO ATACAREJO DAS EMBALAGENS', 'ITA SOLDAS', 'LJR UNIFORMES', 'AGRORACOES', 'PANORAMA', 'PET SHOP SCOOBY-DOO', 'ELO DE LUXO JOIAS', 'CRISTAL CLEAN', 'JEITO CAMPEIRO', 'HABIBI UTILIDADES', 'HAVANA PRESENTES E FLORICULTURA', 'A JOIA.', 'JACIYDO COMUNICACAO VISUAL E GRAFICA CORPORATIVA', 'JC ACESSORIOS', 'SERAFINS ARTE COM AFETO', 'SERRA DOS BICHOS', 'YGG JOIAS E SEMIJOIAS', 'ECONOSHOP', 'P. GRACA COMERCIAL', 'AGRO PET SERGINHO', 'LUMINA MAIS VENDAS', 'SERVECAMPO BR', 'CASINHA ECOLLAB', 'AGIL DISTRIBUIDORA', 'SPOLETA', 'IMAGINE JARDIM PAISAGISMO', 'VALEN ACESSORIOS', 'CASA DE RACAO DA SILVA', 'DLF EQUIPAMENTOS', 'PORTOPLASTIK', 'JOAO BRANCO CASA DE RACOES', 'FORTE SERVICOS ESPECIALIZADOS', 'ZARPY BAGS & BIJUX', 'UP', 'PREMIUM EPS', 'PLANETA RURAL', 'CASA DO PASSARINHEIRO', 'RJ REALCE JOIAS FOLHEADOS E PRATAS', 'ESPACO DA PISCINA', 'NUCUP PRESENTES PERSONALIZADOS', 'NOVA MASTER VARIEDADE', 'PLAST AGRO DISTRIBUIDORA', 'TONKA COMERCIO DE EMBALAGENS LTDA', 'CASA DE RACOES MENDONCA', 'LEOPLAST & DOCES', 'EMPLACA RAPIDO', 'BELLA SEMIJOIAS DE LUXO', 'GARDEN PAISAGISMO', 'CASA DA TELA MOSQUITEIRO', 'PETSHOP MUNDO', "FARIA'S PET", 'AGROBOI', 'PLANTAE GARDEN CENTER', 'AGRO PET DOMINGOS', 'LOJA AMO', 'CASA DE RACAO TICO TICO', 'LOLLI PET', 'SHOPPING DE OGUM', 'RIPNDIP ELETRON', 'ARTVIVA DECORACOES', 'HSM BOMBONAS', 'RACAO & CIA II', 'IPET DISTRIBUIDORA', 'AGROPECUARIA ZANETTI', 'R&R RACOES', 'AGRO BARTH', 'USE CLAIR', 'LORII JOIAS', 'MINHA CANECA FAVORITA', 'CAMPOS MANIA', 'M&P UTILIDADES', 'H2ORTA', 'MUNDO PET LTDA', 'SERVO COMERCIO E SISTEMAS JUIZ DE FORA', 'MIMO PRESENTES', 'LOGUNEDE COMERCIO', 'DISTRIBUIDORA REGISTRO-SP', 'SC ARTESANATO CRIATIVO', 'CLOVES AGROPECUARIA', 'IMPERIAL RACOES', 'DG OLD ART', 'IZZIE BIJU', 'KZZA REAL', 'NATAL LAND', 'MIMOS DA VA', 'R&T DIGITAL COMMERCE LTDA', 'AMOR DE LUXO', 'AGROPECUARIA LAGOA GRANDE', 'JDL PET SHOP', 'PET CHAVES RACOES', 'ALLCANCE AGRICOLA', 'SERENA', 'SAO JOSE AGROPECUARIA', 'AVT SHOP', 'ESPACO PET DOG & CAT', 'HJK COMERCIO LTDA', 'FOR U BRINDES', 'ASK II ELEVADORES', 'PONTO RURAL', 'AGROFALCAO', 'SHOP PLAST DELIVERY', 'MULTISHOP', 'ARILDO TACTICAL STORE', 'MILO DINGO DECOR', 'VICTOR RACOES', 'MS ATACADO E VAREJO LTDA', 'MASTERPACK', 'ZAYAH ACESSORIOS', 'WONIX STORE', 'SAUDE ANIMAL AGROVETERINARIA', 'GREENER BRASIL SOLUCOES', 'HUIJIN TECHNOLOGY', 'OAKHOUSE', 'SPRINTERTEC', 'JS PRESENTES', 'E DOS BICHOS', 'POLILON BRASIL', 'TRACFLOOR DERIVADOS PLASTICOS', 'LUA ACESSORIOS', 'LARI FLOWERS', 'S.O.S ANIMAL', 'ELKA FLORES E JARDINS', 'ARES DISTRIBUIDORA', 'LAGUNA LIMP', 'CORPO 10 SHOP GOIANIA', 'FLEXSHOP', 'KING PLACAS', 'GALPAO DA LIMPEZA', 'CASA DAS BALANCAS E MAQUINAS', 'AGRO PET BELVEDERE', 'CANTINHO CRIATIVO PERSONALIZADOS', 'GARDEN ALTEROSA', 'NUNES CENTRO DE SOLUCOES EM LIMPEZA E HIGIENIZACAO', 'SHOW DO REAL', 'JARDINAGEM IMPERIO', 'B.BALLOON', 'BB KEE', 'FERRAGEM E CASA DE TINTAS FENIX', 'AROEIRA ARTIGOS RELIGIOSOS', 'CB&R', 'MIRANTE SOUVENIR', 'FLORICULTURA NATURALIS', 'MARICOTA PRESENTES E DECORACAO', 'PET GRIMAES', 'FAST BOX COMERCIO DIGITAL', 'ILHA DAS FLORES FLORICULTURA', 'MIX EMBALAGENS', 'DART HORTO', 'AMENITI', 'SUZY RACOES E UTILIDADES', 'AGROPET MENINO DA PECUARIA', 'MIRANDA CINTAS E CORRENTES', 'Q. C.', '3 G PAISAGISMO', 'HT COMUNICACAO', 'LCA', 'DISTRIBUIDORA MIXMARA', 'JF RACOES', 'MEU CANTINHO PRODUTOS DE LIMPEZA', 'J2 PLACAS PATOS', 'IDEAL CONTAINERS', 'PET ROCHA CAJAZEIRAS', 'B2 COMERCIO', 'AQUAVINIL PISCINAS BARREIRINHAS', 'DEIA DECOR', 'PE OUTLET MAGAZINE', 'ESOTERIC CENTER', 'RELANCE', 'START DIGITAL CONSULTORIA', '3D PRODUTORA', 'CHRISTMAS STORE', 'IGOR SCHIAVOLIN FENO', 'CKM FESTAS', 'M PLUS VARIEDADES', 'G M FIRE EXTINTORES', 'PIRA PRODUCOES', 'VALE DOS LORDS PNZ', 'FICA LIMPO', 'HANNAH COMERCIO E DISTRIBUICAO DE EMBALAGENS', 'PET PUPPYS', 'DV COSMETICOS E VARIEDADES', 'LIMPFER', 'MEGAMARKET', 'GEN PRIME PRODUTOS DE LIMPEZA', 'STORE RICKY BRASIL - RRS JR', 'HORTO DO SERTAO LTDA', 'INGGA +', 'AGRO TERRA TRANSPORTES', 'PRISCIELEM COMERCIAL', 'MD FIRE COMERCIO', 'REALE RACOES', 'BIG DOG PET CENTER', 'INTELISERV - SERVICOS INTELIGENTES', 'ANIMAL PET STORE', 'LJ COMERCIO E SERVICOS', 'CENTER PANOS CURITIBA 02', 'RENATA FLORICULTURA', 'TARUMA', 'GCSMARTSHOP', 'PRISMA CONCEPT', 'PISCINAO DA BARRA', 'A L BIJUTERIAS', 'MORADA EXU DO OURO', 'PROTECFIRE', 'ZEUS FIREARMS', 'SARA DE OGUM COMERCIO E SERVICOS', 'RACOES CAMBARA', 'FLORICULTURA PAMPULHA', 'ESSENCE DISTRIBUIDORA', 'FERRO VELHO PORTUGAL', 'SHOPPING DOS ANIMAIS', 'CASA DE RACAO LAMBE SAL', 'SPLASH PISCINAS', 'V.J.', 'ALFA RJ', 'LABELLE PRESENTES E ACESSORIOS', 'FLORA VIVA FLORICULTURA', 'WR REPRESENTACOES', 'PREMIARTE DISTRIBUIDORA DE MATERIAIS', 'ERICA CAMPOS ACESSORIOS', 'BRILHANTE FESTAS E PRESENTES', 'LUDIES PLASTICOS', 'JOAO SMART', 'PET CAMP', 'ACE PRIME', 'PET RAMOS LTDA', 'ALGORITI', 'G-PRODUCTS', 'BK PRODUCOES', 'AGROPET MOREIRA', 'BOX FOR BOYS AND GIRLS', 'AGROPECUARIA TORMEN', 'VANESSA JOIAS', 'GUSTAVO BIJOUX', 'AGROPECUARIA JOSE MARTINS', 'MUNDO EVOLUTION', 'A & R RACOES', 'GLANZ BIJOUX', 'VERNNER MODAS', 'AURORA STORES', 'MARGRAF COMERCIO DIGITAL ONLINE', 'LUA JOIAS LOVERS', 'PEPITO PET SHOP', 'GLOBAL ASSESSORIA', 'SECRETA LUXURIA', 'WINGATE VAREJO', 'DISCONNECT HOME', 'THIME VENDAS ONLINE ECOMMERCE LTDA', 'BIG FESTA', 'EXCELLENCE CLEANING', '4 PATAS CLUB', 'GP IMPORTACAO', 'ENERGIA EM AROMA', 'DOMINIC', 'ARTE 11', 'CARLITO CASA DE RACOES', 'GROUP PET', 'CANTINHO DO ANIMAL', 'ZITTA JEWELRY', 'AMIGAS DE ALUGUEL', 'VERDONA AGROPECUARIA', 'CREER GALERIA', 'TRIADE', 'FILHOS DA TERRA', 'IMAGINATIVA ART&IMPORT', '7 COPAS', 'CASA DA LIMPEZA', 'NANDIN CEREAIS', 'M J EMPREENDIMENTOS', 'JHESSY CABELOS', 'BOB PATIO PAULISTA', 'THE BEST VIP', 'MACRO ATACAREJO', 'AGRO FARM', 'HORSE PLACE', 'FLORICULTURA FLORES BELLA', 'MACEIO PISCINAS', 'NERD!VERSE', 'CIA DA LIMPEZA', 'C. L. IMPORTS', 'SALZ CERAMICA', 'LAFEMME', 'HIGIDESC', 'DONNA MAKE', 'COSETT STORE', 'CHACARA DO QUIRIRI', 'LOUKAS POR LACE', 'GAG TECNOLOGIA', 'VENETO STORE', 'MEGA EXPRESSAO IMPORTS', 'OP MULTISTORE', 'AGRO SHOPPING DO VAQUEIRO', 'REINO AGROPET', 'J R ATACADISTA', 'CENTRAL DO MILHO', '3D DESIGN GRAFICO', 'THALITA COMERCIAL', 'FJ', 'CLEAN SELECT', 'EMPLACADORA FLASH', 'PF AGROPECUARIA', 'REINO DAS RACOES', 'GLOBAL UTILIDADES', 'FLORA PAI CIPRIANO', 'RJ SERRALHERIA', 'RUBY CHEN', 'AGROPECUARIA DO GALO', 'GLJ SOLUCOES EM EMBALAGENS', 'RACOES DO GILSON', 'WWPRESENTES E UTILIDADES', 'EMBELLEZE CAR', 'APROF SAUDE E BELEZA', 'ECOLIMPE', 'FANNY FESTAS', 'HIPER FESTA', 'CONECTE EASY PRODUTOS E SERVICOS', 'PADRAO TEC', 'CONTAINER NATAL', 'I P PRODUTOS DE LIMPEZA', 'SOSOPRO', 'K3J EMBALAGENS', 'BIG PET STM', 'MMG-SOLUTIONS', 'CARVAO BRASA DE OURO', 'GESTO DE AMOR E FE', 'GARGAMEL DISTRIBUIDORA', 'SHOP PET COMERCIO', 'MARTAN JOIAS', 'ESODARTE ARTIGOS RELIGIOSOS', 'LISARB IMPORTS', 'HAL COMERCIO E SERVICOS AGROPECUARIOS', 'REPRODUZO', 'FLORICULTURA SUZANA', 'SOPRAMIM JOIAS', 'CUNHA DA CRUZ LOGISTIX', 'PEG&PET VILA SAO JOSE', 'URBHANA JOIAS', 'KIKI BRINDES', 'MERCADINHO MOURA', 'DG-AGRO EQUIPAMENTOS E ACESSORIOS', 'GUARA ARMAS', 'AGROPET ARMAZEM DOS BICHOS', 'METHAMORFOSE', 'BALANCAS SATELITE DA AMAZONIA', 'CRISTAL AZUL', 'C.S.T. NUTRICAO ANIMAL', 'MIRITZ COMERCIAL AGRICOLA', 'CUBO COMERCIO E REPRESENTACAO', 'REDE POP PET CENTER NOVO REPARTIMENTO', 'CASA DAS PISCINAS', 'RACOES FREIRE', 'NAJA EXTINTORES', 'CENTRO DAS RACOES', 'EXPET EXPRESS', 'BOB RACOES', 'LAGOA QUIMICA PRODUTOS DE LIMPEZA', 'MURO ALTO PISCINAS LTDA', 'JK SACOLAS', 'PAULINIA EMPLACAMENTO MERCOSUL', 'STEGCOAST', 'NICK SEMIJOIAS', 'TOP CLEAN COMERCIO', 'BFG CORPORATE', 'LFSTORE', 'CARVAO OURO VERDE', 'APLIQUES BELLE', 'PAGUE MENOS', 'AGROMAX', 'TENDAS BR', 'POINT ANIMAL AGROPET', 'SASSA FITA', 'QUERO FLO', 'CLINPET', 'FERCOR SOLUCOES EM MANUTENCAO E COMERCIO DE PECAS', 'GRUPO FELIPE', 'SERCOMM', 'HABITAT PET STORE LTDA', 'FENIX COMERCIO DE GASES LTDA', 'ARMADURA DO CRISTAO - ARTIGOS RELIGIOSOS E CAFETERIA', 'FIO DOURADO SEMIJOIAS', 'BG RACOES ANIMAIS', 'LEAL VET SHOP', 'CASA DE RACAO VITORIA GRAOS', 'CAPITAL ACAI', 'COMIDAS PARA PLANTAS', 'FENGYU WU', 'FACICLEAN MATERIAIS DE LIMPEZA LTDA', 'WL MATERIAL DE LIMPEZA', 'VORTEX SHOP', 'ZIPER SOLUCOES PLASTICAS', 'TRINCO', 'LOVE STORY SEXY', 'CELEIRO DE VARGEM GRANDE', 'SASA PERSONALIZADOS', 'PETS HOUSE', 'JL BIJU', 'YURI JOIAS', 'SACARIA NUTRICAO ANIMAL', 'KKSB COMERCIO', 'AGROBEL VINHEDO CAPELA', 'INOVA COMERCIAL', 'WILD ORNAMENTAL FISH BRAZIL', 'RBP JUAZEIRO', 'OPEN JOIAS', 'LIMPA BEEM', 'HAPPY PETS', 'COCCINELLA ACESSORIOS', 'TRINITY', 'REVITALIZA COMERCIO', 'NR COMERCIO DE BEBIDAS E EMBALAGENS', 'MUNDO FERA', 'CASA DO FAZENDEIRO AGROPECUARIA E PET SHOP', 'DOM RURAL', 'GRIFFE DO PET', 'O REINO DOS PETS', 'ART COCO', 'COMERCIAL ALVES DE OLIVEIRA', 'PRATICO MIX', 'SORELLY', 'BICHO AMIGO', 'AGAPE SERVICO ADMINISTRATIVOS', 'SHC VENTURES', 'P0LIMIX USINADOS & C0NCRETEIRA', 'ARTESANO GALERIA', 'HANNAH PET STORE', 'ALL PETS', 'LFP DISTRIBUICAO E SERVICOS', 'A PETS DO BAIRRO', 'SANTOS CALHAS E COBERTURAS', 'BICHO MANIA', 'GALERIA DE ARTE FERNANDO SILVEIRA', 'HIPERCRIA', 'COMERCIO DIGITAL VAM', 'FECKER ACESSORIOS', 'JM FERRAGENS E UTILIDADES DOMESTICAS', 'PET MINAS', 'BIXO MIMO', 'NEW CONSIGNA', 'CASA DO AMIGAO', 'XAVIER DOCES DE ALGAROBA ARTES CRIATIVAS', 'POINTIE SEX', 'SANCHEZ SUPERMERCADO DA LIMPEZA', 'TUDO AGRO', 'CIVETTA TATTOO SUPPLY', 'AGROPECUARIA CORREIA', 'PRO LIMPO', '777 VAREJO DIGITAL', 'PEROLA BUJU', 'SUMMER FLOWER', 'DR8 PRODUTOS EQUESTRES', 'DIGINORTH', 'DO EXTREMA', 'SOLARTE', 'PURO LUXO', 'A MAGIA DA LEMBRANCA', 'UAI CASA DO MINEIRO', 'SAO MIGUEL AGROPECUARIA', 'DISTRIBUIDORA DE RACAO E SERVICOS PET STORE', 'ART BRILHO II', 'LOVE BIJU E ACESSORIOS', 'FERRO NEWS COMERCIO DE FERRO', 'NANDA PRATAS', 'AGRO VETERINARIA SAO FRANCISCO', 'ANGEL BIJUTERIAS E ACESSORIOS', 'KAIROS DISTRIBUIDORA', 'GERALDO ARTESANATOS', 'ESTRELA BRANCA AGROPECUARIA', 'L T L LOJA DE RACAO CACA E PESCA', 'AGROPET RAIZES', 'D VITRINE SEMIJOIAS E PRATAS', 'ALLEF IMPORTS', 'FULL COMERCIO E LOGISTICA LTDA', 'LILIKA RACOES LTDA', 'BALNEARIO SOLUCOES EM HIGIENE', 'COMERCIAL SUPERCHAMAS', 'SHA-DY ACESSORIOS', 'GJ BRINDES', 'EVYLIM STAR COMERCIAL', 'RIBEIRO E SILVA', 'ALEM DA FESTA', 'SYMBIOSIS DISTRIBUIDORA', 'MUNDO DOS BIXOS', 'J. OLIVEIRA ASSESSORIA E COMUNICACAO', "BRIGHT N'SHINE PET DENTAL", 'ONEVALENTE', 'CARVAO BRASIL JL LTDA', 'PLANETA BIJU', 'EMERGE NEGOCIOS DIGITAIS', 'SEJA DOCE BALOES', 'SAT TELECOMUNICACOES', 'DOMINOS RACOES', 'PET SHOP MIMOS & AMOR', 'PRINT+ IMPRESSOES E PRESENTES', 'MARINA LUZZI CO.', 'AGROSUL', 'YONNY FLORICULTURA', 'ALPHA EMBALAGENS CENTRO LTDA', 'ATALAIA RURAL', 'CRISALIS GARDEM', 'EMBOX EMBALAGENS', 'MHP FLORES', 'PARCHEM BRASIL', 'APPUCOM COMERCIO EM GERAIS', 'FERNANDES AGRO SEEDS', 'RECONTO', 'MEGA FEST', 'GP DIGITAL', 'SHE JOIAS BY AMANDA MANEIRA', 'INOVAA CRIATIVE', 'PATIO BARROS REIS', 'SANAREPRO', 'NH PRIME ARMAS', 'MONTIBELLER EXTINTORES', 'SOL RED ENERGIA SOLAR', 'ROZINEA FILIAL', 'GREEN SKY HYDROPONIC', 'AGRO GERAIS', 'CAMINHO PET', 'FUNERARIA E EMPREENDIMENTO NEW LIFE', 'LIMPMUNDIAL', "HOUSE D'APAZ", 'WP IMPORTS LTDA', 'PETS HOME', 'BAZZANI MUDAS COMERCIO DE FLORES E PLANTAS', 'MAIS ARQUITETURA LEM', 'DONA MANU', 'CAO & MIA PET CARE', 'ELIAS BARRETO & CIA', 'BOA VISTA UTILIDADES', 'AGROPET MANDACARU', 'LAURA AGRO PET', 'LOJA LIMPADELA', 'JOI ACESSORIOS', 'OLIMP HIGIENIZACAO', 'LUX MUNDI ATELIE', 'INNOVAFACIL', 'TONS DE LI', 'UNIK IMPRESSAO 3D & UNIVERSO GEEK', 'LICITY OSASCO COMERCIO', 'CHACARA ECOLOGICA', 'KEK COMERCIO E SERVICOS', 'LB DISTRIBUIDORA DE EMBALAGENS E PRODUTOS DE LIMPEZA', 'FINNA FLOR', 'NEKO COMERCIO VAREJISTA', 'GROU PET SHOP', 'PETSHOP AVENIDA', 'MAREAR NEGOCIOS', 'MT COMERCIO', 'AGROPECUARIA AMIZADE', 'AGRO RURAL', 'BANCA NOBRE', 'MP AGRO MAIS - PRODUTOS AGROPECUARIOS E VARIEDADES', 'RC FESTA', 'MUNDO DA RACAO', 'L P ARMAS', 'PROSPERITY 88', 'J DIAS', 'JARDIM DA ARICELI FLORICULTURA E PAISAGISMO', 'DROPLY', 'NOVA AME', 'AGRO E PETS DEUS CONOSCO', 'RIBEIRO & DOYLE', 'ROGISEG', 'YAN BIJUTERIAS', 'ECOVILLE BARREIRAS', 'YIJIADUO COMERCIAL IMPORTACAO 

In [ ]:
produtos_pet = []

for path in dados_estab:
    df = pd.read_parquet(path)

    filtros = ((df['cnae_fiscal_principal'] != '4789004') & (df['cnae_fiscal_secundaria'].str.contains('4789004', na = False)) & (df['situacao_cadastral'] == '02'))

    df_filtrado = df[filtros]

    if not df_filtrado.empty:
        produtos_pet.append(df_filtrado)

    del df
    gc.collect()
    
produtos_pet

[       cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 1770      02377464       0001      47                           1
 3558      00760957       0001      36                           1
 3687      04949905       0004      06                           2
 4255      00762823       0001      54                           1
 5607      05054671       0008      25                           2
 ...            ...        ...     ...                         ...
 495884    01581122       0001      81                           1
 497889    07193429       0001      91                           1
 498057    23592967       0001      05                           1
 498286    03227962       0001      76                           1
 498915    01586154       0001      70                           1

                                nome_fantasia situacao_cadastral  \
 1770                                    None                 02
 3558                     COMERCIAL BOM PRECO                 02
 3687                       SHOPPING DA SAUDE                 02
 4255                    AGROPECUARIA INDIARA                 02
 5607                     MAGAZAN CASTANHEIRA                 02
 ...                                      ...                ...
 495884                           AGRO MOINHO                 02
 497889                                  None                 02
 498057  POLICLINICA VETERINARIA DE FORTALEZA                 02
 498286       ANIMAIS, VETERINARIA E PET SHOP                 02
 498915                                  None                 02

        data_situacao_cadastral motivo_situacao_cadastral nome_cidade_exterior  \
 1770                  20051103                        00                 None
 3558                  20250207                        00                 None
 3687                  20050108                        00                 None
 4255                  20030607                        00                 None
 5607                  20051103                        00                 None
 ...                        ...                       ...                  ...
 495884                20001223                        00                 None
 497889                20050126                        00                 None
 498057                20051103                        00                 None
 498286                20051022                        00                 None
 498915                20001223                        00                 None

         pais  ... municipio ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax  \
 1770    None  ...      5231  None       None  None       None    None
 3558    None  ...      3781    75   32812029  None       None    None
 3687    None  ...      0415    91   32021344    91   32021313      91
 4255    None  ...      9681    64   35471215  None       None    None
 5607    None  ...      0427   091    2504150  None       None     091
 ...      ...  ...       ...   ...        ...   ...        ...     ...
 495884  None  ...      8167  None       None  None       None    None
 497889  None  ...      6789  None       None  None       None    None
 498057  None  ...      1389    85   32244315    85   30886664    None
 498286  None  ...      4111    32   33333968  None       None    None
 498915  None  ...      6899  None       None  None       None    None

              fax                       correio_eletronico situacao_especial  \
 1770        None                                     None              None
 3558        None                      cirson@terra.com.br              None
 3687    32021344  FINANCEIRO@SHOPPINGDASAUDEONLINE.COM.BR              None
 4255        None                                     None              None
 5607     2504192                                     None              None
 ...          ...                                      ...               ...
 495884      None                                     None              None
 497889      None                                     None              None
 498057      None     POLICLINICAVETERINARIA2015@GMAIL.COM              None
 498286      None                                     None              None
 498915      None                                     None              None

        data_situacao_especial
 1770                     None
 3558                     None
 3687                     None
 4255                     None
 5607                     None
 ...                       ...
 495884                   None
 497889                   None
 498057                   None
 498286                   None
 498915                   None

 [416 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 177       42032468       0001      08                           1
 336       42034202       0001      02                           1
 532       42036331       0001      21                           1
 845       42039674       0001      40                           1
 915       42040425       0001      74                           1
 ...            ...        ...     ...                         ...
 498962    46615700       0001      91                           1
 499222    45027395       0053      85                           2
 499277    46619307       0001      76                           1
 499423    24751355       0004      23                           2
 499664    46619943       0001      06                           1

                nome_fantasia situacao_cadastral data_situacao_cadastral  \
 177     USINA DE SAUDE JR.AC                 02                20210520
 336                     None                 02                20210521
 532                 BELLAVET                 02                20210521
 845                     None                 02                20210521
 915           036.934.556-86                 02                20210521
 ...                      ...                ...                     ...
 498962                  None                 02                20220601
 499222                  None                 02                20220601
 499277                  None                 02                20220601
 499423   AGROPECUARIA SOARDI                 02                20220601
 499664                  None                 02                20220601

        motivo_situacao_cadastral nome_cidade_exterior  pais  ... municipio  \
 177                           00                 None  None  ...      0643
 336                           00                 None  None  ...      6449
 532                           00                 None  None  ...      5427
 845                           00                 None  None  ...      7099
 915                           00                 None  None  ...      4123
 ...                          ...                  ...   ...  ...       ...
 498962                        00                 None  None  ...      3067
 499222                        00                 None  None  ...      7107
 499277                        00                 None   105  ...      8877
 499423                        00                 None  None  ...      6409
 499664                        00                 None  None  ...      0447

        ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax   fax  \
 177       68   92252367    68   99867469    None  None
 336       17   91281093  None       None    None  None
 532       31   38924721  None       None    None  None
 845       12   39293361  None       None    None  None
 915       31   34525941  None       None    None  None
 ...      ...        ...   ...        ...     ...   ...
 498962    11   64185875  None       None    None  None
 499222    11   56739656  None       None    None  None
 499277    51   96680228  0000   00000000    None  None
 499423    43   35691366  None       None    None  None
 499664    91   83525151  None       None    None  None

                          correio_eletronico situacao_especial  \
 177                JBRUSINA.SAUDE@GMAIL.COM              None
 336                     SARTORI2007@MSN.COM              None
 532                  CONTABYSILVA@GMAIL.COM              None
 845     CONTATO_MRCONTABILIDADE@HOTMAIL.COM              None
 915            LEGALIZACAO@CONTACTAR.NET.BR              None
 ...                                     ...               ...
 498962           DIANA.HEITOR8811@GMAIL.COM              None
 499222                    LEGAL@SOUDAKI.COM              None
 499277               COSASCONTATO@GMAIL.COM              None
 499423               ARQUIVOPLAZA@GMAIL.COM              None
 499664                 NEYELTON81@GMAIL.COM              None

        data_situacao_especial
 177                      None
 336                      None
 532                      None
 845                      None
 915                      None
 ...                       ...
 498962                   None
 499222                   None
 499277                   None
 499423                   None
 499664                   None

 [2461 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 276       46630765       0001      06                           1
 663       46635228       0001      59                           1
 910       46638017       0001      70                           1
 1175      46640962       0001      06                           1
 1378      46643248       0001      71                           1
 ...            ...        ...     ...                         ...
 499352    52157669       0001      95                           1
 499586    52160182       0001      61                           1
 499614    17238092       0003      07                           2
 499792    52162357       0001      70                           1
 499842    52162897       0001      53                           1

                          nome_fantasia situacao_cadastral  \
 276                               None                 02
 663                               None                 02
 910                               None                 02
 1175                              None                 02
 1378    NOVA MODA FEMININA E MASCULINA                 02
 ...                                ...                ...
 499352                            None                 02
 499586                            None                 02
 499614                  CASA DOS FRIOS                 02
 499792           CONTATO CASA & JARDIM                 02
 499842         MARQUINHOS SUPERMERCADO                 02

        data_situacao_cadastral motivo_situacao_cadastral nome_cidade_exterior  \
 276                   20251204                        00                 None
 663                   20220602                        00                 None
 910                   20220602                        00                 None
 1175                  20220602                        00                 None
 1378                  20220602                        00                 None
 ...                        ...                       ...                  ...
 499352                20230912                        00                 None
 499586                20230913                        00                 None
 499614                20230913                        00                 None
 499792                20230913                        00                 None
 499842                20230913                        00                 None

         pais  ... municipio ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax   fax  \
 276     None  ...      6001    21   31584598  None       None    None  None
 663      105  ...      8635    51   37332569  0000   00000000    None  None
 910      105  ...      9051    67   30479001  0000   00000000    None  None
 1175    None  ...      6969    16   82022821  None       None    None  None
 1378    None  ...      5833    21   65641854  None       None    None  None
 ...      ...  ...       ...   ...        ...   ...        ...     ...   ...
 499352  None  ...      5629    27   98617733  None       None    None  None
 499586  None  ...      7425    43   96630368  None       None    None  None
 499614  None  ...      0255    95   81203469  None       None    None  None
 499792  None  ...      6979    19   96289625  None       None    None  None
 499842  None  ...      4645    33   88687671    33   99989045    None  None

                       correio_eletronico situacao_especial  \
 276               TRESPONTES22@GMAIL.COM              None
 663            BATISTAECUNHA@OUTLOOK.COM              None
 910       KONTINENTAL@KONTINENTAL.COM.BR              None
 1175      ALCHAARBATISTARAFAEL@GMAIL.COM              None
 1378     COMERCIALIMPERIOMODAS@GMAIL.COM              None
 ...                                  ...               ...
 499352        TATIANELOOSE1985@GMAIL.COM              None
 499586   FARMACIA_ESSENCIANF@HOTMAIL.COM              None
 499614  ASSESSORIACONTABILMS@HOTMAIL.COM              None
 499792    EXCELLENCESCONTABEIS@GMAIL.COM              None
 499842     WALTERXAVIERLIMA@YAHOO.COM.BR              None

        data_situacao_especial
 276                      None
 663                      None
 910                      None
 1175                     None
 1378                     None
 ...                       ...
 499352                   None
 499586                   None
 499614                   None
 499792                   None
 499842                   None

 [2349 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 67        52165368       0001      03                           1
 261       52167512       0001      40                           1
 704       52172401       0001      22                           1
 1103      50780165       0001      00                           1
 1460      31497441       0002      55                           2
 ...            ...        ...     ...                         ...
 499415    57746561       0001      51                           1
 499564    57748182       0001      09                           1
 499897    57751829       0001      43                           1
 499900    57751862       0001      73                           1
 499965    57752569       0001      20                           1

                                             nome_fantasia situacao_cadastral  \
 67                                                   None                 02
 261                                                  None                 02
 704                                                  None                 02
 1103                                     PET PARK PETSHOP                 02
 1460                                         CASA DA ROCA                 02
 ...                                                   ...                ...
 499415  TICO FERRAGENS FERRAMENTAS E MATERIAL DE IRRIG...                 02
 499564                                               None                 02
 499897                         AGROPECUARIA CLAUDIO MARIN                 02
 499900                                               None                 02
 499965                                 TRIBO DO BANHO PET                 02

        data_situacao_cadastral motivo_situacao_cadastral nome_cidade_exterior  \
 67                    20230913                        00                 None
 261                   20230913                        00                 None
 704                   20230913                        00                 None
 1103                  20230523                        00                 None
 1460                  20230914                        00                 None
 ...                        ...                       ...                  ...
 499415                20241018                        00                 None
 499564                20241018                        00                 None
 499897                20241018                        00                 None
 499900                20241018                        00                 None
 499965                20241018                        00                 None

         pais  ... municipio ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax   fax  \
 67      None  ...      0674    32   98066819  None       None    None  None
 261     None  ...      4835    33   91123439  None       None    None  None
 704     None  ...      6477    11   82602591  None       None    None  None
 1103     105  ...      7535    41   99186889  0000   00000000    None  None
 1460    None  ...      0251    97   84008394  None       None    None  None
 ...      ...  ...       ...   ...        ...   ...        ...     ...   ...
 499415   105  ...      3341    75   92051520  0000   00000000    None  None
 499564  None  ...      8081    92   86043580  None       None    None  None
 499897  None  ...      8183    49   32224390  None       None    None  None
 499900  None  ...      8589    51   94253593  None       None    None  None
 499965  None  ...      7107    11   12961610    11   64191817    None  None

                            correio_eletronico situacao_especial  \
 67                   JESUSAOLIV2020@GMAIL.COM              None
 261                 DIOVANIAROBERTA@GMAIL.COM              None
 704         JESSICACAROLINEFERREIRA@GMAIL.COM              None
 1103               GUILHERMEFURMAN@ICLOUD.COM              None
 1460                FABRYCIOMOTTO80@GMAIL.COM              None
 ...                                       ...               ...
 499415             TICOMATCONSTRU@HOTMAIL.COM              None
 499564              RAFANEGRITO1997@GMAIL.COM              None
 499897                     MARIN@MARIN.COM.BR              None
 499900  CONTATO@FACILITEICONTABILIDADE.COM.BR              None
 499965              TRIBODOBANHOPET@GMAIL.COM              None

        data_situacao_especial
 67                       None
 261                      None
 704                      None
 1103                     None
 1460                     None
 ...                       ...
 499415                   None
 499564                   None
 499897                   None
 499900                   None
 499965                   None

 [2293 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 18        57753145       0001      80                           1
 725       57761271       0001      87                           1
 921       57763498       0001      61                           1
 1064      57765012       0001      24                           1
 1098      57765375       0001      60                           1
 ...            ...        ...     ...                         ...
 499553    62712250       0001      01                           1
 499702    62713742       0001      11                           1
 499843    62715311       0001      94                           1
 499846    62715343       0001      90                           1
 499962    62716610       0001      43                           1

                        nome_fantasia situacao_cadastral  \
 18                              None                 02
 725                             None                 02
 921                             None                 02
 1064                     MH COMERCIO                 02
 1098                            None                 02
 ...                              ...                ...
 499553                          None                 02
 499702  TROPE DE COISA VENDAS ONLINE                 02
 499843             LC AGROFERRAGISTA                 02
 499846                    LUMI BELLE                 02
 499962                          None                 02


In [ ]:
leads_pet = pd.concat(produtos_pet, ignore_index = True)

leads_pet

,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,nome_fantasia,situacao_cadastral,data_situacao_cadastral,motivo_situacao_cadastral,nome_cidade_exterior,pais,...,municipio,ddd_1,telefone_1,ddd_2,telefone_2,ddd_fax,fax,correio_eletronico,situacao_especial,data_situacao_especial
0,02377464,0001,47,1,None,02,20051103,00,None,None,...,5231,None,None,None,None,None,None,None,None,None
1,00760957,0001,36,1,COMERCIAL BOM PRECO,02,20250207,00,None,None,...,3781,75,32812029,None,None,None,None,cirson@terra.com.br,None,None
2,04949905,0004,06,2,SHOPPING DA SAUDE,02,20050108,00,None,None,...,0415,91,32021344,91,32021313,91,32021344,FINANCEIRO@SHOPPINGDASAUDEONLINE.COM.BR,None,None
3,00762823,0001,54,1,AGROPECUARIA INDIARA,02,20030607,00,None,None,...,9681,64,35471215,None,None,None,None,None,None,None
4,05054671,0008,25,2,MAGAZAN CASTANHEIRA,02,20051103,00,None,None,...,0427,091,2504150,None,None,091,2504192,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214923,04954077,0001,51,1,None,02,20030712,00,None,None,...,7107,11,38586033,None,None,None,None,CAREX@TERRA.COM.BR,None,None
214924,04955914,0001,67,1,ARTMANIA,02,20051103,00,None,None,...,9269,64,84151560,None,None,None,None,ARTMANIABJ@HOTMAIL.COM,None,None
214925,04956923,0001,72,1,None,02,20051103,00,None,None,...,8507,55,99327791,None,None,None,None,OBERDANSEVERO@UOL.COM.BR,None,None
214926,01666715,0001,40,1,COMERCIO E REPRESENTACOES BORTOLI,02,20031018,00,None,None,...,8771,51,5822850,None,None,None,None,None,None,None
214927,03317190,0001,63,1,AGROPECUARIA PAMPA,02,20051103,00,None,None,...,5755,49,36670055,None,None,None,None,donati@mhnet.com.br,None,None

In [ ]:
leads_pet[['cnae_fiscal_secundaria']]

                                   cnae_fiscal_secundaria
0                                 4744099,4763603,4789004
1         5611203,4623109,4744099,4722901,4754701,4789004
2       3312102,3312103,3312104,4642702,4644301,464430...
3                         4744001,4623109,4789004,4683400
4       4646001,4646002,4649408,4744099,4751201,475470...
...                                                   ...
214923  4530701,4530703,4635499,4639701,4642702,464949...
214924  1813001,2512800,2539001,3101200,3299004,412040...
214925  3314710,3314713,4530703,4732600,4741500,474230...
214926            4744001,4789004,4761003,4649408,4693100
214927  4744001,4789002,9609208,4623106,4789004,474409...

[214928 rows x 1 columns]

In [ ]:
leads_pet = leads_pet[['cnpj_basico', 'cnpj_ordem', 'cnpj_dv', 'nome_fantasia', 'bairro','ddd_1', 'telefone_1', 'ddd_2', 'telefone_2']]

leads_pet

,cnpj_basico,cnpj_ordem,cnpj_dv,nome_fantasia,bairro,ddd_1,telefone_1,ddd_2,telefone_2
0,02377464,0001,47,None,CENTRO,None,None,None,None
1,00760957,0001,36,COMERCIAL BOM PRECO,CENTRO,75,32812029,None,None
2,04949905,0004,06,SHOPPING DA SAUDE,CENTRO,91,32021344,91,32021313
3,00762823,0001,54,AGROPECUARIA INDIARA,SETOR ALTO DA PRIMAVERA,64,35471215,None,None
4,05054671,0008,25,MAGAZAN CASTANHEIRA,CASTANHEIRA,091,2504150,None,None
...,...,...,...,...,...,...,...,...,...
214923,04954077,0001,51,None,CASA VERDE,11,38586033,None,None
214924,04955914,0001,67,ARTMANIA,CENTRO,64,84151560,None,None
214925,04956923,0001,72,None,CANJIQUEIRA,55,99327791,None,None
214926,01666715,0001,40,COMERCIO E REPRESENTACOES BORTOLI,ROSELANDIA,51,5822850,None,None
214927,03317190,0001,63,AGROPECUARIA PAMPA,CENTRO,49,36670055,None,None

Modificando as colunas de cnpj e de ddd:

In [ ]:
leads_pet['cnpj'] = (leads_pet['cnpj_basico'].str.zfill(8).str[:2] + '.' + leads_pet['cnpj_basico'].str.zfill(8).str[2:5] + '.' + leads_pet['cnpj_basico'].str.zfill(8).str[5:8] + '/' + 
                      leads_pet['cnpj_ordem'].str.zfill(4) + '-' + leads_pet['cnpj_dv'].str.zfill(2))

leads_pet['cnpj']

C:\Users\mayma\AppData\Local\Temp\ipykernel_14648\2048251676.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  leads_pet['cnpj'] = (leads_pet['cnpj_basico'].str.zfill(8).str[:2] + '.' + leads_pet['cnpj_basico'].str.zfill(8).str[2:5] + '.' + leads_pet['cnpj_basico'].str.zfill(8).str[5:8] + '/' +

0         02.377.464/0001-47
1         00.760.957/0001-36
2         04.949.905/0004-06
3         00.762.823/0001-54
4         05.054.671/0008-25
                 ...
214923    04.954.077/0001-51
214924    04.955.914/0001-67
214925    04.956.923/0001-72
214926    01.666.715/0001-40
214927    03.317.190/0001-63
Name: cnpj, Length: 214928, dtype: object

In [ ]:
leads_pet['ddd_telefone_1'] = ('(' + leads_pet['ddd_1'] + ')' + ' ' + leads_pet['telefone_1'])

leads_pet['ddd_telefone_1']

C:\Users\mayma\AppData\Local\Temp\ipykernel_14648\148848511.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  leads_pet['ddd_telefone_1'] = ('(' + leads_pet['ddd_1'] + ')' + ' ' + leads_pet['telefone_1'])

0                   NaN
1         (75) 32812029
2         (91) 32021344
3         (64) 35471215
4         (091) 2504150
              ...
214923    (11) 38586033
214924    (64) 84151560
214925    (55) 99327791
214926     (51) 5822850
214927    (49) 36670055
Name: ddd_telefone_1, Length: 214928, dtype: object

In [ ]:
leads_pet['ddd_telefone_2'] = ('(' + leads_pet['ddd_2'] + ')' + ' ' + leads_pet['telefone_2'])

leads_pet['ddd_telefone_2']

C:\Users\mayma\AppData\Local\Temp\ipykernel_14648\1717649017.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  leads_pet['ddd_telefone_2'] = ('(' + leads_pet['ddd_2'] + ')' + ' ' + leads_pet['telefone_2'])

0                   NaN
1                   NaN
2         (91) 32021313
3                   NaN
4                   NaN
              ...
214923              NaN
214924              NaN
214925              NaN
214926              NaN
214927              NaN
Name: ddd_telefone_2, Length: 214928, dtype: object

In [ ]:
leads_pet = leads_pet[['cnpj', 'nome_fantasia', 'bairro', 'ddd_telefone_1', 'ddd_telefone_2']]

leads_pet

,cnpj,nome_fantasia,bairro,ddd_telefone_1,ddd_telefone_2
0,02.377.464/0001-47,None,CENTRO,NaN,NaN
1,00.760.957/0001-36,COMERCIAL BOM PRECO,CENTRO,(75) 32812029,NaN
2,04.949.905/0004-06,SHOPPING DA SAUDE,CENTRO,(91) 32021344,(91) 32021313
3,00.762.823/0001-54,AGROPECUARIA INDIARA,SETOR ALTO DA PRIMAVERA,(64) 35471215,NaN
4,05.054.671/0008-25,MAGAZAN CASTANHEIRA,CASTANHEIRA,(091) 2504150,NaN
...,...,...,...,...,...
214923,04.954.077/0001-51,None,CASA VERDE,(11) 38586033,NaN
214924,04.955.914/0001-67,ARTMANIA,CENTRO,(64) 84151560,NaN
214925,04.956.923/0001-72,None,CANJIQUEIRA,(55) 99327791,NaN
214926,01.666.715/0001-40,COMERCIO E REPRESENTACOES BORTOLI,ROSELANDIA,(51) 5822850,NaN
214927,03.317.190/0001-63,AGROPECUARIA PAMPA,CENTRO,(49) 36670055,NaN

In [ ]:
mascara1 = leads_pet[['ddd_telefone_1', 'ddd_telefone_2']].notna()

mascara = leads_pet[['ddd_telefone_1', 'ddd_telefone_2']][mascara1]

#mascara2 = leads_pet['ddd_telefone_1'].notna


mascara

       ddd_telefone_1 ddd_telefone_2
0                 NaN            NaN
1       (75) 32812029            NaN
2       (91) 32021344  (91) 32021313
3       (64) 35471215            NaN
4       (091) 2504150            NaN
...               ...            ...
214923  (11) 38586033            NaN
214924  (64) 84151560            NaN
214925  (55) 99327791            NaN
214926   (51) 5822850            NaN
214927  (49) 36670055            NaN

[214928 rows x 2 columns]

In [ ]:
leads_pet.to_parquet('leads_pet_secundario.parquet', index=False, engine='pyarrow', compression='snappy')

**3. Higienização para Discador Automático (Foco em Regex)**
O time de telemarketing da sua empresa está enfrentando problemas porque o sistema de discagem automática está travando. O motivo é que os números de telefone na base da Receita muitas vezes vêm com letras, espaços, traços ou símbolos bizarros.
* **Tarefa:** Pegue a base de Estabelecimentos e faça uma limpeza na coluna principal de telefones usando Expressões Regulares (Regex) para substituir **qualquer caractere que não seja um número** por um espaço vazio. Exiba no seu código as primeiras linhas da tabela antes e depois da limpeza para comprovar que restaram apenas dígitos numéricos, e exporte a base limpa como `telefones_higienizados.parquet`.

In [ ]:
contatos_ruins = []
contatos = []

for path in dados_estab:
    df = pd.read_parquet(path)
    colunas = ['ddd_1', 'telefone_1', 'ddd_2', 'telefone_2']
    verificador = df[colunas].apply(lambda x: x.str.contains(r'[^0-9]', na = False, regex = True))
    mascara = verificador.any(axis = 1)
    df_problemas = df[colunas][mascara]
    if not df_problemas.empty:
        contatos_ruins.append(df_problemas)
        for coluna in colunas:
            df_problemas[coluna] = df_problemas[coluna].str.replace(r'\D', '', regex = True)
        contatos.append(df_problemas)    
    del df
    del df_problemas
    gc.collect()

contatos_ruins

[       ddd_1 telefone_1 ddd_2 telefone_2
 47        66    4986445  None       None
 1677     083    2225141  None       None
 1679     083    2219292  None       None
 1681     083    2242356  None       None
 4124     011   61419415  None       None
 ...      ...        ...   ...        ...
 465895  0011    7396572  None       None
 467477    49    6770195  None       None
 476196  0532     651028  None       None
 481818    49    8640034  None       None
 488366   024    3521671  None       None

 [190 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 235976    27    3711131  None       None
 238811    21    2639457  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 326255   035    2121320  None       None
 326635  0532     213614  None       None
 327554  0011    2679657  None       None
 329736   035    4711102  None       None
 330255   063    8513441  None       None
 ...      ...        ...   ...        ...
 491936    75    4223728  None       None
 492775   067    2381765  None       None
 494412   083    2463181  None       None
 496243   021    2409838  None       None
 496264   021    2628808  None       None

 [131 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 90       021    2535469  None       None
 374      067    4451270  None       None
 1892     051    6341144  None       None
 1984     055    2321264  None       None
 3329     083    2922720  None       None
 ...      ...        ...   ...        ...
 483930    41    3383235  None       None
 486271   088    5311084  None       None
 486972   053    2710544  None       None
 491811   021    2248846  None       None
 497557   021    2425154  None       None

 [250 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 2826     016    6105600  None       None
 3026     086    4831430  None       None
 7158     021    5331183  None       None
 12393    044    2240570  None       None
 19299     49    3231097  None       None
 ...      ...        ...   ...        ...
 491273    48    6246164  None       None
 491866    21    8868569  None       None
 496375    18    2217542    18    2210244
 496505    54    5220090    54   91264211
 499902   067    7869513  None       None

 [90 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 271      021    2923939  None       None
 2202      74   35351231    74    3535084
 2518      51    4729248    51   30311444
 4543      11    2944785    11   67845296
 5105      61    3627346    61   36277138
 ...      ...        ...   ...        ...
 486868   085    2731731  None       None
 491639   067    3828065  None       None
 495565    94    4211519  None       None
 497242   021    2634433  None       None
 497316   083    2316904  None       None

 [198 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 32        14   97037342    14    9721386
 11460     85    3235302    85   96113631
 11551     43   35251033    43    3525113
 17428     13    3235669  None       None
 19902     18   33711491    18     977532
 19923     21    2446397    21   22693967
 25409     51    9652753  None       None
 27289     14   37651733    14    3765833
 28557     54    3232726  None       None
 35589     62     329113    62     328970
 37165     66    3531552    66   35316816
 40125     62    3337112  None       None
 42538     16   37271424    16    3727181
 44250     35     382177  None       None
 47334     11    4428600  None       None
 51335     21   24645247    21    3017532
 54804     68    8408461  None       None
 55130     41    3322848    41   30131475
 55641     14   37141182    14    3714119
 56450     91   96247339    91    3449136
 75202     16    3402718  None       None
 198395    30    2503093  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 32346     88    3611453  None       None
 129032    12          0  None       None
 129656    19    7716040  None       None
 144735    22          0  None       None
 165807    14          0  None       None
 165837    67          0  None       None
 166893    19          0  None       None
 166968    34    5313540  None       None
 167831    83          0  None       None
 168002    88    1314670  None       None
 168497    21          0  None       None
 169806    74    6534410  None       None
 169927    94          0  None       None
 170716    91          0  None       None
 171161    91    2106820  None       None
 171290    88          0  None       None
 175001    84          0  None       None
 175113    99          0  None       None
 175137    31          0  None       None
 175393    87          0  None       None
 175419    77          0  None       None
 175976    31          0  None       None
 176217    98      12060  None       None
 176908    32    3519640  None       None
 176978    62          0  None       None
 176986    31          0  None       None
 179636    13          0  None       None
 183414    74          0  None       None
 334661    91    2244642  None       None
 371784    85          0  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 1293    0532     721717  None       None
 2338      55    4123601  None       None
 7962    0031    4821700  None       None
 7996     071    9714708  None       None
 9157      54    2135000  None       None
 ...      ...        ...   ...        ...
 482442    47    3362445  None       None
 485974    41    2735535  None       None
 495049    51    3625318  None       None
 495939   021    2209535  None       None
 498185    51   37142204    51    3714220

 [126 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 50454     11    2671741  None       None
 50467     16    3945199  None       None
 50744     19    3561154  None       None
 51465     21    3275599  None       None
 51477     19    5276046  None       None
 51544     24    2482994  None       None
 51602     22    2624091  None       None
 51637     21    2756171  None       None
 51659     21    2290901  None       None
 60757     21    2225155  None       None
 67899     21    3474546  None       None
 131577    62   32255728  None    5562322
 138573    16   32627192  None      16326
 205220                   None       None
 232504    18   32696275  None    1920000
 247839                   None       None
 437351    51    3656357  None       None
 447607    38    3725120  None       None
 451816    31    3642388  None       None
 452014    31    3641468  None       None
 452046    16    3146111  None       None
 452682    28    3552619  None       None
 452869    38    3723112  None       None
 452973    13    3386442  None       None
 453069    33    3277285  None       None
 455614    86    3323827  None       None
 455756    33    3225261  None       None
 455818    22    2793366  None       None
 459961    24    3320589  None       None
 460281    19    3225614  None       None
 461035    54    3211380  None       None
 467756    16    3415031  None       None
 467803    19    3821111  None       None
 468695    31    3718128  None       None
 468778    85    3371238  None       None
 468893    19    3327324  None       None
 468958    16    3627338  None       None
 469139    62    3281773  None       None
 469246    81    9859230  None       None
 471284    47    3372347  None       None
 472381    75    3224106  None       None
 478596    11    2331369  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 52848     98    3461130  None       None
 53771     27    3269145  None       None
 87123     47          0  None       None
 94837     14    3434046  None       None
 96661     49    3444030  None       None
 ...      ...        ...   ...        ...
 256601    14    3478153  None       None
 256602    67    3541170  None       None
 256611    18    3622393  None       None
 256616    31    3033297  None       None
 460562    33    3251201  None       None

 [86 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 56824     21    2659213  None       None
 325238    21    7583561  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 225600    61   93187548    61   81489415
 248143    61   81273492  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 410690    27    2292743  None       None
 412195  0243     711155  None       None
 413172    71    3773864  None       None
 417870  0243     650690  None       None
 417896  0243     654163  None       None
 ...      ...        ...   ...        ...
 494380    49    3235275  None       None
 495196   067    7510120  None       None
 496474   067    3833401  None       None
 497876  0243     711404  None       None
 499095  0243     422317  None       None

 [70 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 1751     021    5323757  None       None
 2062     067    7632170  None       None
 2248     067    3868791  None       None
 4625     079    9822232  None       None
 8986     067    3861947  None       None
 ...      ...        ...   ...        ...
 484315   032    7223425  None       None
 485259    47    3437032    47   30255568
 486900   071    3770848  None       None
 494259  0083    2226970  None       None
 498065    71    2593632  None       None

 [337 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 3815    0243     650699  None       None
 4612     071    6351166  None       None
 11421     61    3524203  None       None
 14439     62    4310809  None       None
 15810    021    5715283  None       None
 ...      ...        ...   ...        ...
 463640    16   33752332    17    3342711
 464982    81   32690871    81    3269087
 465317    21   26031533    21    2603176
 470089    37    2241123  None       None
 474491    62          0  None       None

 [159 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 786       71    3062059  None       None
 5521     011    4411827  None       None
 8320    0132     302858  None       None
 9705     021    2973922  None       None
 13944   0729       5470  None       None
 ...      ...        ...   ...        ...
 464905   051    5441149  None       None
 469073    16    6244344  None       None
 474469   021    2629536  None       None
 485382   021    2620887  None       None
 498015    65    3322055    65   33220551

 [105 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 5246    0319    9544869  None       None
 10787    067    7616530  None       None
 12894     54    3921070  None       None
 17194    021    2325180  None       None
 26290    021    2208004  None       None
 ...      ...        ...   ...        ...
 471252    61    2483015  None       None
 472838    47    3511312    47    3351131
 479469   083    2482004  None       None
 480017   021    2622440  None       None
 481769    85    2523644  None       None

 [169 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 1823     083    2219724  None       None
 7555     083    2251910  None       None
 35074    088    8311138  None       None
 37546     86    0000000  None       None
 45553   0083    2224193  None       None
 54461    063    8411255  None       None
 60277   None       3621  1535       None
 62653    067    7871286  None       None
 65563    011   69573377  None       None
 67690    067    3824265  None       None
 78984     51    3598232    51   35984676
 81553    021    2207576  None       None
 83850   6714    7861556  None       None
 86915     31   99828077    31    2242030
 87163     65    3692212  None       None
 88412     17   36991194    17    3699716
 89496     85    3235302    85   32333743
 89647     49   95460998    49    3546099
 90531     11    3062315  None       None
 95639     84    9963020    84   99630208
 96056     75    3221460  None       None
 99241     21    2658555    21   87386444
 103396    73    3617713    73   36177133
 108144    17   35224269    17    9141076
 113123    61    3572898  None       None
 113261    75    3251182  None       None
 113722    61    3345118  None       None
 123280    99    8801542  None       None
 124542    45    3222638  None       None
 134853    51    3334497  None       None
 138109    27   40094657    27    4009465
 141873    16   36645621    16    9996823
 144601    53    9982675  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 121269    61    3612309    61   36121718
 124523    62    3558515  None       None
 127585    17    3525337  None       None
 180639    21   22553267    21    2255326
 231163    27          0  None       None
 249528    11          0  None       None
 252086    11          0  None       None
 252209    77          0  None       None
 254335    11          0  None       None
 254894    33    6314260  None       None
 256189    54      21290  None       None
 257153    79    9937900  None       None
 258097    98          0  None       None
 258117    38          0  None       None
 258385    65          0  None       None
 259164    63    3369410  None       None
 261304    11          0  None       None
 261446    22          0  None       None
 261563    13          0  None       None
 261610    11          0  None       None
 261655    62          0  None       None
 261695    37          0  None       None
 262665    94          0  None       None
 262770    46    1475030  None       None
 263213    96          0  None       None
 263218    62          0  None       None
 263263    32    8413060  None       None
 263319    38          0  None       None
 264139    33    3521230  None       None
 266234    12          0  None       None
 272562    68      11050  None       None
 273905    79          0  None       None
 284457    17   33614762    17    3361158
 458264    71          0  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 136847    12    3307289  None       None
 136872    11    4198550  None       None
 136884    11    3603477  None       None
 136896    16    3342338  None       None
 137423    87    3862226  None       None
 137743    21    3404707  None       None
 138025    21    2290397  None       None
 138030    21    2475135  None       None
 138044    21    2796317  None       None
 138054    21    3703794  None       None
 138061    21    2232368  None       None
 143133    21    3292312  None       None
 162020    21    2697029  None       None
 171370    99   36631192    99      99366
 217213    64   35472116  None    5564354
 219403    83    3337172  None       None
 258294    21   39073713    21    5521365
 287552                   None       None
 291843                   None       None
 294750    44   99022073  None    5544990
 304902    14   37623941  None    1874000
 318847                   None       None
 327881                   None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 33060     54    3822281  None       None
 33158     38    3725132  None       None
 33373     87    3822290  None       None
 33752     14    3417396  None       None
 36681     21    2693062  None       None
 ...      ...        ...   ...        ...
 279255    33    3271572  None       None
 279314    71    3266114  None       None
 279385    19    3884410  None       None
 342975    64    3404139  None       None
 343011    11    4576230  None       None

 [103 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 411611    85    3294305  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 180286    21    2201827  None       None
 236142    21    2281233  None       None
 317201    21    3596295  None       None
 384364                   None       None
 449135    18   32832681    18    3283268,
        ddd_1 telefone_1 ddd_2 telefone_2
 172637    31   93165042             None,
        ddd_1 telefone_1 ddd_2 telefone_2
 499188  0243     623227  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 128       55     323810  None       None
 527     0352    2821245  None       None
 724      083    2355636  None       None
 3611     027    7631194  None       None
 4714     011    9164844  None       None
 ...      ...        ...   ...        ...
 486749    51    3383488  None       None
 487051   067    7212721  None       None
 493832   017    5226580  None       None
 494399   019    4220088  None       None
 495304   016    6901300  None       None

 [340 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 2926    0243     651359  None       None
 3731     067    6811041  None       None
 3964      91    4681568  None       None
 4344      41    2726851  None       None
 8059     015    2333938  None       None
 ...      ...        ...   ...        ...
 453448   021    5951818  None       None
 462467    48   32451245    48    3245108
 471357   011    6912378  None       None
 476375   011   69449900  None       None
 492328   021    5322766  None       None

 [108 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 6954     021    2058828  None       None
 11646    011   61010101  None       None
 12032    021    2424374  None       None
 23260     53    2611911  None       None
 23557    021    2334148  None       None
 ...      ...        ...   ...        ...
 480599    64    3657147  None       None
 480819    84    3223704    84   32237042
 491077   091    2505000  None       None
 493085   021    2213242  None       None
 498479    47    3533137    47   35333099

 [150 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 1249      44    3267774  None       None
 1323      47    3322263  None       None
 5609     035    2652752  None       None
 6332      24    3542018  None       None
 7094     047    4263757  None       None
 ...      ...        ...   ...        ...
 228438    51   35973566    51    3598282
 228774    48    8802142  None       None
 228895    83          0  None       None
 229113    49    3652757  None       None
 259378    65     354387    65   33549700

 [88 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 43407     41   33290475    41    3329047
 120746    21    3486340  None       None
 205871    22    0000000  None       None
 209650    08   32126820    83    3212682
 210597    21    2620344  None       None
 338552    11          0  None       None
 338572    11    4048940  None       None
 339691    37    1411380  None       None
 342525    91     412180  None       None
 342599    85          0  None       None
 342616    21          0  None       None
 342627    11          0  None       None
 342674    91    2548820  None       None
 342752    67          0  None       None
 343967    64    9258330  None       None
 343977    27          0  None       None
 345637    81          0  None       None
 346304    99    9988240  None       None
 346413    96          0  None       None
 346460    54      36150  None       None
 347085    42    3448930  None       None
 347272    85    5923890  None       None
 348274    99    5182670  None       None
 348806    65          0  None       None
 349149    91          0  None       None
 349773    62          0  None       None
 430031    86    3120040  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 5537      51    3595330    51    3595330
 5857      11    5533688    11   99890248
 6700      19   32276808    19    3227680
 45103     87          0  None       None
 45272     86          0  None       None
 150578                   None       None
 223281    11    2378131  None       None
 223327    11    2068608  None       None
 223589    17    3013470  None       None
 223950    11    5677315  None       None
 224306    21    3316080  None       None
 224377    21    2450044  None       None
 224380    21    3272496  None       None
 224458    24    2485311  None       None
 225789    24    2242429  None       None
 305753    12    3888400  None       None
 345360    51   81014254  None    5551810
 376881    15   35323710  None    1846000
 403833                   None       None
 409395    73   32872174  None    5573992,
        ddd_1 telefone_1 ddd_2 telefone_2

In [ ]:
contatos_ruins = []
contatos = []

for path in dados_estab:
    df = pd.read_parquet(path)
    colunas = ['ddd_1', 'telefone_1', 'ddd_2', 'telefone_2']
    
    verificador = df[colunas].apply(lambda x: x.str.contains(r'[^0-9]', na=False, regex=True))
    mascara = verificador.any(axis=1)
    
    # Criamos a fatia com os problemas
    df_problemas = df[colunas][mascara]
    
    if not df_problemas.empty:
        # SALVAMOS UMA CÓPIA DA VERSÃO RUIM (Original)
        contatos_ruins.append(df_problemas.copy()) 
        
        # Agora alteramos o df_problemas original
        for coluna in colunas:
            df_problemas[coluna] = df_problemas[coluna].str.replace(r'\D', '', regex=True)
            
        # SALVAMOS A VERSÃO QUE FOI EDITADA
        contatos.append(df_problemas)    
    
    del df
    # O del df_problemas aqui é seguro pois as listas guardam as referências/cópias
    gc.collect()

In [ ]:
contatos_ruins

[       ddd_1 telefone_1 ddd_2 telefone_2
 47        66   498 6445  None       None
 1677     083   222 5141  None       None
 1679     083   221 9292  None       None
 1681     083   224 2356  None       None
 4124     011   61419415  None       None
 ...      ...        ...   ...        ...
 465895  0011    7396572  None       None
 467477    49   677 0195  None       None
 476196  0532     651028  None       None
 481818    49   864 0034  None       None
 488366   024    3521671  None       None

 [190 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 235976    27   3711 131  None       None
 238811    21   2639 457  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 326255   035   212 1320  None       None
 326635  0532    21 3614  None       None
 327554  0011    2679657  None       None
 329736   035   471 1102  None       None
 330255   063   851 3441  None       None
 ...      ...        ...   ...        ...
 491936    75   422 3728  None       None
 492775   067   238 1765  None       None
 494412   083   246 3181  None       None
 496243   021   240 9838  None       None
 496264   021   262 8808  None       None

 [131 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 90       021   253 5469  None       None
 374      067   445 1270  None       None
 1892     051   634 1144  None       None
 1984     055   232 1264  None       None
 3329     083   292 2720  None       None
 ...      ...        ...   ...        ...
 483930    41   338 3235  None       None
 486271   088   531 1084  None       None
 486972   053    2710544  None       None
 491811   021   224 8846  None       None
 497557   021   242 5154  None       None

 [250 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 2826     016   610 5600  None       None
 3026     086   483 1430  None       None
 7158     021   533 1183  None       None
 12393    044   224 0570  None       None
 19299     49    3231097  None       None
 ...      ...        ...   ...        ...
 491273    48   624 6164  None       None
 491866    21   8868-569  None       None
 496375    18   2217-542    18    2210244
 496505    54   5220-090    54   91264211
 499902   067   786 9513  None       None

 [90 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 271      021   292 3939  None       None
 2202      74   35351231    74   353-5084
 2518      51   4729-248    51   30311444
 4543      11   2944-785    11   67845296
 5105      61   362-7346    61   36277138
 ...      ...        ...   ...        ...
 486868   085    2731731  None       None
 491639   067   382 8065  None       None
 495565    94   421 1519  None       None
 497242   021   263 4433  None       None
 497316   083   231 6904  None       None

 [198 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 32        14   97037342    14   972-1386
 11460     85   323-5302    85   96113631
 11551     43   35251033    43   352-5113
 17428     13   323-5669  None       None
 19902     18   33711491    18   977-5-32
 19923     21   2446-397    21   22693967
 25409     51   965-2753  None       None
 27289     14   37651733    14   376-5833
 28557     54   323-2726  None       None
 35589     62     329113    62    328-970
 37165     66   353-1552    66   35316816
 40125     62   333-7112  None       None
 42538     16   37271424    16   372-7181
 44250     35    382-177  None       None
 47334     11   4428-600  None       None
 51335     21   24645247    21   301-7532
 54804     68   8408-461  None       None
 55130     41   332-2848    41   30131475
 55641     14   37141182    14   3714-119
 56450     91   96247339    91   344-9136
 75202     16   3402 718  None       None
 198395    30   2503 093  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 32346     88   361-1453  None       None
 129032    12          0  None       None
 129656    19   771604 0  None       None
 144735    22          0  None       None
 165807    14          0  None       None
 165837    67          0  None       None
 166893    19          0  None       None
 166968    34   531354 0  None       None
 167831    83          0  None       None
 168002    88   131467 0  None       None
 168497    21          0  None       None
 169806    74   653441 0  None       None
 169927    94          0  None       None
 170716    91          0  None       None
 171161    91   210682 0  None       None
 171290    88          0  None       None
 175001    84          0  None       None
 175113    99          0  None       None
 175137    31          0  None       None
 175393    87          0  None       None
 175419    77          0  None       None
 175976    31          0  None       None
 176217    98   1206   0  None       None
 176908    32   351964 0  None       None
 176978    62          0  None       None
 176986    31          0  None       None
 179636    13          0  None       None
 183414    74          0  None       None
 334661    91   2244-642  None       None
 371784    85          0  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 1293    0532     721717  None       None
 2338      55    4123601  None       None
 7962    0031    4821700  None       None
 7996     071    9714708  None       None
 9157      54   213 5000  None       None
 ...      ...        ...   ...        ...
 482442    47    3362445  None       None
 485974    41    2735535  None       None
 495049    51   362-5318  None       None
 495939   021   220 9535  None       None
 498185    51   37142204    51   3714-220

 [126 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 50454     11   2671 741  None       None
 50467     16   3945 199  None       None
 50744     19   3561 154  None       None
 51465     21   3275 599  None       None
 51477     19   5276 046  None       None
 51544     24   2482 994  None       None
 51602     22   2624 091  None       None
 51637     21   2756 171  None       None
 51659     21   2290 901  None       None
 60757     21   2225 155  None       None
 67899     21   3474 546  None       None
 131577    62   32255728  None   +5562322
 138573    16   32627192  None   (16) 326
 205220    **   ********  None       None
 232504    18   32696275  None   19200-00
 247839    **   ********  None       None
 437351    51   3656 357  None       None
 447607    38   3725 120  None       None
 451816    31   3642 388  None       None
 452014    31   3641 468  None       None
 452046    16   3146 111  None       None
 452682    28   3552 619  None       None
 452869    38   3723 112  None       None
 452973    13   3386 442  None       None
 453069    33   3277 285  None       None
 455614    86   3323 827  None       None
 455756    33   3225 261  None       None
 455818    22   2793 366  None       None
 459961    24   3320 589  None       None
 460281    19   3225 614  None       None
 461035    54   3211 380  None       None
 467756    16   3415 031  None       None
 467803    19   3821 111  None       None
 468695    31   3718 128  None       None
 468778    85   3371 238  None       None
 468893    19   3327 324  None       None
 468958    16   3627 338  None       None
 469139    62   3281 773  None       None
 469246    81   9859 230  None       None
 471284    47   3372 347  None       None
 472381    75   3224 106  None       None
 478596    11   2331 369  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 52848     98   346113 0  None       None
 53771     27   3269 145  None       None
 87123     47          0  None       None
 94837     14   3434 046  None       None
 96661     49   3444 030  None       None
 ...      ...        ...   ...        ...
 256601    14   3478 153  None       None
 256602    67   3541 170  None       None
 256611    18   3622 393  None       None
 256616    31   3033 297  None       None
 460562    33   3251 201  None       None

 [86 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 56824     21   2659 213  None       None
 325238    21   7583 561  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 225600    61   93187548    61   81489415
 248143    61   81273492  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 410690    27   229-2743  None       None
 412195  0243     711155  None       None
 413172    71   377 3864  None       None
 417870  0243     650690  None       None
 417896  0243     654163  None       None
 ...      ...        ...   ...        ...
 494380    49   323 5275  None       None
 495196   067   751 0120  None       None
 496474   067   383 3401  None       None
 497876  0243     711404  None       None
 499095  0243     422317  None       None

 [70 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 1751     021   532 3757  None       None
 2062     067   763 2170  None       None
 2248     067   386 8791  None       None
 4625     079    9822232  None       None
 8986     067   386 1947  None       None
 ...      ...        ...   ...        ...
 484315   032    7223425  None       None
 485259    47   3437-032    47   30255568
 486900   071    3770848  None       None
 494259  0083    2226970  None       None
 498065    71    2593632  None       None

 [337 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 3815    0243     650699  None       None
 4612     071    6351166  None       None
 11421     61    3524203  None       None
 14439     62   431 0809  None       None
 15810    021   571 5283  None       None
 ...      ...        ...   ...        ...
 463640    16   33752332    17   334-2711
 464982    81   32690871    81   326-9087
 465317    21   26031533    21   260-3176
 470089    37   224-1123  None       None
 474491    62          0  None       None

 [159 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 786       71   306 2059  None       None
 5521     011    4411827  None       None
 8320    0132    30 2858  None       None
 9705     021   297 3922  None       None
 13944   0729       5470  None       None
 ...      ...        ...   ...        ...
 464905   051    5441149  None       None
 469073    16   6244-344  None       None
 474469   021   262 9536  None       None
 485382   021   262 0887  None       None
 498015    65   332-2055    65   33220551

 [105 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 5246    0319   954 4869  None       None
 10787    067   761 6530  None       None
 12894     54    3921070  None       None
 17194    021   232 5180  None       None
 26290    021   220 8004  None       None
 ...      ...        ...   ...        ...
 471252    61    2483015  None       None
 472838    47    3511312    47   335-1131
 479469   083   248 2004  None       None
 480017   021   262 2440  None       None
 481769    85    2523644  None       None

 [169 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 1823     083   221 9724  None       None
 7555     083   225 1910  None       None
 35074    088    8311138  None       None
 37546     86   000-0000  None       None
 45553   0083    2224193  None       None
 54461    063   841 1255  None       None
 60277   None       3621  1535       None
 62653    067   787 1286  None       None
 65563    011   69573377  None       None
 67690    067   382 4265  None       None
 78984     51   359-8232    51   35984676
 81553    021   220 7576  None       None
 83850   6714   786 1556  None       None
 86915     31   99828077    31   2242-030
 87163     65   369-2212  None       None
 88412     17   36991194    17   369-9716
 89496     85   323-5302    85   32333743
 89647     49   95460998    49   354-6099
 90531     11   3062 315  None       None
 95639     84   996-3020    84   99630208
 96056     75   322-1460  None       None
 99241     21   265-8555    21   87386444
 103396    73   361-7713    73   36177133
 108144    17   35224269    17   9141-076
 113123    61   3572-898  None       None
 113261    75   325-1182  None       None
 113722    61   334-5118  None       None
 123280    99   880-1542  None       None
 124542    45   322-2638  None       None
 134853    51   3334-497  None       None
 138109    27   40094657    27   400-9465
 141873    16   36645621    16   999-6823
 144601    53   998-2675  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 121269    61   361-2309    61   36121718
 124523    62   355-8515  None       None
 127585    17   3525 337  None       None
 180639    21   22553267    21   225-5326
 231163    27          0  None       None
 249528    11          0  None       None
 252086    11          0  None       None
 252209    77          0  None       None
 254335    11          0  None       None
 254894    33   631426 0  None       None
 256189    54   2129   0  None       None
 257153    79   993790 0  None       None
 258097    98          0  None       None
 258117    38          0  None       None
 258385    65          0  None       None
 259164    63   336941 0  None       None
 261304    11          0  None       None
 261446    22          0  None       None
 261563    13          0  None       None
 261610    11          0  None       None
 261655    62          0  None       None
 261695    37          0  None       None
 262665    94          0  None       None
 262770    46   147503 0  None       None
 263213    96          0  None       None
 263218    62          0  None       None
 263263    32   841306 0  None       None
 263319    38          0  None       None
 264139    33   352123 0  None       None
 266234    12          0  None       None
 272562    68   1105   0  None       None
 273905    79          0  None       None
 284457    17   33614762    17   336-1158
 458264    71          0  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 136847    12   3307 289  None       None
 136872    11   4198 550  None       None
 136884    11   3603 477  None       None
 136896    16   3342 338  None       None
 137423    87   3862 226  None       None
 137743    21   3404 707  None       None
 138025    21   2290 397  None       None
 138030    21   2475 135  None       None
 138044    21   2796 317  None       None
 138054    21   3703 794  None       None
 138061    21   2232 368  None       None
 143133    21   3292 312  None       None
 162020    21   2697 029  None       None
 171370    99   36631192    99   (99) 366
 217213    64   35472116  None   +5564354
 219403    83   3337 172  None       None
 258294    21   39073713    21   +5521365
 287552    **   ********  None       None
 291843    **   ********  None       None
 294750    44   99022073  None   +5544990
 304902    14   37623941  None   18740-00
 318847    **   ********  None       None
 327881    **   ********  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 33060     54   3822 281  None       None
 33158     38   3725 132  None       None
 33373     87   3822 290  None       None
 33752     14   3417 396  None       None
 36681     21   2693 062  None       None
 ...      ...        ...   ...        ...
 279255    33   3271 572  None       None
 279314    71   3266 114  None       None
 279385    19   3884 410  None       None
 342975    64   3404 139  None       None
 343011    11   4576 230  None       None

 [103 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 411611    85   3294 305  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 180286    21   2201 827  None       None
 236142    21   2281 233  None       None
 317201    21   3596 295  None       None
 384364    **   ********  None       None
 449135    18   32832681    18   328-3268,
        ddd_1 telefone_1 ddd_2 telefone_2
 172637    31   93165042     '       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 499188  0243     623227  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 128       55    323-810  None       None
 527     0352   282 1245  None       None
 724      083   235 5636  None       None
 3611     027   763 1194  None       None
 4714     011    9164844  None       None
 ...      ...        ...   ...        ...
 486749    51    3383488  None       None
 487051   067   721 2721  None       None
 493832   017   522 6580  None       None
 494399   019   422 0088  None       None
 495304   016   690 1300  None       None

 [340 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 2926    0243     651359  None       None
 3731     067   681 1041  None       None
 3964      91   468 1568  None       None
 4344      41    2726851  None       None
 8059     015   233 3938  None       None
 ...      ...        ...   ...        ...
 453448   021    5951818  None       None
 462467    48   32451245    48   324-5108
 471357   011    6912378  None       None
 476375   011   69449900  None       None
 492328   021   532 2766  None       None

 [108 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 6954     021   205 8828  None       None
 11646    011   61010101  None       None
 12032    021   242 4374  None       None
 23260     53   261 1911  None       None
 23557    021   233 4148  None       None
 ...      ...        ...   ...        ...
 480599    64   365-7147  None       None
 480819    84   322-3704    84   32237042
 491077   091   250 5000  None       None
 493085   021   221 3242  None       None
 498479    47   353-3137    47   35333099

 [150 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 1249      44   326-7774  None       None
 1323      47   332-2263  None       None
 5609     035   265 2752  None       None
 6332      24    3542018  None       None
 7094     047    4263757  None       None
 ...      ...        ...   ...        ...
 228438    51   35973566    51   359-8282
 228774    48   880-2142  None       None
 228895    83          0  None       None
 229113    49   3652-757  None       None
 259378    65    354-387    65   33549700

 [88 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 43407     41   33290475    41   3329047-
 120746    21   3486 340  None       None
 205871    22   000-0000  None       None
 209650    08   32126820    83   321-2682
 210597    21   262-0344  None       None
 338552    11          0  None       None
 338572    11   404894 0  None       None
 339691    37   141138 0  None       None
 342525    91    41218 0  None       None
 342599    85          0  None       None
 342616    21          0  None       None
 342627    11          0  None       None
 342674    91   254882 0  None       None
 342752    67          0  None       None
 343967    64   925833 0  None       None
 343977    27          0  None       None
 345637    81          0  None       None
 346304    99   998824 0  None       None
 346413    96          0  None       None
 346460    54   3615   0  None       None
 347085    42   344893 0  None       None
 347272    85   592389 0  None       None
 348274    99   518267 0  None       None
 348806    65          0  None       None
 349149    91          0  None       None
 349773    62          0  None       None
 430031    86   312004 0  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 5537      51   359-5330    51   359-5330
 5857      11   553-3688    11   99890248
 6700      19   32276808    19   322-7680
 45103     87          0  None       None
 45272     86          0  None       None
 150578    **   ********  None       None
 223281    11   2378 131  None       None
 223327    11   2068 608  None       None
 223589    17   3013 470  None       None
 223950    11   5 677315  None       None
 224306    21   3316 080  None       None
 224377    21   2450 044  None       None
 224380    21   3272 496  None       None
 224458    24   2485 311  None       None
 225789    24   2242 429  None       None
 305753    12   3888 400  None       None
 345360    51   81014254  None   +5551810
 376881    15   35323710  None   18460-00
 403833    **   ********  None       None
 409395    73   32872174  None   +5573992,
        ddd_1 telefone_1 ddd_2 telefone_2

In [ ]:
contatos

[       ddd_1 telefone_1 ddd_2 telefone_2
 47        66    4986445  None       None
 1677     083    2225141  None       None
 1679     083    2219292  None       None
 1681     083    2242356  None       None
 4124     011   61419415  None       None
 ...      ...        ...   ...        ...
 465895  0011    7396572  None       None
 467477    49    6770195  None       None
 476196  0532     651028  None       None
 481818    49    8640034  None       None
 488366   024    3521671  None       None

 [190 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 235976    27    3711131  None       None
 238811    21    2639457  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 326255   035    2121320  None       None
 326635  0532     213614  None       None
 327554  0011    2679657  None       None
 329736   035    4711102  None       None
 330255   063    8513441  None       None
 ...      ...        ...   ...        ...
 491936    75    4223728  None       None
 492775   067    2381765  None       None
 494412   083    2463181  None       None
 496243   021    2409838  None       None
 496264   021    2628808  None       None

 [131 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 90       021    2535469  None       None
 374      067    4451270  None       None
 1892     051    6341144  None       None
 1984     055    2321264  None       None
 3329     083    2922720  None       None
 ...      ...        ...   ...        ...
 483930    41    3383235  None       None
 486271   088    5311084  None       None
 486972   053    2710544  None       None
 491811   021    2248846  None       None
 497557   021    2425154  None       None

 [250 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 2826     016    6105600  None       None
 3026     086    4831430  None       None
 7158     021    5331183  None       None
 12393    044    2240570  None       None
 19299     49    3231097  None       None
 ...      ...        ...   ...        ...
 491273    48    6246164  None       None
 491866    21    8868569  None       None
 496375    18    2217542    18    2210244
 496505    54    5220090    54   91264211
 499902   067    7869513  None       None

 [90 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 271      021    2923939  None       None
 2202      74   35351231    74    3535084
 2518      51    4729248    51   30311444
 4543      11    2944785    11   67845296
 5105      61    3627346    61   36277138
 ...      ...        ...   ...        ...
 486868   085    2731731  None       None
 491639   067    3828065  None       None
 495565    94    4211519  None       None
 497242   021    2634433  None       None
 497316   083    2316904  None       None

 [198 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 32        14   97037342    14    9721386
 11460     85    3235302    85   96113631
 11551     43   35251033    43    3525113
 17428     13    3235669  None       None
 19902     18   33711491    18     977532
 19923     21    2446397    21   22693967
 25409     51    9652753  None       None
 27289     14   37651733    14    3765833
 28557     54    3232726  None       None
 35589     62     329113    62     328970
 37165     66    3531552    66   35316816
 40125     62    3337112  None       None
 42538     16   37271424    16    3727181
 44250     35     382177  None       None
 47334     11    4428600  None       None
 51335     21   24645247    21    3017532
 54804     68    8408461  None       None
 55130     41    3322848    41   30131475
 55641     14   37141182    14    3714119
 56450     91   96247339    91    3449136
 75202     16    3402718  None       None
 198395    30    2503093  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 32346     88    3611453  None       None
 129032    12          0  None       None
 129656    19    7716040  None       None
 144735    22          0  None       None
 165807    14          0  None       None
 165837    67          0  None       None
 166893    19          0  None       None
 166968    34    5313540  None       None
 167831    83          0  None       None
 168002    88    1314670  None       None
 168497    21          0  None       None
 169806    74    6534410  None       None
 169927    94          0  None       None
 170716    91          0  None       None
 171161    91    2106820  None       None
 171290    88          0  None       None
 175001    84          0  None       None
 175113    99          0  None       None
 175137    31          0  None       None
 175393    87          0  None       None
 175419    77          0  None       None
 175976    31          0  None       None
 176217    98      12060  None       None
 176908    32    3519640  None       None
 176978    62          0  None       None
 176986    31          0  None       None
 179636    13          0  None       None
 183414    74          0  None       None
 334661    91    2244642  None       None
 371784    85          0  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 1293    0532     721717  None       None
 2338      55    4123601  None       None
 7962    0031    4821700  None       None
 7996     071    9714708  None       None
 9157      54    2135000  None       None
 ...      ...        ...   ...        ...
 482442    47    3362445  None       None
 485974    41    2735535  None       None
 495049    51    3625318  None       None
 495939   021    2209535  None       None
 498185    51   37142204    51    3714220

 [126 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 50454     11    2671741  None       None
 50467     16    3945199  None       None
 50744     19    3561154  None       None
 51465     21    3275599  None       None
 51477     19    5276046  None       None
 51544     24    2482994  None       None
 51602     22    2624091  None       None
 51637     21    2756171  None       None
 51659     21    2290901  None       None
 60757     21    2225155  None       None
 67899     21    3474546  None       None
 131577    62   32255728  None    5562322
 138573    16   32627192  None      16326
 205220                   None       None
 232504    18   32696275  None    1920000
 247839                   None       None
 437351    51    3656357  None       None
 447607    38    3725120  None       None
 451816    31    3642388  None       None
 452014    31    3641468  None       None
 452046    16    3146111  None       None
 452682    28    3552619  None       None
 452869    38    3723112  None       None
 452973    13    3386442  None       None
 453069    33    3277285  None       None
 455614    86    3323827  None       None
 455756    33    3225261  None       None
 455818    22    2793366  None       None
 459961    24    3320589  None       None
 460281    19    3225614  None       None
 461035    54    3211380  None       None
 467756    16    3415031  None       None
 467803    19    3821111  None       None
 468695    31    3718128  None       None
 468778    85    3371238  None       None
 468893    19    3327324  None       None
 468958    16    3627338  None       None
 469139    62    3281773  None       None
 469246    81    9859230  None       None
 471284    47    3372347  None       None
 472381    75    3224106  None       None
 478596    11    2331369  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 52848     98    3461130  None       None
 53771     27    3269145  None       None
 87123     47          0  None       None
 94837     14    3434046  None       None
 96661     49    3444030  None       None
 ...      ...        ...   ...        ...
 256601    14    3478153  None       None
 256602    67    3541170  None       None
 256611    18    3622393  None       None
 256616    31    3033297  None       None
 460562    33    3251201  None       None

 [86 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 56824     21    2659213  None       None
 325238    21    7583561  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 225600    61   93187548    61   81489415
 248143    61   81273492  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 410690    27    2292743  None       None
 412195  0243     711155  None       None
 413172    71    3773864  None       None
 417870  0243     650690  None       None
 417896  0243     654163  None       None
 ...      ...        ...   ...        ...
 494380    49    3235275  None       None
 495196   067    7510120  None       None
 496474   067    3833401  None       None
 497876  0243     711404  None       None
 499095  0243     422317  None       None

 [70 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 1751     021    5323757  None       None
 2062     067    7632170  None       None
 2248     067    3868791  None       None
 4625     079    9822232  None       None
 8986     067    3861947  None       None
 ...      ...        ...   ...        ...
 484315   032    7223425  None       None
 485259    47    3437032    47   30255568
 486900   071    3770848  None       None
 494259  0083    2226970  None       None
 498065    71    2593632  None       None

 [337 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 3815    0243     650699  None       None
 4612     071    6351166  None       None
 11421     61    3524203  None       None
 14439     62    4310809  None       None
 15810    021    5715283  None       None
 ...      ...        ...   ...        ...
 463640    16   33752332    17    3342711
 464982    81   32690871    81    3269087
 465317    21   26031533    21    2603176
 470089    37    2241123  None       None
 474491    62          0  None       None

 [159 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 786       71    3062059  None       None
 5521     011    4411827  None       None
 8320    0132     302858  None       None
 9705     021    2973922  None       None
 13944   0729       5470  None       None
 ...      ...        ...   ...        ...
 464905   051    5441149  None       None
 469073    16    6244344  None       None
 474469   021    2629536  None       None
 485382   021    2620887  None       None
 498015    65    3322055    65   33220551

 [105 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 5246    0319    9544869  None       None
 10787    067    7616530  None       None
 12894     54    3921070  None       None
 17194    021    2325180  None       None
 26290    021    2208004  None       None
 ...      ...        ...   ...        ...
 471252    61    2483015  None       None
 472838    47    3511312    47    3351131
 479469   083    2482004  None       None
 480017   021    2622440  None       None
 481769    85    2523644  None       None

 [169 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 1823     083    2219724  None       None
 7555     083    2251910  None       None
 35074    088    8311138  None       None
 37546     86    0000000  None       None
 45553   0083    2224193  None       None
 54461    063    8411255  None       None
 60277   None       3621  1535       None
 62653    067    7871286  None       None
 65563    011   69573377  None       None
 67690    067    3824265  None       None
 78984     51    3598232    51   35984676
 81553    021    2207576  None       None
 83850   6714    7861556  None       None
 86915     31   99828077    31    2242030
 87163     65    3692212  None       None
 88412     17   36991194    17    3699716
 89496     85    3235302    85   32333743
 89647     49   95460998    49    3546099
 90531     11    3062315  None       None
 95639     84    9963020    84   99630208
 96056     75    3221460  None       None
 99241     21    2658555    21   87386444
 103396    73    3617713    73   36177133
 108144    17   35224269    17    9141076
 113123    61    3572898  None       None
 113261    75    3251182  None       None
 113722    61    3345118  None       None
 123280    99    8801542  None       None
 124542    45    3222638  None       None
 134853    51    3334497  None       None
 138109    27   40094657    27    4009465
 141873    16   36645621    16    9996823
 144601    53    9982675  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 121269    61    3612309    61   36121718
 124523    62    3558515  None       None
 127585    17    3525337  None       None
 180639    21   22553267    21    2255326
 231163    27          0  None       None
 249528    11          0  None       None
 252086    11          0  None       None
 252209    77          0  None       None
 254335    11          0  None       None
 254894    33    6314260  None       None
 256189    54      21290  None       None
 257153    79    9937900  None       None
 258097    98          0  None       None
 258117    38          0  None       None
 258385    65          0  None       None
 259164    63    3369410  None       None
 261304    11          0  None       None
 261446    22          0  None       None
 261563    13          0  None       None
 261610    11          0  None       None
 261655    62          0  None       None
 261695    37          0  None       None
 262665    94          0  None       None
 262770    46    1475030  None       None
 263213    96          0  None       None
 263218    62          0  None       None
 263263    32    8413060  None       None
 263319    38          0  None       None
 264139    33    3521230  None       None
 266234    12          0  None       None
 272562    68      11050  None       None
 273905    79          0  None       None
 284457    17   33614762    17    3361158
 458264    71          0  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 136847    12    3307289  None       None
 136872    11    4198550  None       None
 136884    11    3603477  None       None
 136896    16    3342338  None       None
 137423    87    3862226  None       None
 137743    21    3404707  None       None
 138025    21    2290397  None       None
 138030    21    2475135  None       None
 138044    21    2796317  None       None
 138054    21    3703794  None       None
 138061    21    2232368  None       None
 143133    21    3292312  None       None
 162020    21    2697029  None       None
 171370    99   36631192    99      99366
 217213    64   35472116  None    5564354
 219403    83    3337172  None       None
 258294    21   39073713    21    5521365
 287552                   None       None
 291843                   None       None
 294750    44   99022073  None    5544990
 304902    14   37623941  None    1874000
 318847                   None       None
 327881                   None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 33060     54    3822281  None       None
 33158     38    3725132  None       None
 33373     87    3822290  None       None
 33752     14    3417396  None       None
 36681     21    2693062  None       None
 ...      ...        ...   ...        ...
 279255    33    3271572  None       None
 279314    71    3266114  None       None
 279385    19    3884410  None       None
 342975    64    3404139  None       None
 343011    11    4576230  None       None

 [103 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 411611    85    3294305  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 180286    21    2201827  None       None
 236142    21    2281233  None       None
 317201    21    3596295  None       None
 384364                   None       None
 449135    18   32832681    18    3283268,
        ddd_1 telefone_1 ddd_2 telefone_2
 172637    31   93165042             None,
        ddd_1 telefone_1 ddd_2 telefone_2
 499188  0243     623227  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 128       55     323810  None       None
 527     0352    2821245  None       None
 724      083    2355636  None       None
 3611     027    7631194  None       None
 4714     011    9164844  None       None
 ...      ...        ...   ...        ...
 486749    51    3383488  None       None
 487051   067    7212721  None       None
 493832   017    5226580  None       None
 494399   019    4220088  None       None
 495304   016    6901300  None       None

 [340 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 2926    0243     651359  None       None
 3731     067    6811041  None       None
 3964      91    4681568  None       None
 4344      41    2726851  None       None
 8059     015    2333938  None       None
 ...      ...        ...   ...        ...
 453448   021    5951818  None       None
 462467    48   32451245    48    3245108
 471357   011    6912378  None       None
 476375   011   69449900  None       None
 492328   021    5322766  None       None

 [108 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 6954     021    2058828  None       None
 11646    011   61010101  None       None
 12032    021    2424374  None       None
 23260     53    2611911  None       None
 23557    021    2334148  None       None
 ...      ...        ...   ...        ...
 480599    64    3657147  None       None
 480819    84    3223704    84   32237042
 491077   091    2505000  None       None
 493085   021    2213242  None       None
 498479    47    3533137    47   35333099

 [150 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 1249      44    3267774  None       None
 1323      47    3322263  None       None
 5609     035    2652752  None       None
 6332      24    3542018  None       None
 7094     047    4263757  None       None
 ...      ...        ...   ...        ...
 228438    51   35973566    51    3598282
 228774    48    8802142  None       None
 228895    83          0  None       None
 229113    49    3652757  None       None
 259378    65     354387    65   33549700

 [88 rows x 4 columns],
        ddd_1 telefone_1 ddd_2 telefone_2
 43407     41   33290475    41    3329047
 120746    21    3486340  None       None
 205871    22    0000000  None       None
 209650    08   32126820    83    3212682
 210597    21    2620344  None       None
 338552    11          0  None       None
 338572    11    4048940  None       None
 339691    37    1411380  None       None
 342525    91     412180  None       None
 342599    85          0  None       None
 342616    21          0  None       None
 342627    11          0  None       None
 342674    91    2548820  None       None
 342752    67          0  None       None
 343967    64    9258330  None       None
 343977    27          0  None       None
 345637    81          0  None       None
 346304    99    9988240  None       None
 346413    96          0  None       None
 346460    54      36150  None       None
 347085    42    3448930  None       None
 347272    85    5923890  None       None
 348274    99    5182670  None       None
 348806    65          0  None       None
 349149    91          0  None       None
 349773    62          0  None       None
 430031    86    3120040  None       None,
        ddd_1 telefone_1 ddd_2 telefone_2
 5537      51    3595330    51    3595330
 5857      11    5533688    11   99890248
 6700      19   32276808    19    3227680
 45103     87          0  None       None
 45272     86          0  None       None
 150578                   None       None
 223281    11    2378131  None       None
 223327    11    2068608  None       None
 223589    17    3013470  None       None
 223950    11    5677315  None       None
 224306    21    3316080  None       None
 224377    21    2450044  None       None
 224380    21    3272496  None       None
 224458    24    2485311  None       None
 225789    24    2242429  None       None
 305753    12    3888400  None       None
 345360    51   81014254  None    5551810
 376881    15   35323710  None    1846000
 403833                   None       None
 409395    73   32872174  None    5573992,
        ddd_1 telefone_1 ddd_2 telefone_2

**4. Alvos Valiosos para Fusões e Aquisições (Foco em Conversão de Tipos)**
Uma consultoria financeira (M&A) está em busca de "alvos" promissores. Eles querem focar em negócios classificados oficialmente como "Empresa de Pequeno Porte" (EPP), mas que possuam um capital social declarado muito alto, superior a R$ 2.000.000,00.
* **Tarefa:** Acesse a base de Empresas e filtre por esse porte específico (descubra o código correspondente a EPP). Trate a coluna de capital social (removendo ou alterando caracteres de texto, se necessário) para que o Python a entenda como um número decimal puro (Float). Extraia apenas as empresas que superam estritamente a marca de 2 milhões e salve o resultado em `alvos_aquisicao_epp.csv`.

PORTE DA EMPRESA:
CÓDIGOS DO PORTE DA EMPRESA:

00 – NÃO INFORMADO

01 - MICRO EMPRESA

03 - EMPRESA DE PEQUENO PORTE

05 - DEMAIS

In [ ]:
diretorio_dados = r'C:\Users\mayma\Documents\Projetos\Big_data-Consulta_CNPJ_Brasil\Base_de_dados_parquet'

dados_empresas = glob.glob(os.path.join(diretorio_dados, 'Empresas*'))

dados_empresas

['C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_10.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_11.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_12.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_13.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_14.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_15.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_16.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_17.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_18.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_19.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_20.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_21.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_22.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_23.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_24.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_25.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_26.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_27.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_28.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_29.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_30.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_31.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_32.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_33.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_34.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_35.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_36.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_37.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_38.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_39.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_40.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_41.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_42.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_43.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_44.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_45.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_46.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_47.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_48.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_49.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_50.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_51.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_52.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_53.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_54.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_55.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas0_9.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas1.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas2.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas4.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas5.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas7.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Empresas9.parquet']

In [ ]:
import random

indice_aleat = random.randrange(len(dados_empresas))

previa = pd.read_parquet(dados_empresas[indice_aleat])

previa

,cnpj_basico,razao_social,natureza_juridica,qualificacao_responsavel,capital_social,porte_empresa,ente_federativo_responsavel
0,59570674,59.570.674 ISRAEL SANTOS SILVA,2135,50,"2000,00",01,None
1,59570675,NATHALIA ERTHAL CLINICA DE PSICOLOGIA E SAUDE ...,2062,49,"10000,00",01,None
2,59570676,CABANA DO SONO KIDS LTDA,2062,49,"20000,00",01,None
3,59570677,WL SERVICOS AUTOMOTIVOS LTDA,2062,49,"40000,00",03,None
4,59570678,59.570.678 YURI ALVES BANDEIRA,2135,50,"5000,00",01,None
...,...,...,...,...,...,...,...
499995,60072738,60.072.738 MARLEYZE QUEIROZ DE SOUZA,2135,50,"5000,00",01,None
499996,60072739,60.072.739 NEILSON DE JESUS RODRIGUES DOS SANTOS,2135,50,"1518,00",01,None
499997,60072740,60.072.740 KLEBERT SANTOS WANDERLEY,2135,50,"1000,00",01,None
499998,60072741,ROSA & FRANCO LTDA,2062,49,"0,00",05,None
499999,60072742,60.072.742 WYTHORIA VALENTINA FERNANDES SILVA,2135,50,"500,00",01,None

In [ ]:
previa.columns

Index(['cnpj_basico', 'razao_social', 'natureza_juridica',
       'qualificacao_responsavel', 'capital_social', 'porte_empresa',
       'ente_federativo_responsavel'],
      dtype='object')

In [ ]:
previa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   cnpj_basico                  500000 non-null  object
 1   razao_social                 500000 non-null  object
 2   natureza_juridica            500000 non-null  object
 3   qualificacao_responsavel     500000 non-null  object
 4   capital_social               500000 non-null  object
 5   porte_empresa                500000 non-null  object
 6   ente_federativo_responsavel  256 non-null     object
dtypes: object(7)
memory usage: 26.7+ MB

In [ ]:
previa[previa['porte_empresa'] == '03']

,cnpj_basico,razao_social,natureza_juridica,qualificacao_responsavel,capital_social,porte_empresa,ente_federativo_responsavel
38,43323682,ZINCAFER INDUSTRIA E COMERCIO LTDA,2062,49,"30000,00",03,None
177,43323826,MAFH SERVICOS LTDA,2062,49,"3000,00",03,None
550,43324211,ALEXANDRE COMERCIO DE AREIA E PEDRA LTDA,2062,49,"30000,00",03,None
567,43324229,"APC - ARQUITETURA, PROJETOS E CONSTRUCAO LTDA",2062,49,"10000,00",03,None
1023,43324696,CONSTRUTORA MEURA LTDA,2062,49,"50000,00",03,None
...,...,...,...,...,...,...,...
499759,43842972,ANGELICA GONCALVES MORAIS LTDA,2062,49,"20000,00",03,None
499819,43843037,DROGARIA LIDER FARMA LTDA,2062,49,"50000,00",03,None
499840,43843060,AF IMOBILIARIA LTDA,2062,49,"30000,00",03,None
499841,43843061,MATRIX LABORATORIO E DISTRIBUIDORA OTICA LTDA.,2062,49,"200000,00",03,None
499859,43843079,AMARAL COMERCIO DE VEICULOS LTDA,2062,49,"30000,00",03,None

In [ ]:
alvos = []

for path in dados_empresas:
    df = pd.read_parquet(path)

    df['capital_social'] = df['capital_social'].str.replace(',', '.', regex = False)

    df['capital_social'] = pd.to_numeric(df['capital_social'], errors = 'coerce')

    filtros = ((df['porte_empresa'] == '03') & (df['capital_social'] > 2000000))

    df_filtrado = df[filtros]

    if not df_filtrado.empty:
        alvos.append(df_filtrado)
    
    del df
    gc.collect()

alvos

[       cnpj_basico                                       razao_social  \
 3026      41276622                              AGROPECUARIA ISA LTDA
 4710      41278312                 AGROPECUARIA STABILLE & MOURA LTDA
 7120      41280730                              A. S. DOS SANTOS LTDA
 12825     41286450                            LEPAUS IMPORTADORA LTDA
 25358     41299018   C3R3 LOCACAO E ADMINISTRACAO DE IMOVEIS SPE LTDA
 ...            ...                                                ...
 490162    41767338  MAXIRAFIA INDUSTRIA IMPORTACAO EXPORTACAO DE E...
 490983    41768160                   ROSA MONTEIRO ADMINISTRACAO LTDA
 492301    41769478                             CMF INCORPORADORA LTDA
 497587    41774767        AUTO POSTO E COMERCIAL CRUZEIRO DO SUL LTDA
 499570    41776755        PORTO BRASIL ADMINISTRADORA DE IMOVEIS LTDA

        natureza_juridica qualificacao_responsavel  capital_social  \
 3026                2062                       49      8144885.36
 4710                2062                       49     11468152.00
 7120                2062                       49      2800000.00
 12825               2062                       49      5000000.00
 25358               2062                       05     13510000.00
 ...                  ...                      ...             ...
 490162              2062                       49      7350000.00
 490983              2062                       05      2338000.00
 492301              2062                       49      3428571.00
 497587              2062                       49      3000000.00
 499570              2062                       49      4839500.00

        porte_empresa ente_federativo_responsavel
 3026              03                        None
 4710              03                        None
 7120              03                        None
 12825             03                        None
 25358             03                        None
 ...              ...                         ...
 490162            03                        None
 490983            03                        None
 492301            03                        None
 497587            03                        None
 499570            03                        None

 [191 rows x 7 columns],
        cnpj_basico                                      razao_social  \
 1494      45922427                            A M ALVES HOLDING LTDA
 2344      45923284                HAROLDO AZEVEDO INCORPORACOES LTDA
 3737      45924707                       BL SERVICOS ESPORTIVOS LTDA
 5526      45926568  AMSP BRASIL SERVICOS PORTUARIOS E LOGISTICA LTDA
 20764     45942222                              LMA PATRIMONIAL LTDA
 ...            ...                                               ...
 493234    46433105              REALIZAR CONSULTORIA E SERVICOS LTDA
 493344    46433218                  APEX CONSULTORIA E SERVICOS LTDA
 496459    46436455                    LZ ADMINISTRADORA DE BENS LTDA
 499033    46439104      CONTINENTAL CONSTRUTORA E TERRAPLENAGEM LTDA
 499666    46439763       GWA HOLDING E PARTICIPACOES SOCIETARIA LTDA

        natureza_juridica qualificacao_responsavel  capital_social  \
 1494                2062                       49       2130000.0
 2344                2062                       49       3000000.0
 3737                2062                       49       4500000.0
 5526                2062                       49       4500000.0
 20764               2062                       49       4836000.0
 ...                  ...                      ...             ...
 493234              2062                       49       3000000.0
 493344              2062                       49       3000000.0
 496459              2062                       49       3500000.0
 499033              2062                       49       2500000.0
 499666              2062                       49       5600000.0

        porte_empresa ente_federativo_responsavel
 1494              03                        None
 2344              03                        None
 3737              03                        None
 5526              03                        None
 20764             03                        None
 ...              ...                         ...
 493234            03                        None
 493344            03                        None
 496459            03                        None
 499033            03                        None
 499666            03                        None

 [206 rows x 7 columns],
        cnpj_basico                                       razao_social  \
 4199      46444409                           AGROPECUARIA DROPPA LTDA
 8651      46448960  MAIS PHARMA REPRESENTACAO COMERCIO E DISTRIBUI...
 9043      46449380               5M EMPREENDIMENTOS IMOBILIARIOS LTDA
 15744     46456200                               COLEGIO VITORIA LTDA
 18534     46459116                     JLL SERVICOS E MANUTENCAO LTDA
 ...            ...                                                ...
 489354    46952851              SSA EMPREENDIMENTOS IMOBILIARIOS LTDA
 492606    46956319                         CORES EMPREENDIMENTOS LTDA
 492686    46956402                           CREDIMAIS RN BRASIL LTDA
 493852    46957630                         AGROPECUARIA 4 IRMAOS LTDA
 497507    46961423  CELERE TECNOLOGIA E ASSESSORIA EM SAUDE PUBLIC...

        natureza_juridica qualificacao_responsavel  capital_social  \
 4199                2062                       49       2478000.0
 8651                2062                       49       5000000.0
 9043                2062                       49       7500000.0
 15744               2062                       49       2400000.0
 18534               2062                       49       3000000.0
 ...                  ...                      ...             ...
 489354              2062                       49       2817940.0
 492606              2062                       49       2654000.0
 492686              2062                       49       5000000.0
 493852              2062                       49       2612018.0
 497507              2062                       49       4100000.0

        porte_empresa ente_federativo_responsavel
 4199              03                        None
 8651              03                        None
 9043              03                        None
 15744             03                        None
 18534             03                        None
 ...              ...                         ...
 489354            03                        None
 492606            03                        None
 492686            03                        None
 493852            03                        None
 497507            03                        None

 [191 rows x 7 columns],
        cnpj_basico                                      razao_social  \
 1181      46965255     INFINITY OCEAN IMPORTADORA E EXPORTADORA LTDA
 1763      46965859                        LISAJAN PARTICIPACOES LTDA
 7400      46971721                      GUERRA E GUERRA IMOVEIS LTDA
 9742      46974143    TELEFINO TELECOMUNICACOES E ELETRIFICACAO LTDA
 12124     46976605                   VOLTIO INDUSTRIA DO BRASIL LTDA
 ...            ...                                               ...
 489251    47476619  ESTORIL BAURU ADMINISTRACAO E PARTICIPACOES LTDA
 492955    47480331                   TERRA E TERRA AGROPECUARIA LTDA
 495259    47482638                                   47.482.638 LTDA
 495481    47482860                   STELL ACK HOLDING FAMILIAR LTDA
 499869    47487249           FAMILIA DELICIO GESTAO DE NEGOCIOS LTDA

        natureza_juridica qualificacao_responsavel  capital_social  \
 1181                2062                       49       4000000.0
 1763                2062                       49       5000000.0
 7400                2062                       49       4585417.0
 9742                2062                       49       4300000.0
 12124               2062                       49       2150000.0
 ...                  ...                      ...             ...
 489251              2062                       49       3870610.0
 492955              2062                       49       9000000.0
 495259              2062                       49     250000000.0
 495481              2062                       49       4426462.0
 499869              2062                       05       4557289.0

        porte_empresa ente_federativo_responsavel
 1181              03                        None
 1763              03                        None
 7400              03                        None
 9742              03                        None
 12124             03                        None
 ...              ...                         ...
 489251            03                        None
 492955            03                        None
 495259            03                        None
 495481            03                        None
 499869            03                        None

 [177 rows x 7 columns],
        cnpj_basico                                       razao_social  \
 2908      47490317                          POSTO ALIANZ COLINAS LTDA
 4388      47491805                 WARKENTIN HOLDING PATRIMONIAL LTDA
 13401     47500924                                  CASAL MENDES LTDA
 14031     47501554  SPE EMPREENDIMENTOS IMOBILIARIOS PARK IMPERIAL...
 14600     47502124                            AGROPECUARIA ZILIO LTDA
 ...            ...                                                ...
 489537    47991117                                    47.991.117 LTDA
 489996    47991585  CONSTRUTORA, LOCADORA E PRODUTORA DAVI SOUZA LTDA
 492768    47994435                CALENDA VAZ IMOVEIS E LOCACOES LTDA
 493510    47995194                 WZN PARTICIPACOES SOCIETARIAS LTDA
 499323    48001154                             RVV PARTICIPACOES LTDA

        natureza_juridica qualificacao_responsavel  capital_social  \
 2908                2062                       49    6.800000e+06
 4388                2062                       05    2.736500e+07
 13401               2062                       49    4.393163e+06
 14031               2062                       49    6.600000e+06
 14600               2062                       49    4.056664e+06
 ...                  ...                      ...             ...
 489537              2062                       49    1.000000e+12
 489996              2062                       49    1.000000e+07
 492768              2062                       49    2.400000e+06
 493510              2062                       49    2.825628e+06
 499323              2062                       49    3.412314e+06

        porte_empresa ente_federativo_responsavel
 2908              03                        None
 4388              03                        None
 13401             03                        None
 14031             03                        None
 14600             03                        None
 ...              ...                         ...
 489537            03                        None
 489996            03                        None
 492768            03                        None
 493510            03                        None
 499323            03                        None

 [206 rows x 7 columns],
        cnpj_basico                                       razao_social  \
 2677      48004602                 ACORDI ADMINISTRADORA DE BENS LTDA
 9144      48011214                             ATCE AGROPECUARIA LTDA
 11173     48013309                               BAIOCO & BAIOCO LTDA
 22580     48024927                  Z D N SERVICOS E CONSULTORIA LTDA
 29601     48032077                                  RUSSO DUARTE LTDA
 ...            ...                                                ...
 493492    48504706                             A4M INCORPORACOES LTDA
 498553    48509773                                   ALMA ENERGY LTDA
 498699    48509919                         FEITOSA PARTICIPACOES LTDA
 499461    48510682  GLOBAL COMERCIO DE JOIAS IMPORTADORA E EXPORTA...
 499923    48511146               N&M CONSTRUTORA E INCORPORADORA LTDA

        natureza_juridica qualificacao_responsavel  capital_social  \
 2677                2062                       49       3505000.0
 9144                2062                       49       2032326.0
 11173               2062                       49       3000000.0
 22580               2062                       49       3706265.0
 29601               2062                       49       3610000.0
 ...                  ...                      ...             ...
 493492              2062                       49       6402409.0
 498553              2062                       49       3343376.0
 498699              2062                       49       2172000.0
 499461              2062                       49      10000000.0
 499923              2062                       49       3000000.0

        porte_empresa ente_federativo_responsavel
 2677              03                        None
 9144              03                        None
 11173             03                        None
 22580             03                        None
 29601             03                        None
 ...              ...                         ...
 493492            03                        None
 498553            03                        None
 498699            03                        None
 499461            03                        None
 499923            03                        None

 [202 rows x 7 columns],
        cnpj_basico                                       razao_social  \
 764       48511987  HOLDING ANTUNES FRANZINI ADMINISTRACAO DE BENS...
 962       48512188                        AGROTOLFO AGRONEGOCIOS LTDA
 3803      48515029                         AGROPECUARIA VOLPATTO LTDA
 3891      48515117                              AGROPECUARIA MMO LTDA
 8108      48519360                   NUTRICIONISTA DAIANA GUEDES LTDA
 ...            ...                                                ...
 488062    49001717   SOARES & FIUZA EMPREENDIMENTOS IMOBILIARIOS LTDA
 489329    49002988              G5L EMPREENDIMENTOS IMOBILIARIOS LTDA
 489521    49003180               EDUARDO SERGIO KANAMURA & CIA. LTDA.
 491222    49004885                                    49.004.885 LTDA
 492834    49006499            PANDA CONSULTORIA E PARTICIPACOES LTDA.

        natureza_juridica qualificacao_responsavel  capital_social  \
 764                 2062                       49    2.300000e+06
 962                 2062                       49    3.500000e+06
 3803                2062                       49    3.558957e+06
 3891                2062                       49    9.550000e+06
 8108                2062                       49    1.000000e+07
 ...                  ...                      ...             ...
 488062              2062                       49    2.542000e+06
 489329              2062                       49    2.444995e+06
 489521              2062                       49    3.500082e+06
 491222              2062                       49    1.000000e+12
 492834              2062                       49    4.500000e+06

        porte_empresa ente_federativo_responsavel
 764               03                        None
 962               03                        None
 3803              03                        None
 3891              03                        None
 8108              03                        None
 ...              ...                         ...
 488062            03                        None
 489329            03                        None
 489521            03                        None
 491222            03                        None
 492834            03                        None

 [281 rows x 7 columns],
        cnpj_basico                                razao_social  \
 159       49013847              RPM NEGOCIOS IMOBILIARIOS LTDA
 1708      49015406                      ENSEMBLE SOLUTION LTDA
 6472      49020189  REMO CONSULTORIA E GESTAO EMPRESARIAL LTDA
 8871      49022597                    DULCE INVESTIMENTOS LTDA
 10165     49023896   SANTANA MATERIAL DE CONSTRUCAO UNIPESSOAL
 ...            ...                                         ...
 492624    49513464                         CRISTAL EDICAO LTDA
 493964    49514804    SERRA EVOLUTE CONSTRUCOES E LIMPEZA LTDA
 495732    49516573   MN DISTRIBUIDORA E COMERCIO DE PECAS LTDA
 498165    49519012        TELES CONSTRUCOES E CONSULTORIA LTDA
 499699    49520568               ROMA HOLDING PATRIMONIAL LTDA

        natureza_juridica qualificacao_responsavel  capital_social  \
 159                 2062                       49       2200000.0
 1708                2062                       49       5500000.0
 6472                2062                       49       5007000.0
 8871                2062                       49      19694136.0
 10165               2135                       50      80000000.0
 ...                  ...                      ...             ...
 492624              2062                       49       5000000.0
 493964              2062                       49       2500000.0
 495732              2062                       49       8100000.0
 498165              2062                       49       4000000.0
 499699              2062                       49       3400000.0

        porte_empresa ente_federativo_responsavel
 159               03                        None
 1708              03                        None
 6472              03                        None
 8871              03                        None
 10165             03                        None
 ...              ...                         ...
 492624            03                        None
 493964            03                        None
 495732            03                        None
 498165            03                        None
 499699            03                        None

 [172 rows x 7 columns],
        cnpj_basico                                       razao_social  \
 5883      49526756  GCX AGRONEGOCIO PARTICIPACOES E EMPREENDIMENTO...
 12938     49533864           49.533.864 EVANDILSON FREITAS DE ANDRADE
 13583     49534509                                 AGRO SUCUPIRA LTDA
 14974     49535902                       JCS PIASSA AGRONEGOCIOS LTDA
 17294     49538222                        AGROPECUARIA SAO PEDRO LTDA
 ...            ...                                                ...
 492704    50015412     IRMAS UNIDAS ADMINISTRACAO E PARTICIPACAO LTDA
 494262    50017040                 APOLLO ADMINISTRADORA DE BENS LTDA
 496785    50019563              APLOTERRA ADMINISTRADORA DE BENS LTDA
 498081    50020867  CIGA PARTICIPACOES E INVESTIMENTOS PATRIMONIAI...
 499407    50022202                                    50.022.202 LTDA

        natureza_juridica qualificacao_responsavel  capital_social  \
 5883                2062                       49       4000000.0
 12938               2135                       50       4000000.0
 13583               2062                       49       9150000.0
 14974               2062                       49      94296000.0
 17294               2062                       49      12705000.0
 ...                  ...                      ...             ...
 492704              2062                       49       7100000.0
 494262              2062                       49       8313000.0
 496785              2062                       05       2370000.0
 498081              2062                       05       7950000.0
 499407              2062                       49     987000000.0

        porte_empresa ente_federativo_responsavel
 5883              03                        None

In [ ]:
df_alvos = pd.concat(alvos, ignore_index = True)

df_alvos

,cnpj_basico,razao_social,natureza_juridica,qualificacao_responsavel,capital_social,porte_empresa,ente_federativo_responsavel
0,41276622,AGROPECUARIA ISA LTDA,2062,49,8144885.36,03,None
1,41278312,AGROPECUARIA STABILLE & MOURA LTDA,2062,49,11468152.00,03,None
2,41280730,A. S. DOS SANTOS LTDA,2062,49,2800000.00,03,None
3,41286450,LEPAUS IMPORTADORA LTDA,2062,49,5000000.00,03,None
4,41299018,C3R3 LOCACAO E ADMINISTRACAO DE IMOVEIS SPE LTDA,2062,05,13510000.00,03,None
...,...,...,...,...,...,...,...
28568,41254671,TOTAL GARANTIDORA LTDA,2062,49,3000000.00,03,None
28569,41262698,GFM EDIFICACOES LTDA,2062,49,2200000.00,03,None
28570,41263636,TERRA LEIMBACH LTDA,2062,49,6500000.00,03,None
28571,41265196,CMZ PARTICIPACOES LTDA.,2062,49,6821414.00,03,None
28572,41269944,PROTELAS COMERCIO DE TELAS DE PROTECAO LTDA,2062,49,2210000.00,03,None

In [ ]:
df_alvos.to_csv('alvos_aquisicao_epp.csv', index = False, sep = ';', encoding = 'utf-8-sig')

**5. Campanha de Softwares para Padarias (Foco em Concatenação e Nulos)**
Uma startup desenvolveu um ERP para padarias e confeitarias. Eles farão uma campanha mista (ligação e e-mail) e precisam de uma tabela preparada.
* **Tarefa:** Pesquise o CNAE principal relacionado à "Fabricação de produtos de padaria e confeitaria com predominância de produção própria". Filtre as empresas ativas. Crie uma **nova coluna** na tabela combinando o DDD e o Telefone em um único campo de texto. Como muitas padarias não preenchem o e-mail, em vez de excluir essas linhas, preencha todos os valores nulos/vazios da coluna de correio eletrônico com o texto "NÃO INFORMADO". Exporte a lista final para `contatos_padarias.csv`.

In [ ]:
import random

path_estabs = random.sample(dados_estab, 5)

path_estabs

['C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_45.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos2_6.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos9_8.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos3_3.parquet',
 'C:\\Users\\mayma\\Documents\\Projetos\\Big_data-Consulta_CNPJ_Brasil\\Base_de_dados_parquet\\Estabelecimentos0_27.parquet']

In [ ]:
estab_amostras = []

for path in path_estabs:
    df = pd.read_parquet(path)
    estab_amostras.append(df)

amostras_estabs = pd.concat(estab_amostras, ignore_index = True)

amostras_estabs

,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,nome_fantasia,situacao_cadastral,data_situacao_cadastral,motivo_situacao_cadastral,nome_cidade_exterior,pais,...,municipio,ddd_1,telefone_1,ddd_2,telefone_2,ddd_fax,fax,correio_eletronico,situacao_especial,data_situacao_especial
0,67464123,0001,54,1,None,08,20081231,71,None,None,...,7107,None,None,None,None,None,None,None,None,None
1,12447538,0001,28,1,None,08,20081231,71,None,None,...,2785,None,None,None,None,None,None,None,None,None
2,50802255,0001,46,1,HOSPITAL SANTA TEREZINHA,08,20081231,71,None,None,...,6201,None,None,None,None,None,None,None,None,None
3,87444519,0001,47,1,None,08,19810623,01,None,None,...,8791,None,None,None,None,None,None,None,None,None
4,87447371,0001,02,1,None,04,20180913,63,None,None,...,8791,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499995,55399320,0001,58,1,JULIANA REIS ODONTOLOGIA,02,20240605,00,None,None,...,4123,31,93505850,None,None,None,None,JUSILVA907@GMAIL.COM,None,None
2499996,55400281,0001,61,1,None,02,20240605,00,None,None,...,0011,69,99952709,None,None,None,None,LIMAANDERSON4444@GMAIL.COM,None,None
2499997,55401342,0001,05,1,None,02,20240605,00,None,None,...,8883,54,81151207,None,None,None,None,ANEDALLAGO@HOTMAIL.COM,None,None
2499998,55402027,0001,00,1,None,02,20240605,00,None,None,...,1367,21,65384184,None,None,None,None,RODRIGUESBEEA2@GMAIL.COM,None,None
2499999,55403522,0001,26,1,"S&M (CONSULTORIA, DATA SCIENCE E AUTOMACAO)",02,20240605,00,None,105,...,7107,41,98880068,0000,00000000,None,None,ABERTURA@CONTABILIZEI.COM.BR,None,None

In [ ]:
amostras_estabs.columns

Index(['cnpj_basico', 'cnpj_ordem', 'cnpj_dv', 'identificador_matriz_filial',
       'nome_fantasia', 'situacao_cadastral', 'data_situacao_cadastral',
       'motivo_situacao_cadastral', 'nome_cidade_exterior', 'pais',
       'data_inicio_atividade', 'cnae_fiscal_principal',
       'cnae_fiscal_secundaria', 'tipo_logradouro', 'logradouro', 'numero',
       'complemento', 'bairro', 'cep', 'uf', 'municipio', 'ddd_1',
       'telefone_1', 'ddd_2', 'telefone_2', 'ddd_fax', 'fax',
       'correio_eletronico', 'situacao_especial', 'data_situacao_especial'],
      dtype='object')

In [ ]:
amostras_estabs[amostras_estabs['cnae_fiscal_principal'] == '1091102'][['cnae_fiscal_principal', 'nome_fantasia']]

        cnae_fiscal_principal         nome_fantasia
1638                  1091102         PADARIA IDEAL
4459                  1091102       PADARIA AVENIDA
7974                  1091102  CONFEITARIA IPIRANGA
9805                  1091102    BIG PAES DE QUEIJO
15165                 1091102    PADARIA SONHO REAL
...                       ...                   ...
2499751               1091102                  None
2499768               1091102                  None
2499772               1091102                  None
2499910               1091102                  None
2499927               1091102                  None

[13225 rows x 2 columns]

In [ ]:
amostras_estabs['cnae_fiscal_principal'].value_counts()

cnae_fiscal_principal
4781400    113231
8888888    104427
9492800    103487
5611203     77809
4712100     62597
            ...
8690902         1
6424702         1
0899101         1
0322106         1
4623107         1
Name: count, Length: 1313, dtype: int64

In [ ]:
amostras_estabs[amostras_estabs['cnae_fiscal_principal'].str.contains('1091102', na = False)]['cnae_fiscal_principal']

        cnae_fiscal_principal         nome_fantasia
1638                  1091102         PADARIA IDEAL
4459                  1091102       PADARIA AVENIDA
7974                  1091102  CONFEITARIA IPIRANGA
9805                  1091102    BIG PAES DE QUEIJO
15165                 1091102    PADARIA SONHO REAL
...                       ...                   ...
2499751               1091102                  None
2499768               1091102                  None
2499772               1091102                  None
2499910               1091102                  None
2499927               1091102                  None

[13225 rows x 2 columns]

In [ ]:
padarias = []

for path in dados_estab:
    df = pd.read_parquet(path)

    filtros = ((df['situacao_cadastral'] == '02') & (df['cnae_fiscal_principal'] == '1091102')) 

    df_filtrado = df[filtros]

    if not df_filtrado.empty:
        padarias.append(df_filtrado)

    del df
    gc.collect()

padarias

[       cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 8125      04102220       0001      87                           1
 10147     05759812       0001      39                           1
 12115     05766104       0001      25                           1
 13717     00788892       0001      37                           1
 14630     02414106       0001      67                           1
 ...            ...        ...     ...                         ...
 482503    41692054       0001      42                           1
 487890    01568510       0001      22                           1
 490047    41821216       0001      03                           1
 491121    79081816       0001      47                           1
 491969    03216047       0001      85                           1

                                 nome_fantasia situacao_cadastral  \
 8125                                     None                 02
 10147                                    None                 02
 12115                    PANIFICADORA SAVASSI                 02
 13717                PANIFICADORA PAO DELICIA                 02
 14630                                    None                 02
 ...                                       ...                ...
 482503                                   None                 02
 487890                                   None                 02
 490047                                   None                 02
 491121  PANIFICADORA E CONFEITARIA CENTRAL II                 02
 491969                                   None                 02

        data_situacao_cadastral motivo_situacao_cadastral nome_cidade_exterior  \
 8125                  20001002                        00                 None
 10147                 20051103                        00                 None
 12115                 20030711                        00                 None
 13717                 20040619                        00                 None
 14630                 20001223                        00                 None
 ...                        ...                       ...                  ...
 482503                20050604                        00                 None
 487890                20210807                        00                 None
 490047                20050507                        00                 None
 491121                20050129                        00                 None
 491969                20051103                        00                 None

         pais  ... municipio ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax  \
 8125    None  ...      6941   014    4481169  None       None    None
 10147   None  ...      6291  None       None  None       None    None
 12115   None  ...      9701    61   32018092  None       None    None
 13717   None  ...      7535    41   32484942  None       None    None
 14630   None  ...      8881    55   96953517  None       None    None
 ...      ...  ...       ...   ...        ...   ...        ...     ...
 482503  None  ...      4599  None       None  None       None    None
 487890  None  ...      6291    19   32420149  None       None    None
 490047  None  ...      0726  None       None  None       None    None
 491121  None  ...      7749  None       None  None       None    None
 491969  None  ...      7183    12   36085717    12   34111780      12

              fax     correio_eletronico situacao_especial  \
 8125        None                   None              None
 10147       None                   None              None
 12115       None                   None              None
 13717       None                   None              None
 14630       None  BRANCA.TANE@GMAIL.COM              None
 ...          ...                    ...               ...
 482503      None                   None              None
 487890      None   BIASOFIATO@GMAIL.COM              None
 490047      None                   None              None
 491121      None                   None              None
 491969  36085717  DIFLEITE@TERRA.COM.BR              None

        data_situacao_especial
 8125                     None
 10147                    None
 12115                    None
 13717                    None
 14630                    None
 ...                       ...
 482503                   None
 487890                   None
 490047                   None
 491121                   None
 491969                   None

 [198 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 0         42030517       0001      73                           1
 610       42037170       0001      90                           1
 752       42038683       0001      16                           1
 1424      42045932       0001      09                           1
 1912      42051365       0001      95                           1
 ...            ...        ...     ...                         ...
 498676    46612394       0001      30                           1
 499171    46618113       0001      56                           1
 499297    46619543       0001      92                           1
 499525    46622126       0001      07                           1
 499880    46626193       0001      91                           1

        nome_fantasia situacao_cadastral data_situacao_cadastral  \
 0               None                 02                20210520
 610             None                 02                20210521
 752             None                 02                20241114
 1424            None                 02                20210521
 1912            None                 02                20210523
 ...              ...                ...                     ...
 498676          None                 02                20220531
 499171          None                 02                20220601
 499297          None                 02                20220601
 499525          None                 02                20220601
 499880          None                 02                20220601

        motivo_situacao_cadastral nome_cidade_exterior  pais  ... municipio  \
 0                             00                 None  None  ...      7535
 610                           00                 None  None  ...      6219
 752                           00                 None  None  ...      3913
 1424                          00                 None  None  ...      7099
 1912                          00                 None  None  ...      6213
 ...                          ...                  ...   ...  ...       ...
 498676                        00                 None  None  ...      2531
 499171                        00                 None  None  ...      1429
 499297                        00                 None  None  ...      7107
 499525                        00                 None  None  ...      2381
 499880                        00                 None  None  ...      0808

        ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax   fax  \
 0         41   32499121  None       None    None  None
 610       14   88102858  None       None    None  None
 752       71   86118323  None       None    None  None
 1424      16   96222018  None       None    None  None
 1912      11   94864445  None       None    None  None
 ...      ...        ...   ...        ...     ...   ...
 498676    81   98941476  None       None    None  None
 499171    88   97130188  None       None    None  None
 499297    11   41934344  None       None    None  None
 499525    81   37241700  None       None    None  None
 499880    17   97650111  None       None    None  None

                       correio_eletronico situacao_especial  \
 0               ANAMENDES094@HOTMAIL.COM              None
 610                  RUTYNHAJU@GMAIL.COM              None
 752                 PCCEZAR220@GMAIL.COM              None
 1424         A.P.SABRINA.PEREZ@GMAIL.COM              None
 1912              RAY-FURLAN@HOTMAIL.COM              None
 ...                                  ...               ...
 498676       PEDROLEITEDOCEIRO@GMAIL.COM              None
 499171         JAYANEBRAGA2912@GMAIL.COM              None
 499297             LIGIA.MINEI@IG.COM.BR              None
 499525        FABIANASANTOSRC@ICLOUD.COM              None
 499880  CONCEICAOSOUZAMACEDO13@GMAIL.COM              None

        data_situacao_especial
 0                        None
 610                      None
 752                      None
 1424                     None
 1912                     None
 ...                       ...
 498676                   None
 499171                   None
 499297                   None
 499525                   None
 499880                   None

 [1965 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 205       46629933       0001      43                           1
 363       46631779       0001      44                           1
 801       46636796       0001      74                           1
 1218      46641440       0001      29                           1
 1226      46641527       0001      04                           1
 ...            ...        ...     ...                         ...
 498837    52151977       0001      03                           1
 499293    52157008       0001      60                           1
 499378    52157958       0001      94                           1
 499391    52158100       0001      44                           1
 499978    52164398       0001      03                           1

           nome_fantasia situacao_cadastral data_situacao_cadastral  \
 205                None                 02                20220601
 363                None                 02                20220601
 801                None                 02                20220602
 1218    VAINILLA DONUTS                 02                20220602
 1226               None                 02                20220602
 ...                 ...                ...                     ...
 498837             None                 02                20230912
 499293             None                 02                20230912
 499378             None                 02                20230913
 499391             None                 02                20230913
 499978             None                 02                20230913

        motivo_situacao_cadastral nome_cidade_exterior  pais  ... municipio  \
 205                           00                 None  None  ...      2531
 363                           00                 None  None  ...      9701
 801                           00                 None  None  ...      7053
 1218                          00                 None  None  ...      7097
 1226                          00                 None  None  ...      8605
 ...                          ...                  ...   ...  ...       ...
 498837                        00                 None  None  ...      6303
 499293                        00                 None  None  ...      1389
 499378                        00                 None  None  ...      8683
 499391                        00                 None  None  ...      2051
 499978                        00                 None  None  ...      5813

        ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax       fax  \
 205       81   98825644  None       None    None      None
 363       61   99177188  None       None    None      None
 801       16   39543150  None       None    None      None
 1218      17   92052906    17   91539689      17  92052906
 1226      55   96541631  None       None    None      None
 ...      ...        ...   ...        ...     ...       ...
 498837    16   97524972  None       None    None      None
 499293    85   85890387  None       None    None      None
 499378    51   91174005  None       None    None      None
 499391    83   86425064  None       None    None      None
 499978    22   81661860  None       None    None      None

                  correio_eletronico situacao_especial data_situacao_especial
 205         WILMA.TATIANA@GMAIL.COM              None                   None
 363     PEREIRAVIRGINIA28@GMAIL.COM              None                   None
 801      MURILOMESQUITA01@GMAIL.COM              None                   None
 1218     LUCASBOMBARDA_@HOTMAIL.COM              None                   None
 1226    JULIANEALMEIDA786@GMAIL.COM              None                   None
 ...                             ...               ...                    ...
 498837     FLAVIAFORMICI1@GMAIL.COM              None                   None
 499293  ANACAROLINAMAIA82@GMAIL.COM              None                   None
 499378           LILIDIU@ICLOUD.COM              None                   None
 499391      RAQUELMELO.LP@GMAIL.COM              None                   None
 499978      PYETRADUTRA94@GMAIL.COM              None                   None

 [2296 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 244       52167329       0001      45                           1
 567       52170873       0001      46                           1
 620       52171458       0001      07                           1
 665       52171966       0001      95                           1
 671       52172029       0001      54                           1
 ...            ...        ...     ...                         ...
 499596    57748524       0001      82                           1
 499655    57749163       0001      99                           1
 499669    57749322       0001      55                           1
 499765    57750371       0001      08                           1
 499768    57750403       0001      75                           1

                nome_fantasia situacao_cadastral data_situacao_cadastral  \
 244                     None                 02                20230913
 567                     None                 02                20230913
 620                     None                 02                20230913
 665                     None                 02                20230913
 671                     None                 02                20230913
 ...                      ...                ...                     ...
 499596                  None                 02                20241018
 499655                  None                 02                20241018
 499669                  None                 02                20241018
 499765  PANIFICADORA GENESIS                 02                20241018
 499768                  None                 02                20241018

        motivo_situacao_cadastral nome_cidade_exterior  pais  ... municipio  \
 244                           00                 None  None  ...      0465
 567                           00                 None  None  ...      2117
 620                           00                 None  None  ...      9701
 665                           00                 None  None  ...      2591
 671                           00                 None  None  ...      7107
 ...                          ...                  ...   ...  ...       ...
 499596                        00                 None  None  ...      7057
 499655                        00                 None  None  ...      8735
 499669                        00                 None  None  ...      5705
 499765                        00                 None   105  ...      0921
 499768                        00                 None  None  ...      9073

        ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax   fax  \
 244       83   99803905  None       None    None  None
 567       83   99449203  None       None    None  None
 620       61   83619023  None       None    None  None
 665       87   96611488  None       None    None  None
 671       11   83566217  None       None    None  None
 ...      ...        ...   ...        ...     ...   ...
 499596    11   44444444  None       None    None  None
 499655    54   99208723  None       None    None  None
 499669    27   96055869  None       None    None  None
 499765    98   84401316  0000   00000000    None  None
 499768    67   98445167  None       None    None  None

                    correio_eletronico situacao_especial data_situacao_especial
 244         THYERSONALVES26@GMAIL.COM              None                   None
 567              PRISMS0809@GMAIL.COM              None                   None
 620                ENG.RS@OUTLOOK.COM              None                   None
 665       FABYANNA_ALVES7@HOTMAIL.COM              None                   None
 671          LUCIANA.MODENA@GMAIL.COM              None                   None
 ...                               ...               ...                    ...
 499596  NOGUEIRALARISSA1916@GMAIL.COM              None                   None
 499655           VJANETE654@GMAIL.COM              None                   None
 499669    GALAXIADONUTS.VIX@GMAIL.COM              None                   None
 499765      CIRLENELOUZEIRO@GMAIL.COM              None                   None
 499768           DNOVAES744@GMAIL.COM              None                   None

 [2574 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 2         57752969       0001      36                           1
 45        57753439       0001      02                           1
 208       57755245       0001      46                           1
 287       57756117       0001      17                           1
 373       57757107       0001      04                           1
 ...            ...        ...     ...                         ...
 499314    62709531       0001      05                           1
 499435    62710909       0001      90                           1
 499492    62711560       0001      01                           1
 499766    62714451       0001      48                           1
 499972    62716718       0001      36                           1

        nome_fantasia situacao_cadastral data_situacao_cadastral  \
 2               None                 02                20241018
 45              None                 02                20241018
 208             None                 02                20241018
 287             None                 02                20241019
 373             None                 02                20241019
 ...              ...                ...                     ...
 499314          None                 02                20250914
 499435          None                 02                20250914
 499492          None                 02                20250914
 499766          None                 02                20250915
 499972          None                 02                20250915

        motivo_situacao_cadastral nome_cidade_exterior  pais  ... municipio  \
 2                             00                 None  None  ...      4123
 45                            00                 None  None  ...      3849
 208                           00                 None  None  ...      6001
 287                           00                 None  None  ...      6527
 373                           00                 None  None  ...      7107
 ...                          ...                  ...   ...  ...       ...
 499314                        00                 None  None  ...      7107
 499435                        00                 None  None  ...      7149
 499492                        00                 None  None  ...      5647
 499766                        00                 None  None  ...      8801
 499972                        00                 None  None  ...      4595

        ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax   fax  \
 2         31   85422734  None       None    None  None

In [ ]:
df_padarias = pd.concat(padarias, ignore_index = True)

df_padarias.head()

,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,nome_fantasia,situacao_cadastral,data_situacao_cadastral,motivo_situacao_cadastral,nome_cidade_exterior,pais,...,municipio,ddd_1,telefone_1,ddd_2,telefone_2,ddd_fax,fax,correio_eletronico,situacao_especial,data_situacao_especial
0,04102220,0001,87,1,None,02,20001002,00,None,None,...,6941,014,4481169,None,None,None,None,None,None,None
1,05759812,0001,39,1,None,02,20051103,00,None,None,...,6291,None,None,None,None,None,None,None,None,None
2,05766104,0001,25,1,PANIFICADORA SAVASSI,02,20030711,00,None,None,...,9701,61,32018092,None,None,None,None,None,None,None
3,00788892,0001,37,1,PANIFICADORA PAO DELICIA,02,20040619,00,None,None,...,7535,41,32484942,None,None,None,None,None,None,None
4,02414106,0001,67,1,None,02,20001223,00,None,None,...,8881,55,96953517,None,None,None,None,BRANCA.TANE@GMAIL.COM,None,None

In [ ]:
df_padarias.shape

(201881, 30)

In [ ]:
mascara_fax = df_padarias[['ddd_fax', 'fax']].notnull().all(axis=1)

df_padarias_fax = df_padarias.loc[mascara_fax, ['ddd_fax', 'fax']]

df_padarias_fax

       ddd_fax       fax
8           31  33957673
19          11  47222200
20          32  35381135
23          88  34421006
27          32  32731867
...        ...       ...
197852      32  98502122
197864      19  78155159
198007      73  32819955
198077      89  35621754
199223      61  91094205

[5281 rows x 2 columns]

In [ ]:
df_padarias['telefone_1'] = ('(' + df_padarias['ddd_1'] + ')' + ' ' + df_padarias['telefone_1'])
df_padarias['telefone_2'] = ('(' + df_padarias['ddd_2'] + ')' + ' ' + df_padarias['telefone_2'])
df_padarias['fax'] = ('(' + df_padarias['ddd_fax'] + ')' + ' ' + df_padarias['fax'])

df_padarias = df_padarias.drop(columns = ['ddd_1', 'ddd_2', 'ddd_fax'])

df_padarias['correio_eletronico'] = df_padarias['correio_eletronico'].fillna('NÃO INFORMADO')

df_padarias

,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,nome_fantasia,situacao_cadastral,data_situacao_cadastral,motivo_situacao_cadastral,nome_cidade_exterior,pais,...,municipio,ddd_1,telefone_1,ddd_2,telefone_2,ddd_fax,fax,correio_eletronico,situacao_especial,data_situacao_especial
0,04102220,0001,87,1,None,02,20001002,00,None,None,...,6941,014,(014) 4481169,None,NaN,None,NaN,NÃO INFORMADO,None,None
1,05759812,0001,39,1,None,02,20051103,00,None,None,...,6291,None,NaN,None,NaN,None,NaN,NÃO INFORMADO,None,None
2,05766104,0001,25,1,PANIFICADORA SAVASSI,02,20030711,00,None,None,...,9701,61,(61) 32018092,None,NaN,None,NaN,NÃO INFORMADO,None,None
3,00788892,0001,37,1,PANIFICADORA PAO DELICIA,02,20040619,00,None,None,...,7535,41,(41) 32484942,None,NaN,None,NaN,NÃO INFORMADO,None,None
4,02414106,0001,67,1,None,02,20001223,00,None,None,...,8881,55,(55) 96953517,None,NaN,None,NaN,BRANCA.TANE@GMAIL.COM,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201876,01657060,0001,44,1,None,02,20030125,00,None,None,...,4675,None,NaN,None,NaN,None,NaN,NÃO INFORMADO,None,None
201877,04946477,0001,15,1,PANIFICADORA NOBRE,02,20051103,00,None,None,...,6511,19,(19) 81624483,None,NaN,None,NaN,PADARIANOBREESCRITORIO@GMAIL.COM,None,None
201878,92589720,0001,52,1,None,02,20051103,00,None,None,...,8841,None,NaN,None,NaN,None,NaN,NÃO INFORMADO,None,None
201879,03314961,0001,69,1,CROKANT PAES E DOCES,02,20000930,00,None,None,...,6163,None,NaN,None,NaN,None,NaN,NÃO INFORMADO,None,None
201880,03317439,0001,30,1,None,02,20050827,00,None,None,...,8853,55,(55) 33120000,None,NaN,None,NaN,KEMPERS@KEMPERSHAUS.COM.BR,FALIDO,20240311

In [ ]:
df_padarias.to_csv('contatos_padarias.csv', index = False, sep = ';', encoding = 'utf-8-sig')

**6. O *Frame* de Amostragem Estatística (Foco em Dicionários)**
Sua consultoria ganhou uma licitação para realizar uma pesquisa por amostragem rigorosa com donos de restaurantes em todo o estado da Bahia. Você precisa montar a "população" base (o *sampling frame*) com o nome legível das cidades para a equipe de campo.
* **Tarefa:** Descubra o CNAE de "Restaurantes e similares" e filtre a base para obter esses estabelecimentos ativos na Bahia. Carregue a tabela acessória de Municípios, transforme-a em um dicionário Python e faça o mapeamento na base principal, substituindo o código numérico do município diretamente pelo seu nome real em texto. Salve a base pronta em `frame_amostragem_restaurantes_ba.parquet`.

O principal CNAE para restaurantes e similares é o 5611-2/01 - Restaurantes e similares

In [3]:
path_municipio = r'C:\Users\mayma\Documents\Projetos\Big_data-Consulta_CNPJ_Brasil\Base_de_dados_parquet\Municipios.parquet'

df_municipio = pd.read_parquet(path_municipio)

df_municipio

     codigo_municipio           nome_municipio
0                0001            GUAJARA-MIRIM
1                0002  ALTO ALEGRE DOS PARECIS
2                0003              PORTO VELHO
3                0004                  BURITIS
4                0005                JI-PARANA
...               ...                      ...
5567             9989               SERRA ALTA
5568             9991                TUNAPOLIS
5569             9993                 GUARINOS
5570             9995               RIO QUENTE
5571             9997         CORONEL SAPUCAIA

[5572 rows x 2 columns]

In [9]:
import random

ind_aleat = random.randrange(len(dados_estab))

estab_aleat = pd.read_parquet(dados_estab[ind_aleat])

estab_aleat

,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,nome_fantasia,situacao_cadastral,data_situacao_cadastral,motivo_situacao_cadastral,nome_cidade_exterior,pais,...,municipio,ddd_1,telefone_1,ddd_2,telefone_2,ddd_fax,fax,correio_eletronico,situacao_especial,data_situacao_especial
0,07396865,0001,68,1,None,08,20170210,01,None,None,...,8297,47,33851125,47,33851125,47,33851125,None,None,None
1,64904295,0018,51,2,None,08,20161110,01,None,None,...,2785,11,36491000,31,33880436,82,33118379,CLAUDIO.GIGLIO@CAMIL.COM.BR,None,None
2,76016369,0003,16,2,None,04,20231113,63,None,None,...,7071,None,None,None,None,None,None,None,None,None
3,52302726,0001,82,1,None,04,20210406,63,None,None,...,6131,None,None,None,None,None,None,None,None,None
4,03618479,0001,12,1,None,02,20000201,00,None,None,...,7607,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,06770053,0001,78,1,None,08,20041231,01,None,None,...,5113,None,None,None,None,None,None,None,None,None
499996,36936888,0001,16,1,ELETRONICA ALVES,08,20081231,71,None,None,...,9091,None,None,None,None,None,None,None,None,None
499997,06770056,0001,01,1,None,08,20041231,01,None,None,...,4639,None,None,None,None,None,None,None,None,None
499998,74510892,0001,07,1,IR,08,19961015,01,None,None,...,7107,None,None,None,None,None,None,None,None,None
499999,02855066,0001,99,1,None,04,20181009,63,None,None,...,9625,None,None,None,None,None,None,None,None,None

In [11]:
estab_aleat['municipio']

0         8297
1         2785
2         7071
3         6131
4         7607
          ...
499995    5113
499996    9091
499997    4639
499998    7107
499999    9625
Name: municipio, Length: 500000, dtype: object

**7. Venda de Modelagem Preditiva para o Varejo (Foco em Listas)**
Você desenvolveu um algoritmo de segmentação de clientes e quer vender para o varejo alimentar (supermercados, hipermercados e minimercados), pois eles têm grande volume de dados.
* **Tarefa:** Pesquise os códigos CNAE exatos para Supermercados, Hipermercados e Minimercados. Crie uma lista no Python contendo esses três códigos. Acesse a base de Estabelecimentos e faça um único filtro passando essa lista, de modo a extrair todas as empresas ativas do Brasil que se enquadrem em qualquer uma dessas três categorias simultaneamente. Exporte os potenciais clientes encontrados para `leads_modelagem_varejo.csv`.

**8. Terceirização de Coleta de Dados (Foco em Agrupamento)**
Sua consultoria fechou um contrato de abrangência nacional, mas você precisa mapear em quais estados há maior concentração de parceiros e concorrentes locais para terceirizar a aplicação de questionários.
* **Tarefa:** Pesquise o CNAE referente a "Pesquisas de mercado e de opinião pública" e filtre as empresas ativas no Brasil inteiro que atuam nessa atividade. Em vez de gerar um mailing de contatos, crie uma tabela estatística agrupando os dados para mostrar a **contagem total de empresas ativas por Estado (UF)**. Ordene a tabela do estado com mais parceiros para o estado com menos e salve em `ranking_estados_pesquisa.csv`.

O CNAE principal para "Pesquisas de mercado e de opinião pública" é o 7320-3/00.

In [ ]:
amostras_estabs[((amostras_estabs['cnae_fiscal_principal'] == '7320300') | (amostras_estabs['cnae_fiscal_secundaria'].str.contains('7320300', na = False)))][['cnae_fiscal_principal', 'cnae_fiscal_secundaria', 'nome_fantasia']]

,cnae_fiscal_principal,cnae_fiscal_secundaria,nome_fantasia
4529,9430800,"6209100,6311900,6619399,7119704,7220700,731140...",None
15136,7320300,None,None
19773,8230001,"4759899,7320300,7020400,8599604,7830200",None
19776,7320300,None,None
22983,7320300,None,None
...,...,...,...
2495205,8211300,"8219999,7320300",KMHG
2495896,8230001,"6319400,7319002,7320300,8599604",LIBRA ENTRETENIMENTOS
2497148,7319003,"5812302,5813100,5819100,5912099,7020400,731140...",BACUPARI COMUNICA
2498990,6619399,"5920100,6622300,7311400,7312200,7319002,731900...",None
2499940,8211300,"8299799,8220200,7020400,7319004,7320300,960929...",None

In [ ]:
estabelecimentos = []

for path_estab in dados_estab:
    df_estab = pd.read_parquet(path_estab)

    filtros = ((df_estab['cnae_fiscal_principal'] == '7320300') | (df_estab['cnae_fiscal_secundaria'].str.contains('7320300', na = False)) &
               (df_estab['situacao_cadastral'] == '02'))
    
    df_filtrado = df_estab[filtros]

    if not df_filtrado.empty:
        estabelecimentos.append(df_filtrado)

    del df_estab
    gc.collect()

estabelecimentos

[       cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 303       02373341       0001      38                           1
 1382      00755147       0001      91                           1
 5466      05744796       0001      00                           1
 5666      00766671       0001      68                           1
 5877      02389145       0001      51                           1
 ...            ...        ...     ...                         ...
 492899    03217708       0001      97                           1
 495885    60578481       0001      49                           1
 496265    07192048       0001      98                           1
 497138    07192765       0001      10                           1
 498550    41985243       0001      03                           1

                     nome_fantasia situacao_cadastral data_situacao_cadastral  \
 303                     IEL/NR-AC                 02                20041224
 1382     CPA - CREDIT PARK ADVICE                 02                20241126
 5466                   PARNATALLE                 02                20030627
 5666    KAUS LEATHERS DEVELOPMENT                 08                20150909
 5877                         None                 02                20210520
 ...                           ...                ...                     ...
 492899                  EMBRAPLEX                 02                20181222
 495885                       None                 02                20220118
 496265                       None                 08                20161116
 497138                       None                 08                20120925
 498550          R. L. CONSULTORIA                 08                20100325

        motivo_situacao_cadastral nome_cidade_exterior  pais  ... municipio  \
 303                           00                 None  None  ...      0139
 1382                          00                 None  None  ...      6001
 5466                          00                 None  None  ...      1761
 5666                          01                 None  None  ...      8877
 5877                          00                 None  None  ...      4123
 ...                          ...                  ...   ...  ...       ...
 492899                        00                 None  None  ...      5857
 495885                        00                 None  None  ...      7107
 496265                        01                 None  None  ...      7493
 497138                        01                 None  None  ...      7047
 498550                        01                 None  None  ...      3515

        ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax       fax  \
 303       68   32124271  None       None     068   2124274
 1382      21   22544545    21   25545454      21  21212124
 5466      84   94816420  None       None    None      None
 5666      51   35882322  None       None    None      None
 5877      31   98193029  None       None    None      None
 ...      ...        ...   ...        ...     ...       ...
 492899    21   24840000  None       None    None      None
 495885    11   86896105  None       None      11  29353005
 496265    45   91173534  None       None    None      None
 497138  None       None  None       None    None      None
 498550  None       None  None       None    None      None

                       correio_eletronico situacao_especial  \
 303                     IEL@IELAC.ORG.BR              None
 1382                   lene79@bol.com.br              None
 5466           NATALUSKASANTOS@GMAIL.COM              None
 5666                                None              None
 5877    PAULO@MERCADORCONSULTORES.COM.BR              None
 ...                                  ...               ...
 492899             DLCMARTINS@UOL.COM.BR              None
 495885      CARAIBAS@CARAIBASPART.COM.BR              None
 496265                              None              None
 497138                              None              None
 498550                              None              None

        data_situacao_especial
 303                      None
 1382                     None
 5466                     None
 5666                     None
 5877                     None
 ...                       ...
 492899                   None
 495885                   None
 496265                   None
 497138                   None
 498550                   None

 [191 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 638       36288437       0001      10                           1
 3113      42064545       0001      01                           1
 3194      42065403       0001      69                           1
 5236      41627201       0001      09                           1
 6130      42096728       0001      09                           1
 ...            ...        ...     ...                         ...
 491787    46534067       0001      07                           1
 491921    46535544       0001      59                           1
 492747    46151206       0001      13                           1
 494258    46561909       0001      10                           1
 498087    46605628       0001      11                           1

                                          nome_fantasia situacao_cadastral  \
 638                                           IMVESTER                 02
 3113      QUANTO NETWORK INSTITUICAO DE PAGAMENTO LTDA                 02
 3194                                               LMC                 02
 5236                                    BOX EMBALAGENS                 02
 6130                              ANCORA X COMUNICACAO                 02
 ...                                                ...                ...
 491787                                  JK CONSULTORIA                 02
 491921  FF INVEST ATIVOS PARTICIPACOES E SERVICOS LTDA                 02
 492747                        FAMIGRAF EDITORA GRAFICA                 02
 494258     ABACO CONTABILIDADE & ADMINISTRACAO PUBLICA                 02
 498087                  TORA PROJETOS E PRODUCOES LTDA                 02

        data_situacao_cadastral motivo_situacao_cadastral nome_cidade_exterior  \
 638                   20200207                        00                 None
 3113                  20210524                        00                 None
 3194                  20210524                        00                 None
 5236                  20210419                        00                 None
 6130                  20210526                        00                 None
 ...                        ...                       ...                  ...
 491787                20220525                        00                 None
 491921                20220525                        00                 None
 492747                20220426                        00                 None
 494258                20220527                        00                 None
 498087                20220531                        00                 None

         pais  ... municipio ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax   fax  \
 638     None  ...      7107    11   63518908  None       None    None  None
 3113    None  ...      7107    11   32722900  None       None    None  None
 3194    None  ...      7107    11   30789626  None       None    None  None
 5236    None  ...      6563    11   43802244  None       None    None  None
 6130    None  ...      1981    83   96065982  None       None    None  None
 ...      ...  ...       ...   ...        ...   ...        ...     ...   ...
 491787   105  ...      3191    79   99397541  None       None    None  None
 491921  None  ...      7107    11   30823322  None       None    None  None
 492747   105  ...      8543    55   35381017  0000   00000000    None  None
 494258  None  ...      5393    38   35272696  None       None    None  None
 498087  None  ...      7119    11   97016671  None       None    None  None

                              correio_eletronico situacao_especial  \
 638                           RACTT80@GMAIL.COM              None
 3113                    SALVADOR@MSAUDIT.COM.BR              None
 3194                   C.LANG@LAVIEMARKETING.FR              None
 5236               CLEITON@BOXEMBALAGENS.COM.BR              None
 6130               ANCORAXCOMUNICACAO@GMAIL.COM              None
 ...                                         ...               ...
 491787                        JKS1001@GMAIL.COM              None
 491921               MICHEL@FARAHSERVICE.COM.BR              None
 492747  CONTABILIDADE@ESCRITORIOPRESENCA.COM.BR              None
 494258                  MEIRECONTA@YAHOO.COM.BR              None
 498087                   PROJETOSTORA@GMAIL.COM              None

        data_situacao_especial
 638                      None
 3113                     None
 3194                     None
 5236                     None
 6130                     None
 ...                       ...
 491787                   None
 491921                   None
 492747                   None
 494258                   None
 498087                   None

 [386 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 1770      46647742       0001      04                           1
 2670      46658029       0001      66                           1
 2954      46661277       0001      66                           1
 5019      46684640       0001      69                           1
 7092      46708311       0001      00                           1
 ...            ...        ...     ...                         ...
 492729    52085822       0001      16                           1
 493763    29149265       0002      19                           2
 494260    52101986       0001      90                           1
 496596    52127667       0001      53                           1
 496866    47400063       0001      07                           1

                                       nome_fantasia situacao_cadastral  \
 1770                                           None                 02
 2670                                           None                 02
 2954                        B2030 AI SEE THE FUTURE                 02
 5019    PCS PROJETOS E GESTAO DE COMUNICACAO SOCIAL                 02
 7092                        ZE PRODUCOES E EVEN TOS                 02
 ...                                             ...                ...
 492729                                 OVNI DIGITAL                 02
 493763                                         None                 02
 494260                       MAGDA RIBEIRO BARCELOS                 02
 496596              ALIQUA INTERMEDICAO DE NEGOCIOS                 02
 496866                         BOOMERANG BRINQUEDOS                 02

        data_situacao_cadastral motivo_situacao_cadastral nome_cidade_exterior  \
 1770                  20220603                        00                 None
 2670                  20220603                        00                 None
 2954                  20220603                        00                 None
 5019                  20241228                        00                 None
 7092                  20220608                        00                 None
 ...                        ...                       ...                  ...
 492729                20230905                        00                 None
 493763                20230906                        00                 None
 494260                20230906                        00                 None
 496596                20230911                        00                 None
 496866                20220803                        00                 None

         pais  ... municipio ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax  \
 1770     105  ...      7777    42   98069101  None       None    None
 2670    None  ...      6713    11   86406697  None       None    None
 2954     105  ...      9051    67   81334444  None       None    None
 5019     105  ...      7107    11   52385356  0000   00000000    None
 7092     105  ...      7107    11   66349393  0000   00000000    None
 ...      ...  ...       ...   ...        ...   ...        ...     ...
 492729   105  ...      2785    82   88121852  0000   00000000    None
 493763  None  ...      6425    16   34323656  None       None    None
 494260   105  ...      8801    51   91422662  0000   00000000    None
 496596  None  ...      7107    11   22222222    11   33333333      11
 496866   105  ...      9519    63   33612400  0000   00000000    None

              fax             correio_eletronico situacao_especial  \
 1770        None            LDNLAADIN@GMAIL.COM              None
 2670        None        MARIO_FARMA@HOTMAIL.COM              None
 2954        None             B2030.MA@GMAIL.COM              None
 5019        None              PAULO@IIPR.COM.BR              None
 7092        None         CONTATO@DOMALFA.COM.BR              None
 ...          ...                            ...               ...
 492729      None  FINANCEIRO@OVNIAUDIOVIDEO.COM              None
 493763      None            NERI091@HOTMAIL.COM              None
 494260      None              MAGDARB@GMAIL.COM              None
 496596  44444444  ALIQUAINTERNEGOCIOS@GMAIL.COM              None
 496866      None   ROMULO.CONTABEIS@OUTLOOK.COM              None

        data_situacao_especial
 1770                     None
 2670                     None
 2954                     None
 5019                     None
 7092                     None
 ...                       ...
 492729                   None
 493763                   None
 494260                   None
 496596                   None
 496866                   None

 [377 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 1552      50245724       0001      73                           1
 1565      52181639       0001      14                           1
 2462      52191431       0001      86                           1
 3230      52199729       0001      32                           1
 7502      52245997       0001      43                           1
 ...            ...        ...     ...                         ...
 494861    57697482       0001      06                           1
 496349    55064842       0002      80                           2
 496439    57714407       0001      06                           1
 497472    57725716       0001      73                           1
 497766    57728822       0001      00                           1

                                             nome_fantasia situacao_cadastral  \
 1552    ECOMAIS ENGENHARIA AMBIENTAL E SEGURANCA DO TR...                 02
 1565                ALB SOLUCOES EM TECNOLOGIA E INOVACAO                 02
 2462                                                 None                 02
 3230                            PERPETUUS GROWTH VENTURES                 02
 7502                                                 None                 02
 ...                                                   ...                ...
 494861                                   ANDRADE SERVICOS                 02
 496349                                               None                 02
 496439                            AGENCIA HUB COMUNICACAO                 02
 497472                               R9 WINNER ASSESSORIA                 02
 497766                                            IMAGGIO                 02

        data_situacao_cadastral motivo_situacao_cadastral nome_cidade_exterior  \
 1552                  20230409                        00                 None
 1565                  20230914                        00                 None
 2462                  20230915                        00                 None
 3230                  20230915                        00                 None
 7502                  20230920                        00                 None
 ...                        ...                       ...                  ...
 494861                20241015                        00                 None
 496349                20241016                        00                 None
 496439                20241016                        00                 None
 497472                20241017                        00                 None
 497766                20241017                        00                 None

         pais  ... municipio ddd_1 telefone_1 ddd_2 telefone_2 ddd_fax  \
 1552     105  ...      0483    94   81068031  None       None    None
 1565     105  ...      8801    51   98581847  None       None    None
 2462     105  ...      1829    84   94341993    84   90000000    None
 3230    None  ...      8985    66   96181212  None       None    None
 7502    None  ...      4123    31   30284826  None       None    None
 ...      ...  ...       ...   ...        ...   ...        ...     ...
 494861  None  ...      2699    38   99220576  None       None    None
 496349  None  ...      7107    21   21228220    21   38448000      11
 496439  None  ...      0595    94   81154203  None       None    None
 497472  None  ...      2499    81   99121000  None       None    None
 497766  None  ...      7057    11   74691865  None       None    None

              fax                    correio_eletronico situacao_especial  \
 1552        None                   ECOMAISPA@GMAIL.COM              None
 1565        None                 ANDRE.BI.FV@GMAIL.COM              None
 2462        None  LIMAARQUITETURAEENGENHARIA@GMAIL.COM              None
 3230        None      LUISFELIPESANTOSZXCV@HOTMAIL.COM              None
 7502        None     LEGALIZACAO@MGRCONSULTORES.COM.BR              None
 ...          ...                                   ...               ...
 494861      None       ANDRADESINCORPORACOES@GMAIL.COM              None
 496349  99999999         JURIDICO@GRUPODREAMERS.COM.BR              None
 496439      None             WAGNERSANTTOS@OUTLOOK.COM              None
 497472      None                    RUDEMSON@GMAIL.COM              None
 497766      None                CONTATO@IMAGGIO.COM.BR              None

        data_situacao_especial
 1552                     None
 1565                     None
 2462                     None
 3230                     None
 7502                     None
 ...                       ...
 494861                   None
 496349                   None
 496439                   None
 497472                   None
 497766                   None

 [291 rows x 30 columns],
        cnpj_basico cnpj_ordem cnpj_dv identificador_matriz_filial  \
 1187      57766330       0001      00                           1
 1564      57770392       0001      95                           1
 2916      57785068       0001      40                           1
 6093      57819786       0001      90                           1
 6220      57821123       0001      00                           1
 ...            ...        ...     ...                         ...
 493574    62645371       0001      88                           1
 496902    62682534       0001      00                           1
 497730    62691725       0001      20                           1
 497926    62693928       0001      56                           1
 498246    29649211       0002      12                           2

             nome_fantasia situacao_cadastral data_situacao_cadastral  \
 1187                 KOGN                 02                20241021
 1564                 None                 02                20241021
 2916         CAMPO JUNIOR                 02                20240718

In [ ]:
df_op_publica = pd.concat(estabelecimentos, ignore_index = True)

df_op_publica

,cnpj_basico,cnpj_ordem,cnpj_dv,identificador_matriz_filial,nome_fantasia,situacao_cadastral,data_situacao_cadastral,motivo_situacao_cadastral,nome_cidade_exterior,pais,...,municipio,ddd_1,telefone_1,ddd_2,telefone_2,ddd_fax,fax,correio_eletronico,situacao_especial,data_situacao_especial
0,02373341,0001,38,1,IEL/NR-AC,02,20041224,00,None,None,...,0139,68,32124271,None,None,068,2124274,IEL@IELAC.ORG.BR,None,None
1,00755147,0001,91,1,CPA - CREDIT PARK ADVICE,02,20241126,00,None,None,...,6001,21,22544545,21,25545454,21,21212124,lene79@bol.com.br,None,None
2,05744796,0001,00,1,PARNATALLE,02,20030627,00,None,None,...,1761,84,94816420,None,None,None,None,NATALUSKASANTOS@GMAIL.COM,None,None
3,00766671,0001,68,1,KAUS LEATHERS DEVELOPMENT,08,20150909,01,None,None,...,8877,51,35882322,None,None,None,None,None,None,None
4,02389145,0001,51,1,None,02,20210520,00,None,None,...,4123,31,98193029,None,None,None,None,PAULO@MERCADORCONSULTORES.COM.BR,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40070,66141443,0001,00,1,GRUPO AMADOS,02,20260408,00,None,None,...,5813,22,99467746,None,None,None,None,DAVI.SOUZAZA@GMAIL.COM,None,None
40071,66163629,0001,60,1,AXION INTELLIGENCE & INNOVATION,02,20260406,00,None,105,...,1389,88,81362929,0000,00000000,None,None,AXIONINTELLIGENCE@HOTMAIL.COM,None,None
40072,66179439,0001,31,1,R&V SOLUTIONS,02,20260409,00,None,None,...,0529,91,86300043,None,None,None,None,CONTATO@RAMOSEVALADAO.COM.BR,None,None
40073,01663217,0001,44,1,None,08,20010725,01,None,None,...,6619,011,4345908,None,None,None,None,None,None,None
40074,01663597,0001,17,1,None,02,20051103,00,None,None,...,4123,31,34212073,None,None,31,32137748,ATELIEDEPRODUCAO@TERRA.COM.BR,None,None

In [ ]:
df_est_op_publ = pd.DataFrame(df_op_publica['uf'].value_counts())

df_est_op_publ

    count
uf
SP  12296
MG   2909
RJ   2906
PR   2242
RS   1891
BA   1781
DF   1509
GO   1460
CE   1387
SC   1339
PE   1089
MA   1005
AM    944
PA    937
MT    869
ES    784
MS    659
TO    640
PB    495
PI    492
RN    485
RO    397
SE    380
RR    344
AL    295
AC    239
AP    231
EX     70

In [ ]:
df_est_op_publ.to_csv('ranking_estados_pesquisa.csv', index = False, sep = ';', encoding= 'utf-8-sig')

In [ ]:
ranking_estados_pesquisa.csv

Index(['cnpj_basico', 'razao_social', 'natureza_juridica',
       'qualificacao_responsavel', 'capital_social', 'porte_empresa',
       'ente_federativo_responsavel'],
      dtype='object')